/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.junction.api.resources.labreport;

import com.junction.api.core.ClientOptions;
import com.junction.api.core.RequestOptions;
import com.junction.api.resources.labreport.requests.CreateLabReportParserJobBody;
import com.junction.api.resources.labreport.requests.ParserGetJobLabReportRequest;
import com.junction.api.types.ParsingJob;
import java.io.File;

public class LabReportClient {
    protected final ClientOptions clientOptions;

    private final RawLabReportClient rawClient;

    public LabReportClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawLabReportClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawLabReportClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Creates a parse job, uploads the file(s) to provider, persists the job row,
     * and starts the ParseLabReport. Returns a generated job_id.
     */
    public ParsingJob parserCreateJob(File file, CreateLabReportParserJobBody request) {
        return this.rawClient.parserCreateJob(file, request).body();
    }

    /**
     * Creates a parse job, uploads the file(s) to provider, persists the job row,
     * and starts the ParseLabReport. Returns a generated job_id.
     */
    public ParsingJob parserCreateJob(File file, CreateLabReportParserJobBody request, RequestOptions requestOptions) {
        return this.rawClient.parserCreateJob(file, request, requestOptions).body();
    }

    /**
     * Retrieves the parse job status and stored result if completed.
     * <p>Returns:
     * ParseLabResultJobResponse with job status and parsed data (if complete)</p>
     */
    public ParsingJob parserGetJob(String jobId) {
        return this.rawClient.parserGetJob(jobId).body();
    }

    /**
     * Retrieves the parse job status and stored result if completed.
     * <p>Returns:
     * ParseLabResultJobResponse with job status and parsed data (if complete)</p>
     */
    public ParsingJob parserGetJob(String jobId, RequestOptions requestOptions) {
        return this.rawClient.parserGetJob(jobId, requestOptions).body();
    }

    /**
     * Retrieves the parse job status and stored result if completed.
     * <p>Returns:
     * ParseLabResultJobResponse with job status and parsed data (if complete)</p>
     */
    public ParsingJob parserGetJob(String jobId, ParserGetJobLabReportRequest request) {
        return this.rawClient.parserGetJob(jobId, request).body();
    }

    /**
     * Retrieves the parse job status and stored result if completed.
     * <p>Returns:
     * ParseLabResultJobResponse with job status and parsed data (if complete)</p>
     */
    public ParsingJob parserGetJob(String jobId, ParserGetJobLabReportRequest request, RequestOptions requestOptions) {
        return this.rawClient.parserGetJob(jobId, request, requestOptions).body();
    }
}
