/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.junction.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class AggregateFieldExprFunc {
    public static final AggregateFieldExprFunc MAX = new AggregateFieldExprFunc(Value.MAX, "max");

    public static final AggregateFieldExprFunc SUM = new AggregateFieldExprFunc(Value.SUM, "sum");

    public static final AggregateFieldExprFunc MEAN = new AggregateFieldExprFunc(Value.MEAN, "mean");

    public static final AggregateFieldExprFunc STDDEV = new AggregateFieldExprFunc(Value.STDDEV, "stddev");

    public static final AggregateFieldExprFunc OLDEST = new AggregateFieldExprFunc(Value.OLDEST, "oldest");

    public static final AggregateFieldExprFunc MIN = new AggregateFieldExprFunc(Value.MIN, "min");

    public static final AggregateFieldExprFunc NEWEST = new AggregateFieldExprFunc(Value.NEWEST, "newest");

    public static final AggregateFieldExprFunc COUNT = new AggregateFieldExprFunc(Value.COUNT, "count");

    public static final AggregateFieldExprFunc MEDIAN = new AggregateFieldExprFunc(Value.MEDIAN, "median");

    private final Value value;

    private final String string;

    AggregateFieldExprFunc(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof AggregateFieldExprFunc
                        && this.string.equals(((AggregateFieldExprFunc) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case MAX:
                return visitor.visitMax();
            case SUM:
                return visitor.visitSum();
            case MEAN:
                return visitor.visitMean();
            case STDDEV:
                return visitor.visitStddev();
            case OLDEST:
                return visitor.visitOldest();
            case MIN:
                return visitor.visitMin();
            case NEWEST:
                return visitor.visitNewest();
            case COUNT:
                return visitor.visitCount();
            case MEDIAN:
                return visitor.visitMedian();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static AggregateFieldExprFunc valueOf(String value) {
        switch (value) {
            case "max":
                return MAX;
            case "sum":
                return SUM;
            case "mean":
                return MEAN;
            case "stddev":
                return STDDEV;
            case "oldest":
                return OLDEST;
            case "min":
                return MIN;
            case "newest":
                return NEWEST;
            case "count":
                return COUNT;
            case "median":
                return MEDIAN;
            default:
                return new AggregateFieldExprFunc(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        MEAN,

        MIN,

        MAX,

        SUM,

        COUNT,

        MEDIAN,

        STDDEV,

        OLDEST,

        NEWEST,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitMean();

        T visitMin();

        T visitMax();

        T visitSum();

        T visitCount();

        T visitMedian();

        T visitStddev();

        T visitOldest();

        T visitNewest();

        T visitUnknown(String unknownType);
    }
}
