/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.junction.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class AppointmentStatus {
    public static final AppointmentStatus PENDING = new AppointmentStatus(Value.PENDING, "pending");

    public static final AppointmentStatus IN_PROGRESS = new AppointmentStatus(Value.IN_PROGRESS, "in_progress");

    public static final AppointmentStatus RESERVED = new AppointmentStatus(Value.RESERVED, "reserved");

    public static final AppointmentStatus COMPLETED = new AppointmentStatus(Value.COMPLETED, "completed");

    public static final AppointmentStatus CONFIRMED = new AppointmentStatus(Value.CONFIRMED, "confirmed");

    public static final AppointmentStatus CANCELLED = new AppointmentStatus(Value.CANCELLED, "cancelled");

    private final Value value;

    private final String string;

    AppointmentStatus(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof AppointmentStatus && this.string.equals(((AppointmentStatus) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case PENDING:
                return visitor.visitPending();
            case IN_PROGRESS:
                return visitor.visitInProgress();
            case RESERVED:
                return visitor.visitReserved();
            case COMPLETED:
                return visitor.visitCompleted();
            case CONFIRMED:
                return visitor.visitConfirmed();
            case CANCELLED:
                return visitor.visitCancelled();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static AppointmentStatus valueOf(String value) {
        switch (value) {
            case "pending":
                return PENDING;
            case "in_progress":
                return IN_PROGRESS;
            case "reserved":
                return RESERVED;
            case "completed":
                return COMPLETED;
            case "confirmed":
                return CONFIRMED;
            case "cancelled":
                return CANCELLED;
            default:
                return new AppointmentStatus(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        CONFIRMED,

        PENDING,

        RESERVED,

        IN_PROGRESS,

        COMPLETED,

        CANCELLED,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitConfirmed();

        T visitPending();

        T visitReserved();

        T visitInProgress();

        T visitCompleted();

        T visitCancelled();

        T visitUnknown(String unknownType);
    }
}
