/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.junction.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class BulkOpType {
    public static final BulkOpType LINK_BULK_HISTORICAL_TRIGGER =
            new BulkOpType(Value.LINK_BULK_HISTORICAL_TRIGGER, "link_bulk_historical_trigger");

    public static final BulkOpType LINK_BULK_IMPORT = new BulkOpType(Value.LINK_BULK_IMPORT, "link_bulk_import");

    private final Value value;

    private final String string;

    BulkOpType(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other) || (other instanceof BulkOpType && this.string.equals(((BulkOpType) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case LINK_BULK_HISTORICAL_TRIGGER:
                return visitor.visitLinkBulkHistoricalTrigger();
            case LINK_BULK_IMPORT:
                return visitor.visitLinkBulkImport();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static BulkOpType valueOf(String value) {
        switch (value) {
            case "link_bulk_historical_trigger":
                return LINK_BULK_HISTORICAL_TRIGGER;
            case "link_bulk_import":
                return LINK_BULK_IMPORT;
            default:
                return new BulkOpType(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        LINK_BULK_IMPORT,

        LINK_BULK_HISTORICAL_TRIGGER,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitLinkBulkImport();

        T visitLinkBulkHistoricalTrigger();

        T visitUnknown(String unknownType);
    }
}
