/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.junction.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class BulkOpStatus {
    public static final BulkOpStatus SUCCESS = new BulkOpStatus(Value.SUCCESS, "success");

    public static final BulkOpStatus ABORTED = new BulkOpStatus(Value.ABORTED, "aborted");

    public static final BulkOpStatus FAILURE = new BulkOpStatus(Value.FAILURE, "failure");

    public static final BulkOpStatus IN_PROGRESS = new BulkOpStatus(Value.IN_PROGRESS, "in_progress");

    private final Value value;

    private final String string;

    BulkOpStatus(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other) || (other instanceof BulkOpStatus && this.string.equals(((BulkOpStatus) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case SUCCESS:
                return visitor.visitSuccess();
            case ABORTED:
                return visitor.visitAborted();
            case FAILURE:
                return visitor.visitFailure();
            case IN_PROGRESS:
                return visitor.visitInProgress();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static BulkOpStatus valueOf(String value) {
        switch (value) {
            case "success":
                return SUCCESS;
            case "aborted":
                return ABORTED;
            case "failure":
                return FAILURE;
            case "in_progress":
                return IN_PROGRESS;
            default:
                return new BulkOpStatus(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        IN_PROGRESS,

        SUCCESS,

        FAILURE,

        ABORTED,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitInProgress();

        T visitSuccess();

        T visitFailure();

        T visitAborted();

        T visitUnknown(String unknownType);
    }
}
