/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.junction.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.junction.api.core.Nullable;
import com.junction.api.core.NullableNonemptyFilter;
import com.junction.api.core.ObjectMappers;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CheckoutSession.Builder.class)
public final class CheckoutSession {
    private final String checkoutId;

    private final CheckoutSessionStatus status;

    private final OffsetDateTime payBefore;

    private final Optional<String> paymentResourceId;

    private final Optional<String> orderId;

    private final Optional<String> orderTransactionId;

    private final Map<String, Object> additionalProperties;

    private CheckoutSession(
            String checkoutId,
            CheckoutSessionStatus status,
            OffsetDateTime payBefore,
            Optional<String> paymentResourceId,
            Optional<String> orderId,
            Optional<String> orderTransactionId,
            Map<String, Object> additionalProperties) {
        this.checkoutId = checkoutId;
        this.status = status;
        this.payBefore = payBefore;
        this.paymentResourceId = paymentResourceId;
        this.orderId = orderId;
        this.orderTransactionId = orderTransactionId;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("checkout_id")
    public String getCheckoutId() {
        return checkoutId;
    }

    /**
     * @return ℹ️ This enum is non-exhaustive.
     */
    @JsonProperty("status")
    public CheckoutSessionStatus getStatus() {
        return status;
    }

    @JsonProperty("pay_before")
    public OffsetDateTime getPayBefore() {
        return payBefore;
    }

    @JsonIgnore
    public Optional<String> getPaymentResourceId() {
        if (paymentResourceId == null) {
            return Optional.empty();
        }
        return paymentResourceId;
    }

    @JsonIgnore
    public Optional<String> getOrderId() {
        if (orderId == null) {
            return Optional.empty();
        }
        return orderId;
    }

    @JsonIgnore
    public Optional<String> getOrderTransactionId() {
        if (orderTransactionId == null) {
            return Optional.empty();
        }
        return orderTransactionId;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("payment_resource_id")
    private Optional<String> _getPaymentResourceId() {
        return paymentResourceId;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("order_id")
    private Optional<String> _getOrderId() {
        return orderId;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("order_transaction_id")
    private Optional<String> _getOrderTransactionId() {
        return orderTransactionId;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CheckoutSession && equalTo((CheckoutSession) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CheckoutSession other) {
        return checkoutId.equals(other.checkoutId)
                && status.equals(other.status)
                && payBefore.equals(other.payBefore)
                && paymentResourceId.equals(other.paymentResourceId)
                && orderId.equals(other.orderId)
                && orderTransactionId.equals(other.orderTransactionId);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.checkoutId,
                this.status,
                this.payBefore,
                this.paymentResourceId,
                this.orderId,
                this.orderTransactionId);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static CheckoutIdStage builder() {
        return new Builder();
    }

    public interface CheckoutIdStage {
        StatusStage checkoutId(@NotNull String checkoutId);

        Builder from(CheckoutSession other);
    }

    public interface StatusStage {
        /**
         * <p>ℹ️ This enum is non-exhaustive.</p>
         */
        PayBeforeStage status(@NotNull CheckoutSessionStatus status);
    }

    public interface PayBeforeStage {
        _FinalStage payBefore(@NotNull OffsetDateTime payBefore);
    }

    public interface _FinalStage {
        CheckoutSession build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        _FinalStage paymentResourceId(Optional<String> paymentResourceId);

        _FinalStage paymentResourceId(String paymentResourceId);

        _FinalStage paymentResourceId(Nullable<String> paymentResourceId);

        _FinalStage orderId(Optional<String> orderId);

        _FinalStage orderId(String orderId);

        _FinalStage orderId(Nullable<String> orderId);

        _FinalStage orderTransactionId(Optional<String> orderTransactionId);

        _FinalStage orderTransactionId(String orderTransactionId);

        _FinalStage orderTransactionId(Nullable<String> orderTransactionId);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements CheckoutIdStage, StatusStage, PayBeforeStage, _FinalStage {
        private String checkoutId;

        private CheckoutSessionStatus status;

        private OffsetDateTime payBefore;

        private Optional<String> orderTransactionId = Optional.empty();

        private Optional<String> orderId = Optional.empty();

        private Optional<String> paymentResourceId = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(CheckoutSession other) {
            checkoutId(other.getCheckoutId());
            status(other.getStatus());
            payBefore(other.getPayBefore());
            paymentResourceId(other.getPaymentResourceId());
            orderId(other.getOrderId());
            orderTransactionId(other.getOrderTransactionId());
            return this;
        }

        @java.lang.Override
        @JsonSetter("checkout_id")
        public StatusStage checkoutId(@NotNull String checkoutId) {
            this.checkoutId = Objects.requireNonNull(checkoutId, "checkoutId must not be null");
            return this;
        }

        /**
         * <p>ℹ️ This enum is non-exhaustive.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("status")
        public PayBeforeStage status(@NotNull CheckoutSessionStatus status) {
            this.status = Objects.requireNonNull(status, "status must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("pay_before")
        public _FinalStage payBefore(@NotNull OffsetDateTime payBefore) {
            this.payBefore = Objects.requireNonNull(payBefore, "payBefore must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage orderTransactionId(Nullable<String> orderTransactionId) {
            if (orderTransactionId.isNull()) {
                this.orderTransactionId = null;
            } else if (orderTransactionId.isEmpty()) {
                this.orderTransactionId = Optional.empty();
            } else {
                this.orderTransactionId = Optional.of(orderTransactionId.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage orderTransactionId(String orderTransactionId) {
            this.orderTransactionId = Optional.ofNullable(orderTransactionId);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "order_transaction_id", nulls = Nulls.SKIP)
        public _FinalStage orderTransactionId(Optional<String> orderTransactionId) {
            this.orderTransactionId = orderTransactionId;
            return this;
        }

        @java.lang.Override
        public _FinalStage orderId(Nullable<String> orderId) {
            if (orderId.isNull()) {
                this.orderId = null;
            } else if (orderId.isEmpty()) {
                this.orderId = Optional.empty();
            } else {
                this.orderId = Optional.of(orderId.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage orderId(String orderId) {
            this.orderId = Optional.ofNullable(orderId);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "order_id", nulls = Nulls.SKIP)
        public _FinalStage orderId(Optional<String> orderId) {
            this.orderId = orderId;
            return this;
        }

        @java.lang.Override
        public _FinalStage paymentResourceId(Nullable<String> paymentResourceId) {
            if (paymentResourceId.isNull()) {
                this.paymentResourceId = null;
            } else if (paymentResourceId.isEmpty()) {
                this.paymentResourceId = Optional.empty();
            } else {
                this.paymentResourceId = Optional.of(paymentResourceId.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage paymentResourceId(String paymentResourceId) {
            this.paymentResourceId = Optional.ofNullable(paymentResourceId);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "payment_resource_id", nulls = Nulls.SKIP)
        public _FinalStage paymentResourceId(Optional<String> paymentResourceId) {
            this.paymentResourceId = paymentResourceId;
            return this;
        }

        @java.lang.Override
        public CheckoutSession build() {
            return new CheckoutSession(
                    checkoutId,
                    status,
                    payBefore,
                    paymentResourceId,
                    orderId,
                    orderTransactionId,
                    additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
