/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.junction.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.junction.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CheckoutQuoteLineItem.Builder.class)
public final class CheckoutQuoteLineItem {
    private final CheckoutQuoteLineItemCode code;

    private final int amountMinor;

    private final Map<String, Object> additionalProperties;

    private CheckoutQuoteLineItem(
            CheckoutQuoteLineItemCode code, int amountMinor, Map<String, Object> additionalProperties) {
        this.code = code;
        this.amountMinor = amountMinor;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return ℹ️ This enum is non-exhaustive.
     */
    @JsonProperty("code")
    public CheckoutQuoteLineItemCode getCode() {
        return code;
    }

    @JsonProperty("amount_minor")
    public int getAmountMinor() {
        return amountMinor;
    }

    @JsonProperty("currency")
    public String getCurrency() {
        return "USD";
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CheckoutQuoteLineItem && equalTo((CheckoutQuoteLineItem) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CheckoutQuoteLineItem other) {
        return code.equals(other.code) && amountMinor == other.amountMinor;
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.code, this.amountMinor);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static CodeStage builder() {
        return new Builder();
    }

    public interface CodeStage {
        /**
         * <p>ℹ️ This enum is non-exhaustive.</p>
         */
        AmountMinorStage code(@NotNull CheckoutQuoteLineItemCode code);

        Builder from(CheckoutQuoteLineItem other);
    }

    public interface AmountMinorStage {
        _FinalStage amountMinor(int amountMinor);
    }

    public interface _FinalStage {
        CheckoutQuoteLineItem build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements CodeStage, AmountMinorStage, _FinalStage {
        private CheckoutQuoteLineItemCode code;

        private int amountMinor;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(CheckoutQuoteLineItem other) {
            code(other.getCode());
            amountMinor(other.getAmountMinor());
            return this;
        }

        /**
         * <p>ℹ️ This enum is non-exhaustive.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("code")
        public AmountMinorStage code(@NotNull CheckoutQuoteLineItemCode code) {
            this.code = Objects.requireNonNull(code, "code must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("amount_minor")
        public _FinalStage amountMinor(int amountMinor) {
            this.amountMinor = amountMinor;
            return this;
        }

        @java.lang.Override
        public CheckoutQuoteLineItem build() {
            return new CheckoutQuoteLineItem(code, amountMinor, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
