/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.junction.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class ClientFacingElectrocardiogramInconclusiveCause {
    public static final ClientFacingElectrocardiogramInconclusiveCause HIGH_HEART_RATE =
            new ClientFacingElectrocardiogramInconclusiveCause(Value.HIGH_HEART_RATE, "high_heart_rate");

    public static final ClientFacingElectrocardiogramInconclusiveCause POOR_READING =
            new ClientFacingElectrocardiogramInconclusiveCause(Value.POOR_READING, "poor_reading");

    public static final ClientFacingElectrocardiogramInconclusiveCause LOW_HEART_RATE =
            new ClientFacingElectrocardiogramInconclusiveCause(Value.LOW_HEART_RATE, "low_heart_rate");

    private final Value value;

    private final String string;

    ClientFacingElectrocardiogramInconclusiveCause(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof ClientFacingElectrocardiogramInconclusiveCause
                        && this.string.equals(((ClientFacingElectrocardiogramInconclusiveCause) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case HIGH_HEART_RATE:
                return visitor.visitHighHeartRate();
            case POOR_READING:
                return visitor.visitPoorReading();
            case LOW_HEART_RATE:
                return visitor.visitLowHeartRate();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static ClientFacingElectrocardiogramInconclusiveCause valueOf(String value) {
        switch (value) {
            case "high_heart_rate":
                return HIGH_HEART_RATE;
            case "poor_reading":
                return POOR_READING;
            case "low_heart_rate":
                return LOW_HEART_RATE;
            default:
                return new ClientFacingElectrocardiogramInconclusiveCause(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        HIGH_HEART_RATE,

        LOW_HEART_RATE,

        POOR_READING,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitHighHeartRate();

        T visitLowHeartRate();

        T visitPoorReading();

        T visitUnknown(String unknownType);
    }
}
