/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.junction.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class ClientFacingWaistCircumferenceChangedEventType {
    public static final ClientFacingWaistCircumferenceChangedEventType DAILY_DATA_WAIST_CIRCUMFERENCE_UPDATED =
            new ClientFacingWaistCircumferenceChangedEventType(
                    Value.DAILY_DATA_WAIST_CIRCUMFERENCE_UPDATED, "daily.data.waist_circumference.updated");

    public static final ClientFacingWaistCircumferenceChangedEventType DAILY_DATA_WAIST_CIRCUMFERENCE_CREATED =
            new ClientFacingWaistCircumferenceChangedEventType(
                    Value.DAILY_DATA_WAIST_CIRCUMFERENCE_CREATED, "daily.data.waist_circumference.created");

    private final Value value;

    private final String string;

    ClientFacingWaistCircumferenceChangedEventType(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof ClientFacingWaistCircumferenceChangedEventType
                        && this.string.equals(((ClientFacingWaistCircumferenceChangedEventType) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case DAILY_DATA_WAIST_CIRCUMFERENCE_UPDATED:
                return visitor.visitDailyDataWaistCircumferenceUpdated();
            case DAILY_DATA_WAIST_CIRCUMFERENCE_CREATED:
                return visitor.visitDailyDataWaistCircumferenceCreated();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static ClientFacingWaistCircumferenceChangedEventType valueOf(String value) {
        switch (value) {
            case "daily.data.waist_circumference.updated":
                return DAILY_DATA_WAIST_CIRCUMFERENCE_UPDATED;
            case "daily.data.waist_circumference.created":
                return DAILY_DATA_WAIST_CIRCUMFERENCE_CREATED;
            default:
                return new ClientFacingWaistCircumferenceChangedEventType(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        DAILY_DATA_WAIST_CIRCUMFERENCE_CREATED,

        DAILY_DATA_WAIST_CIRCUMFERENCE_UPDATED,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitDailyDataWaistCircumferenceCreated();

        T visitDailyDataWaistCircumferenceUpdated();

        T visitUnknown(String unknownType);
    }
}
