/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.junction.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class ClientFacingSleepApneaAlertChangedEventType {
    public static final ClientFacingSleepApneaAlertChangedEventType DAILY_DATA_SLEEP_APNEA_ALERT_CREATED =
            new ClientFacingSleepApneaAlertChangedEventType(
                    Value.DAILY_DATA_SLEEP_APNEA_ALERT_CREATED, "daily.data.sleep_apnea_alert.created");

    public static final ClientFacingSleepApneaAlertChangedEventType DAILY_DATA_SLEEP_APNEA_ALERT_UPDATED =
            new ClientFacingSleepApneaAlertChangedEventType(
                    Value.DAILY_DATA_SLEEP_APNEA_ALERT_UPDATED, "daily.data.sleep_apnea_alert.updated");

    private final Value value;

    private final String string;

    ClientFacingSleepApneaAlertChangedEventType(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof ClientFacingSleepApneaAlertChangedEventType
                        && this.string.equals(((ClientFacingSleepApneaAlertChangedEventType) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case DAILY_DATA_SLEEP_APNEA_ALERT_CREATED:
                return visitor.visitDailyDataSleepApneaAlertCreated();
            case DAILY_DATA_SLEEP_APNEA_ALERT_UPDATED:
                return visitor.visitDailyDataSleepApneaAlertUpdated();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static ClientFacingSleepApneaAlertChangedEventType valueOf(String value) {
        switch (value) {
            case "daily.data.sleep_apnea_alert.created":
                return DAILY_DATA_SLEEP_APNEA_ALERT_CREATED;
            case "daily.data.sleep_apnea_alert.updated":
                return DAILY_DATA_SLEEP_APNEA_ALERT_UPDATED;
            default:
                return new ClientFacingSleepApneaAlertChangedEventType(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        DAILY_DATA_SLEEP_APNEA_ALERT_CREATED,

        DAILY_DATA_SLEEP_APNEA_ALERT_UPDATED,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitDailyDataSleepApneaAlertCreated();

        T visitDailyDataSleepApneaAlertUpdated();

        T visitUnknown(String unknownType);
    }
}
