/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.junction.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class ClientFacingHeartRateRecoveryOneMinuteChangedEventType {
    public static final ClientFacingHeartRateRecoveryOneMinuteChangedEventType
            DAILY_DATA_HEART_RATE_RECOVERY_ONE_MINUTE_CREATED =
                    new ClientFacingHeartRateRecoveryOneMinuteChangedEventType(
                            Value.DAILY_DATA_HEART_RATE_RECOVERY_ONE_MINUTE_CREATED,
                            "daily.data.heart_rate_recovery_one_minute.created");

    public static final ClientFacingHeartRateRecoveryOneMinuteChangedEventType
            DAILY_DATA_HEART_RATE_RECOVERY_ONE_MINUTE_UPDATED =
                    new ClientFacingHeartRateRecoveryOneMinuteChangedEventType(
                            Value.DAILY_DATA_HEART_RATE_RECOVERY_ONE_MINUTE_UPDATED,
                            "daily.data.heart_rate_recovery_one_minute.updated");

    private final Value value;

    private final String string;

    ClientFacingHeartRateRecoveryOneMinuteChangedEventType(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof ClientFacingHeartRateRecoveryOneMinuteChangedEventType
                        && this.string.equals(((ClientFacingHeartRateRecoveryOneMinuteChangedEventType) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case DAILY_DATA_HEART_RATE_RECOVERY_ONE_MINUTE_CREATED:
                return visitor.visitDailyDataHeartRateRecoveryOneMinuteCreated();
            case DAILY_DATA_HEART_RATE_RECOVERY_ONE_MINUTE_UPDATED:
                return visitor.visitDailyDataHeartRateRecoveryOneMinuteUpdated();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static ClientFacingHeartRateRecoveryOneMinuteChangedEventType valueOf(String value) {
        switch (value) {
            case "daily.data.heart_rate_recovery_one_minute.created":
                return DAILY_DATA_HEART_RATE_RECOVERY_ONE_MINUTE_CREATED;
            case "daily.data.heart_rate_recovery_one_minute.updated":
                return DAILY_DATA_HEART_RATE_RECOVERY_ONE_MINUTE_UPDATED;
            default:
                return new ClientFacingHeartRateRecoveryOneMinuteChangedEventType(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        DAILY_DATA_HEART_RATE_RECOVERY_ONE_MINUTE_CREATED,

        DAILY_DATA_HEART_RATE_RECOVERY_ONE_MINUTE_UPDATED,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitDailyDataHeartRateRecoveryOneMinuteCreated();

        T visitDailyDataHeartRateRecoveryOneMinuteUpdated();

        T visitUnknown(String unknownType);
    }
}
