/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.junction.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class ClientFacingInsulinInjectionSampleType {
    public static final ClientFacingInsulinInjectionSampleType LONG_ACTING =
            new ClientFacingInsulinInjectionSampleType(Value.LONG_ACTING, "long_acting");

    public static final ClientFacingInsulinInjectionSampleType RAPID_ACTING =
            new ClientFacingInsulinInjectionSampleType(Value.RAPID_ACTING, "rapid_acting");

    private final Value value;

    private final String string;

    ClientFacingInsulinInjectionSampleType(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof ClientFacingInsulinInjectionSampleType
                        && this.string.equals(((ClientFacingInsulinInjectionSampleType) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case LONG_ACTING:
                return visitor.visitLongActing();
            case RAPID_ACTING:
                return visitor.visitRapidActing();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static ClientFacingInsulinInjectionSampleType valueOf(String value) {
        switch (value) {
            case "long_acting":
                return LONG_ACTING;
            case "rapid_acting":
                return RAPID_ACTING;
            default:
                return new ClientFacingInsulinInjectionSampleType(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        RAPID_ACTING,

        LONG_ACTING,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitRapidActing();

        T visitLongActing();

        T visitUnknown(String unknownType);
    }
}
