/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.junction.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class ClientFacingOrderChangedEventType {
    public static final ClientFacingOrderChangedEventType LABTEST_ORDER_CREATED =
            new ClientFacingOrderChangedEventType(Value.LABTEST_ORDER_CREATED, "labtest.order.created");

    public static final ClientFacingOrderChangedEventType LABTEST_ORDER_UPDATED =
            new ClientFacingOrderChangedEventType(Value.LABTEST_ORDER_UPDATED, "labtest.order.updated");

    private final Value value;

    private final String string;

    ClientFacingOrderChangedEventType(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof ClientFacingOrderChangedEventType
                        && this.string.equals(((ClientFacingOrderChangedEventType) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case LABTEST_ORDER_CREATED:
                return visitor.visitLabtestOrderCreated();
            case LABTEST_ORDER_UPDATED:
                return visitor.visitLabtestOrderUpdated();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static ClientFacingOrderChangedEventType valueOf(String value) {
        switch (value) {
            case "labtest.order.created":
                return LABTEST_ORDER_CREATED;
            case "labtest.order.updated":
                return LABTEST_ORDER_UPDATED;
            default:
                return new ClientFacingOrderChangedEventType(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        LABTEST_ORDER_CREATED,

        LABTEST_ORDER_UPDATED,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitLabtestOrderCreated();

        T visitLabtestOrderUpdated();

        T visitUnknown(String unknownType);
    }
}
