/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.junction.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class ClientFacingHrvChangedEventType {
    public static final ClientFacingHrvChangedEventType DAILY_DATA_HRV_CREATED =
            new ClientFacingHrvChangedEventType(Value.DAILY_DATA_HRV_CREATED, "daily.data.hrv.created");

    public static final ClientFacingHrvChangedEventType DAILY_DATA_HRV_UPDATED =
            new ClientFacingHrvChangedEventType(Value.DAILY_DATA_HRV_UPDATED, "daily.data.hrv.updated");

    private final Value value;

    private final String string;

    ClientFacingHrvChangedEventType(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof ClientFacingHrvChangedEventType
                        && this.string.equals(((ClientFacingHrvChangedEventType) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case DAILY_DATA_HRV_CREATED:
                return visitor.visitDailyDataHrvCreated();
            case DAILY_DATA_HRV_UPDATED:
                return visitor.visitDailyDataHrvUpdated();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static ClientFacingHrvChangedEventType valueOf(String value) {
        switch (value) {
            case "daily.data.hrv.created":
                return DAILY_DATA_HRV_CREATED;
            case "daily.data.hrv.updated":
                return DAILY_DATA_HRV_UPDATED;
            default:
                return new ClientFacingHrvChangedEventType(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        DAILY_DATA_HRV_CREATED,

        DAILY_DATA_HRV_UPDATED,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitDailyDataHrvCreated();

        T visitDailyDataHrvUpdated();

        T visitUnknown(String unknownType);
    }
}
