/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.junction.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class ClientFacingWorkoutDurationChangedEventType {
    public static final ClientFacingWorkoutDurationChangedEventType DAILY_DATA_WORKOUT_DURATION_UPDATED =
            new ClientFacingWorkoutDurationChangedEventType(
                    Value.DAILY_DATA_WORKOUT_DURATION_UPDATED, "daily.data.workout_duration.updated");

    public static final ClientFacingWorkoutDurationChangedEventType DAILY_DATA_WORKOUT_DURATION_CREATED =
            new ClientFacingWorkoutDurationChangedEventType(
                    Value.DAILY_DATA_WORKOUT_DURATION_CREATED, "daily.data.workout_duration.created");

    private final Value value;

    private final String string;

    ClientFacingWorkoutDurationChangedEventType(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof ClientFacingWorkoutDurationChangedEventType
                        && this.string.equals(((ClientFacingWorkoutDurationChangedEventType) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case DAILY_DATA_WORKOUT_DURATION_UPDATED:
                return visitor.visitDailyDataWorkoutDurationUpdated();
            case DAILY_DATA_WORKOUT_DURATION_CREATED:
                return visitor.visitDailyDataWorkoutDurationCreated();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static ClientFacingWorkoutDurationChangedEventType valueOf(String value) {
        switch (value) {
            case "daily.data.workout_duration.updated":
                return DAILY_DATA_WORKOUT_DURATION_UPDATED;
            case "daily.data.workout_duration.created":
                return DAILY_DATA_WORKOUT_DURATION_CREATED;
            default:
                return new ClientFacingWorkoutDurationChangedEventType(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        DAILY_DATA_WORKOUT_DURATION_CREATED,

        DAILY_DATA_WORKOUT_DURATION_UPDATED,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitDailyDataWorkoutDurationCreated();

        T visitDailyDataWorkoutDurationUpdated();

        T visitUnknown(String unknownType);
    }
}
