/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.junction.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class ClientFacingInsulinInjectionSampleDeliveryForm {
    public static final ClientFacingInsulinInjectionSampleDeliveryForm EXTENDED =
            new ClientFacingInsulinInjectionSampleDeliveryForm(Value.EXTENDED, "extended");

    public static final ClientFacingInsulinInjectionSampleDeliveryForm STANDARD =
            new ClientFacingInsulinInjectionSampleDeliveryForm(Value.STANDARD, "standard");

    private final Value value;

    private final String string;

    ClientFacingInsulinInjectionSampleDeliveryForm(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof ClientFacingInsulinInjectionSampleDeliveryForm
                        && this.string.equals(((ClientFacingInsulinInjectionSampleDeliveryForm) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case EXTENDED:
                return visitor.visitExtended();
            case STANDARD:
                return visitor.visitStandard();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static ClientFacingInsulinInjectionSampleDeliveryForm valueOf(String value) {
        switch (value) {
            case "extended":
                return EXTENDED;
            case "standard":
                return STANDARD;
            default:
                return new ClientFacingInsulinInjectionSampleDeliveryForm(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        STANDARD,

        EXTENDED,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitStandard();

        T visitExtended();

        T visitUnknown(String unknownType);
    }
}
