/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.junction.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class ClientFacingCaffeineChangedEventType {
    public static final ClientFacingCaffeineChangedEventType DAILY_DATA_CAFFEINE_CREATED =
            new ClientFacingCaffeineChangedEventType(Value.DAILY_DATA_CAFFEINE_CREATED, "daily.data.caffeine.created");

    public static final ClientFacingCaffeineChangedEventType DAILY_DATA_CAFFEINE_UPDATED =
            new ClientFacingCaffeineChangedEventType(Value.DAILY_DATA_CAFFEINE_UPDATED, "daily.data.caffeine.updated");

    private final Value value;

    private final String string;

    ClientFacingCaffeineChangedEventType(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof ClientFacingCaffeineChangedEventType
                        && this.string.equals(((ClientFacingCaffeineChangedEventType) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case DAILY_DATA_CAFFEINE_CREATED:
                return visitor.visitDailyDataCaffeineCreated();
            case DAILY_DATA_CAFFEINE_UPDATED:
                return visitor.visitDailyDataCaffeineUpdated();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static ClientFacingCaffeineChangedEventType valueOf(String value) {
        switch (value) {
            case "daily.data.caffeine.created":
                return DAILY_DATA_CAFFEINE_CREATED;
            case "daily.data.caffeine.updated":
                return DAILY_DATA_CAFFEINE_UPDATED;
            default:
                return new ClientFacingCaffeineChangedEventType(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        DAILY_DATA_CAFFEINE_CREATED,

        DAILY_DATA_CAFFEINE_UPDATED,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitDailyDataCaffeineCreated();

        T visitDailyDataCaffeineUpdated();

        T visitUnknown(String unknownType);
    }
}
