/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.junction.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class ClientFacingWheelchairPushChangedEventType {
    public static final ClientFacingWheelchairPushChangedEventType DAILY_DATA_WHEELCHAIR_PUSH_CREATED =
            new ClientFacingWheelchairPushChangedEventType(
                    Value.DAILY_DATA_WHEELCHAIR_PUSH_CREATED, "daily.data.wheelchair_push.created");

    public static final ClientFacingWheelchairPushChangedEventType DAILY_DATA_WHEELCHAIR_PUSH_UPDATED =
            new ClientFacingWheelchairPushChangedEventType(
                    Value.DAILY_DATA_WHEELCHAIR_PUSH_UPDATED, "daily.data.wheelchair_push.updated");

    private final Value value;

    private final String string;

    ClientFacingWheelchairPushChangedEventType(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof ClientFacingWheelchairPushChangedEventType
                        && this.string.equals(((ClientFacingWheelchairPushChangedEventType) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case DAILY_DATA_WHEELCHAIR_PUSH_CREATED:
                return visitor.visitDailyDataWheelchairPushCreated();
            case DAILY_DATA_WHEELCHAIR_PUSH_UPDATED:
                return visitor.visitDailyDataWheelchairPushUpdated();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static ClientFacingWheelchairPushChangedEventType valueOf(String value) {
        switch (value) {
            case "daily.data.wheelchair_push.created":
                return DAILY_DATA_WHEELCHAIR_PUSH_CREATED;
            case "daily.data.wheelchair_push.updated":
                return DAILY_DATA_WHEELCHAIR_PUSH_UPDATED;
            default:
                return new ClientFacingWheelchairPushChangedEventType(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        DAILY_DATA_WHEELCHAIR_PUSH_CREATED,

        DAILY_DATA_WHEELCHAIR_PUSH_UPDATED,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitDailyDataWheelchairPushCreated();

        T visitDailyDataWheelchairPushUpdated();

        T visitUnknown(String unknownType);
    }
}
