/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.junction.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class ClientFacingForcedExpiratoryVolume1ChangedEventType {
    public static final ClientFacingForcedExpiratoryVolume1ChangedEventType
            DAILY_DATA_FORCED_EXPIRATORY_VOLUME_1_CREATED = new ClientFacingForcedExpiratoryVolume1ChangedEventType(
                    Value.DAILY_DATA_FORCED_EXPIRATORY_VOLUME_1_CREATED,
                    "daily.data.forced_expiratory_volume_1.created");

    public static final ClientFacingForcedExpiratoryVolume1ChangedEventType
            DAILY_DATA_FORCED_EXPIRATORY_VOLUME_1_UPDATED = new ClientFacingForcedExpiratoryVolume1ChangedEventType(
                    Value.DAILY_DATA_FORCED_EXPIRATORY_VOLUME_1_UPDATED,
                    "daily.data.forced_expiratory_volume_1.updated");

    private final Value value;

    private final String string;

    ClientFacingForcedExpiratoryVolume1ChangedEventType(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof ClientFacingForcedExpiratoryVolume1ChangedEventType
                        && this.string.equals(((ClientFacingForcedExpiratoryVolume1ChangedEventType) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case DAILY_DATA_FORCED_EXPIRATORY_VOLUME_1_CREATED:
                return visitor.visitDailyDataForcedExpiratoryVolume1Created();
            case DAILY_DATA_FORCED_EXPIRATORY_VOLUME_1_UPDATED:
                return visitor.visitDailyDataForcedExpiratoryVolume1Updated();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static ClientFacingForcedExpiratoryVolume1ChangedEventType valueOf(String value) {
        switch (value) {
            case "daily.data.forced_expiratory_volume_1.created":
                return DAILY_DATA_FORCED_EXPIRATORY_VOLUME_1_CREATED;
            case "daily.data.forced_expiratory_volume_1.updated":
                return DAILY_DATA_FORCED_EXPIRATORY_VOLUME_1_UPDATED;
            default:
                return new ClientFacingForcedExpiratoryVolume1ChangedEventType(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        DAILY_DATA_FORCED_EXPIRATORY_VOLUME_1_CREATED,

        DAILY_DATA_FORCED_EXPIRATORY_VOLUME_1_UPDATED,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitDailyDataForcedExpiratoryVolume1Created();

        T visitDailyDataForcedExpiratoryVolume1Updated();

        T visitUnknown(String unknownType);
    }
}
