/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.junction.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class ClientFacingInsulinInjectionChangedEventType {
    public static final ClientFacingInsulinInjectionChangedEventType DAILY_DATA_INSULIN_INJECTION_UPDATED =
            new ClientFacingInsulinInjectionChangedEventType(
                    Value.DAILY_DATA_INSULIN_INJECTION_UPDATED, "daily.data.insulin_injection.updated");

    public static final ClientFacingInsulinInjectionChangedEventType DAILY_DATA_INSULIN_INJECTION_CREATED =
            new ClientFacingInsulinInjectionChangedEventType(
                    Value.DAILY_DATA_INSULIN_INJECTION_CREATED, "daily.data.insulin_injection.created");

    private final Value value;

    private final String string;

    ClientFacingInsulinInjectionChangedEventType(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof ClientFacingInsulinInjectionChangedEventType
                        && this.string.equals(((ClientFacingInsulinInjectionChangedEventType) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case DAILY_DATA_INSULIN_INJECTION_UPDATED:
                return visitor.visitDailyDataInsulinInjectionUpdated();
            case DAILY_DATA_INSULIN_INJECTION_CREATED:
                return visitor.visitDailyDataInsulinInjectionCreated();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static ClientFacingInsulinInjectionChangedEventType valueOf(String value) {
        switch (value) {
            case "daily.data.insulin_injection.updated":
                return DAILY_DATA_INSULIN_INJECTION_UPDATED;
            case "daily.data.insulin_injection.created":
                return DAILY_DATA_INSULIN_INJECTION_CREATED;
            default:
                return new ClientFacingInsulinInjectionChangedEventType(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        DAILY_DATA_INSULIN_INJECTION_CREATED,

        DAILY_DATA_INSULIN_INJECTION_UPDATED,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitDailyDataInsulinInjectionCreated();

        T visitDailyDataInsulinInjectionUpdated();

        T visitUnknown(String unknownType);
    }
}
