/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.junction.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class ClientFacingWeightChangedEventType {
    public static final ClientFacingWeightChangedEventType DAILY_DATA_WEIGHT_UPDATED =
            new ClientFacingWeightChangedEventType(Value.DAILY_DATA_WEIGHT_UPDATED, "daily.data.weight.updated");

    public static final ClientFacingWeightChangedEventType DAILY_DATA_WEIGHT_CREATED =
            new ClientFacingWeightChangedEventType(Value.DAILY_DATA_WEIGHT_CREATED, "daily.data.weight.created");

    private final Value value;

    private final String string;

    ClientFacingWeightChangedEventType(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof ClientFacingWeightChangedEventType
                        && this.string.equals(((ClientFacingWeightChangedEventType) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case DAILY_DATA_WEIGHT_UPDATED:
                return visitor.visitDailyDataWeightUpdated();
            case DAILY_DATA_WEIGHT_CREATED:
                return visitor.visitDailyDataWeightCreated();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static ClientFacingWeightChangedEventType valueOf(String value) {
        switch (value) {
            case "daily.data.weight.updated":
                return DAILY_DATA_WEIGHT_UPDATED;
            case "daily.data.weight.created":
                return DAILY_DATA_WEIGHT_CREATED;
            default:
                return new ClientFacingWeightChangedEventType(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        DAILY_DATA_WEIGHT_CREATED,

        DAILY_DATA_WEIGHT_UPDATED,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitDailyDataWeightCreated();

        T visitDailyDataWeightUpdated();

        T visitUnknown(String unknownType);
    }
}
