/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.junction.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class ContinuousQueryTaskStatus {
    public static final ContinuousQueryTaskStatus SKIPPED = new ContinuousQueryTaskStatus(Value.SKIPPED, "skipped");

    public static final ContinuousQueryTaskStatus COMPLETED =
            new ContinuousQueryTaskStatus(Value.COMPLETED, "completed");

    public static final ContinuousQueryTaskStatus SCHEDULED =
            new ContinuousQueryTaskStatus(Value.SCHEDULED, "scheduled");

    public static final ContinuousQueryTaskStatus ERROR = new ContinuousQueryTaskStatus(Value.ERROR, "error");

    public static final ContinuousQueryTaskStatus STARTED = new ContinuousQueryTaskStatus(Value.STARTED, "started");

    private final Value value;

    private final String string;

    ContinuousQueryTaskStatus(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof ContinuousQueryTaskStatus
                        && this.string.equals(((ContinuousQueryTaskStatus) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case SKIPPED:
                return visitor.visitSkipped();
            case COMPLETED:
                return visitor.visitCompleted();
            case SCHEDULED:
                return visitor.visitScheduled();
            case ERROR:
                return visitor.visitError();
            case STARTED:
                return visitor.visitStarted();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static ContinuousQueryTaskStatus valueOf(String value) {
        switch (value) {
            case "skipped":
                return SKIPPED;
            case "completed":
                return COMPLETED;
            case "scheduled":
                return SCHEDULED;
            case "error":
                return ERROR;
            case "started":
                return STARTED;
            default:
                return new ContinuousQueryTaskStatus(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        SCHEDULED,

        STARTED,

        COMPLETED,

        ERROR,

        SKIPPED,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitScheduled();

        T visitStarted();

        T visitCompleted();

        T visitError();

        T visitSkipped();

        T visitUnknown(String unknownType);
    }
}
