/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.junction.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class Ethnicity {
    public static final Ethnicity NON_HISPANIC = new Ethnicity(Value.NON_HISPANIC, "non_hispanic");

    public static final Ethnicity OTHER = new Ethnicity(Value.OTHER, "other");

    public static final Ethnicity ASHKENAZI_JEWISH = new Ethnicity(Value.ASHKENAZI_JEWISH, "ashkenazi_jewish");

    public static final Ethnicity HISPANIC = new Ethnicity(Value.HISPANIC, "hispanic");

    private final Value value;

    private final String string;

    Ethnicity(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other) || (other instanceof Ethnicity && this.string.equals(((Ethnicity) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case NON_HISPANIC:
                return visitor.visitNonHispanic();
            case OTHER:
                return visitor.visitOther();
            case ASHKENAZI_JEWISH:
                return visitor.visitAshkenaziJewish();
            case HISPANIC:
                return visitor.visitHispanic();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static Ethnicity valueOf(String value) {
        switch (value) {
            case "non_hispanic":
                return NON_HISPANIC;
            case "other":
                return OTHER;
            case "ashkenazi_jewish":
                return ASHKENAZI_JEWISH;
            case "hispanic":
                return HISPANIC;
            default:
                return new Ethnicity(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        HISPANIC,

        NON_HISPANIC,

        ASHKENAZI_JEWISH,

        OTHER,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitHispanic();

        T visitNonHispanic();

        T visitAshkenaziJewish();

        T visitOther();

        T visitUnknown(String unknownType);
    }
}
