/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.junction.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.junction.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = GetLabTestPricingResponse.Builder.class)
public final class GetLabTestPricingResponse {
    private final Optional<String> currency;

    private final Map<String, LabTestPanelPricing> data;

    private final Map<String, Object> additionalProperties;

    private GetLabTestPricingResponse(
            Optional<String> currency,
            Map<String, LabTestPanelPricing> data,
            Map<String, Object> additionalProperties) {
        this.currency = currency;
        this.data = data;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("currency")
    public Optional<String> getCurrency() {
        return currency;
    }

    @JsonProperty("data")
    public Map<String, LabTestPanelPricing> getData() {
        return data;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof GetLabTestPricingResponse && equalTo((GetLabTestPricingResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(GetLabTestPricingResponse other) {
        return currency.equals(other.currency) && data.equals(other.data);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.currency, this.data);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> currency = Optional.empty();

        private Map<String, LabTestPanelPricing> data = new LinkedHashMap<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(GetLabTestPricingResponse other) {
            currency(other.getCurrency());
            data(other.getData());
            return this;
        }

        @JsonSetter(value = "currency", nulls = Nulls.SKIP)
        public Builder currency(Optional<String> currency) {
            this.currency = currency;
            return this;
        }

        public Builder currency(String currency) {
            this.currency = Optional.ofNullable(currency);
            return this;
        }

        @JsonSetter(value = "data", nulls = Nulls.SKIP)
        public Builder data(Map<String, LabTestPanelPricing> data) {
            this.data.clear();
            if (data != null) {
                this.data.putAll(data);
            }
            return this;
        }

        public Builder putAllData(Map<String, LabTestPanelPricing> data) {
            if (data != null) {
                this.data.putAll(data);
            }
            return this;
        }

        public Builder data(String key, LabTestPanelPricing value) {
            this.data.put(key, value);
            return this;
        }

        public GetLabTestPricingResponse build() {
            return new GetLabTestPricingResponse(currency, data, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
