/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.junction.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class HistoricalPullRetriableErrorDetails {
    public static final HistoricalPullRetriableErrorDetails PROVIDER_UNAVAILABLE =
            new HistoricalPullRetriableErrorDetails(Value.PROVIDER_UNAVAILABLE, "provider_unavailable");

    public static final HistoricalPullRetriableErrorDetails PROVIDER_RATE_LIMIT_EXCEEDED =
            new HistoricalPullRetriableErrorDetails(Value.PROVIDER_RATE_LIMIT_EXCEEDED, "provider_rate_limit_exceeded");

    public static final HistoricalPullRetriableErrorDetails RESOURCE_CONTENTION =
            new HistoricalPullRetriableErrorDetails(Value.RESOURCE_CONTENTION, "resource_contention");

    public static final HistoricalPullRetriableErrorDetails TRANSPORT_FAILURE =
            new HistoricalPullRetriableErrorDetails(Value.TRANSPORT_FAILURE, "transport_failure");

    private final Value value;

    private final String string;

    HistoricalPullRetriableErrorDetails(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof HistoricalPullRetriableErrorDetails
                        && this.string.equals(((HistoricalPullRetriableErrorDetails) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case PROVIDER_UNAVAILABLE:
                return visitor.visitProviderUnavailable();
            case PROVIDER_RATE_LIMIT_EXCEEDED:
                return visitor.visitProviderRateLimitExceeded();
            case RESOURCE_CONTENTION:
                return visitor.visitResourceContention();
            case TRANSPORT_FAILURE:
                return visitor.visitTransportFailure();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static HistoricalPullRetriableErrorDetails valueOf(String value) {
        switch (value) {
            case "provider_unavailable":
                return PROVIDER_UNAVAILABLE;
            case "provider_rate_limit_exceeded":
                return PROVIDER_RATE_LIMIT_EXCEEDED;
            case "resource_contention":
                return RESOURCE_CONTENTION;
            case "transport_failure":
                return TRANSPORT_FAILURE;
            default:
                return new HistoricalPullRetriableErrorDetails(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        PROVIDER_RATE_LIMIT_EXCEEDED,

        PROVIDER_UNAVAILABLE,

        TRANSPORT_FAILURE,

        RESOURCE_CONTENTION,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitProviderRateLimitExceeded();

        T visitProviderUnavailable();

        T visitTransportFailure();

        T visitResourceContention();

        T visitUnknown(String unknownType);
    }
}
