/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.junction.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class HomeProgesteroneTestEntryTestResult {
    public static final HomeProgesteroneTestEntryTestResult POSITIVE =
            new HomeProgesteroneTestEntryTestResult(Value.POSITIVE, "positive");

    public static final HomeProgesteroneTestEntryTestResult NEGATIVE =
            new HomeProgesteroneTestEntryTestResult(Value.NEGATIVE, "negative");

    public static final HomeProgesteroneTestEntryTestResult INDETERMINATE =
            new HomeProgesteroneTestEntryTestResult(Value.INDETERMINATE, "indeterminate");

    private final Value value;

    private final String string;

    HomeProgesteroneTestEntryTestResult(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof HomeProgesteroneTestEntryTestResult
                        && this.string.equals(((HomeProgesteroneTestEntryTestResult) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case POSITIVE:
                return visitor.visitPositive();
            case NEGATIVE:
                return visitor.visitNegative();
            case INDETERMINATE:
                return visitor.visitIndeterminate();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static HomeProgesteroneTestEntryTestResult valueOf(String value) {
        switch (value) {
            case "positive":
                return POSITIVE;
            case "negative":
                return NEGATIVE;
            case "indeterminate":
                return INDETERMINATE;
            default:
                return new HomeProgesteroneTestEntryTestResult(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        NEGATIVE,

        POSITIVE,

        INDETERMINATE,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitNegative();

        T visitPositive();

        T visitIndeterminate();

        T visitUnknown(String unknownType);
    }
}
