/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.junction.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class LabLocationCapability {
    public static final LabLocationCapability APPOINTMENT_SCHEDULING_WITH_LAB =
            new LabLocationCapability(Value.APPOINTMENT_SCHEDULING_WITH_LAB, "appointment_scheduling_with_lab");

    public static final LabLocationCapability APPOINTMENT_SCHEDULING_VIA_JUNCTION =
            new LabLocationCapability(Value.APPOINTMENT_SCHEDULING_VIA_JUNCTION, "appointment_scheduling_via_junction");

    public static final LabLocationCapability STAT = new LabLocationCapability(Value.STAT, "stat");

    private final Value value;

    private final String string;

    LabLocationCapability(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof LabLocationCapability
                        && this.string.equals(((LabLocationCapability) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case APPOINTMENT_SCHEDULING_WITH_LAB:
                return visitor.visitAppointmentSchedulingWithLab();
            case APPOINTMENT_SCHEDULING_VIA_JUNCTION:
                return visitor.visitAppointmentSchedulingViaJunction();
            case STAT:
                return visitor.visitStat();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static LabLocationCapability valueOf(String value) {
        switch (value) {
            case "appointment_scheduling_with_lab":
                return APPOINTMENT_SCHEDULING_WITH_LAB;
            case "appointment_scheduling_via_junction":
                return APPOINTMENT_SCHEDULING_VIA_JUNCTION;
            case "stat":
                return STAT;
            default:
                return new LabLocationCapability(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        STAT,

        APPOINTMENT_SCHEDULING_VIA_JUNCTION,

        APPOINTMENT_SCHEDULING_WITH_LAB,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitStat();

        T visitAppointmentSchedulingViaJunction();

        T visitAppointmentSchedulingWithLab();

        T visitUnknown(String unknownType);
    }
}
