/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.junction.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class LabReportResultLoincMatchStatus {
    public static final LabReportResultLoincMatchStatus NEEDS_REVIEW =
            new LabReportResultLoincMatchStatus(Value.NEEDS_REVIEW, "needs_review");

    public static final LabReportResultLoincMatchStatus AUTO_MATCH =
            new LabReportResultLoincMatchStatus(Value.AUTO_MATCH, "auto_match");

    public static final LabReportResultLoincMatchStatus NO_MATCH =
            new LabReportResultLoincMatchStatus(Value.NO_MATCH, "no_match");

    private final Value value;

    private final String string;

    LabReportResultLoincMatchStatus(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof LabReportResultLoincMatchStatus
                        && this.string.equals(((LabReportResultLoincMatchStatus) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case NEEDS_REVIEW:
                return visitor.visitNeedsReview();
            case AUTO_MATCH:
                return visitor.visitAutoMatch();
            case NO_MATCH:
                return visitor.visitNoMatch();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static LabReportResultLoincMatchStatus valueOf(String value) {
        switch (value) {
            case "needs_review":
                return NEEDS_REVIEW;
            case "auto_match":
                return AUTO_MATCH;
            case "no_match":
                return NO_MATCH;
            default:
                return new LabReportResultLoincMatchStatus(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        AUTO_MATCH,

        NEEDS_REVIEW,

        NO_MATCH,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitAutoMatch();

        T visitNeedsReview();

        T visitNoMatch();

        T visitUnknown(String unknownType);
    }
}
