/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.junction.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class LabReportResultSampleType {
    public static final LabReportResultSampleType STOOL = new LabReportResultSampleType(Value.STOOL, "stool");

    public static final LabReportResultSampleType OTHER = new LabReportResultSampleType(Value.OTHER, "other");

    public static final LabReportResultSampleType URINE = new LabReportResultSampleType(Value.URINE, "urine");

    public static final LabReportResultSampleType SERUM_PLASMA_BLOOD =
            new LabReportResultSampleType(Value.SERUM_PLASMA_BLOOD, "serum_plasma_blood");

    public static final LabReportResultSampleType CAPILLARY_BLOOD =
            new LabReportResultSampleType(Value.CAPILLARY_BLOOD, "capillary_blood");

    public static final LabReportResultSampleType UNKNOWN = new LabReportResultSampleType(Value.UNKNOWN, "unknown");

    public static final LabReportResultSampleType SALIVA = new LabReportResultSampleType(Value.SALIVA, "saliva");

    private final Value value;

    private final String string;

    LabReportResultSampleType(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof LabReportResultSampleType
                        && this.string.equals(((LabReportResultSampleType) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case STOOL:
                return visitor.visitStool();
            case OTHER:
                return visitor.visitOther();
            case URINE:
                return visitor.visitUrine();
            case SERUM_PLASMA_BLOOD:
                return visitor.visitSerumPlasmaBlood();
            case CAPILLARY_BLOOD:
                return visitor.visitCapillaryBlood();
            case UNKNOWN:
                return visitor.visitUnknown();
            case SALIVA:
                return visitor.visitSaliva();
            case _UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static LabReportResultSampleType valueOf(String value) {
        switch (value) {
            case "stool":
                return STOOL;
            case "other":
                return OTHER;
            case "urine":
                return URINE;
            case "serum_plasma_blood":
                return SERUM_PLASMA_BLOOD;
            case "capillary_blood":
                return CAPILLARY_BLOOD;
            case "unknown":
                return UNKNOWN;
            case "saliva":
                return SALIVA;
            default:
                return new LabReportResultSampleType(Value._UNKNOWN, value);
        }
    }

    public enum Value {
        URINE,

        SERUM_PLASMA_BLOOD,

        CAPILLARY_BLOOD,

        STOOL,

        SALIVA,

        OTHER,

        UNKNOWN,

        _UNKNOWN
    }

    public interface Visitor<T> {
        T visitUrine();

        T visitSerumPlasmaBlood();

        T visitCapillaryBlood();

        T visitStool();

        T visitSaliva();

        T visitOther();

        T visitUnknown();

        T visitUnknown(String unknownType);
    }
}
