/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.junction.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.junction.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = LabTestPromotion.Builder.class)
public final class LabTestPromotion {
    private final String sourceSandboxLabTestId;

    private final String productionLabTestId;

    private final LabTestStatus status;

    private final Map<String, Object> additionalProperties;

    private LabTestPromotion(
            String sourceSandboxLabTestId,
            String productionLabTestId,
            LabTestStatus status,
            Map<String, Object> additionalProperties) {
        this.sourceSandboxLabTestId = sourceSandboxLabTestId;
        this.productionLabTestId = productionLabTestId;
        this.status = status;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("source_sandbox_lab_test_id")
    public String getSourceSandboxLabTestId() {
        return sourceSandboxLabTestId;
    }

    @JsonProperty("production_lab_test_id")
    public String getProductionLabTestId() {
        return productionLabTestId;
    }

    /**
     * @return ℹ️ This enum is non-exhaustive.
     */
    @JsonProperty("status")
    public LabTestStatus getStatus() {
        return status;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof LabTestPromotion && equalTo((LabTestPromotion) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(LabTestPromotion other) {
        return sourceSandboxLabTestId.equals(other.sourceSandboxLabTestId)
                && productionLabTestId.equals(other.productionLabTestId)
                && status.equals(other.status);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.sourceSandboxLabTestId, this.productionLabTestId, this.status);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static SourceSandboxLabTestIdStage builder() {
        return new Builder();
    }

    public interface SourceSandboxLabTestIdStage {
        ProductionLabTestIdStage sourceSandboxLabTestId(@NotNull String sourceSandboxLabTestId);

        Builder from(LabTestPromotion other);
    }

    public interface ProductionLabTestIdStage {
        StatusStage productionLabTestId(@NotNull String productionLabTestId);
    }

    public interface StatusStage {
        /**
         * <p>ℹ️ This enum is non-exhaustive.</p>
         */
        _FinalStage status(@NotNull LabTestStatus status);
    }

    public interface _FinalStage {
        LabTestPromotion build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements SourceSandboxLabTestIdStage, ProductionLabTestIdStage, StatusStage, _FinalStage {
        private String sourceSandboxLabTestId;

        private String productionLabTestId;

        private LabTestStatus status;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(LabTestPromotion other) {
            sourceSandboxLabTestId(other.getSourceSandboxLabTestId());
            productionLabTestId(other.getProductionLabTestId());
            status(other.getStatus());
            return this;
        }

        @java.lang.Override
        @JsonSetter("source_sandbox_lab_test_id")
        public ProductionLabTestIdStage sourceSandboxLabTestId(@NotNull String sourceSandboxLabTestId) {
            this.sourceSandboxLabTestId =
                    Objects.requireNonNull(sourceSandboxLabTestId, "sourceSandboxLabTestId must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("production_lab_test_id")
        public StatusStage productionLabTestId(@NotNull String productionLabTestId) {
            this.productionLabTestId =
                    Objects.requireNonNull(productionLabTestId, "productionLabTestId must not be null");
            return this;
        }

        /**
         * <p>ℹ️ This enum is non-exhaustive.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("status")
        public _FinalStage status(@NotNull LabTestStatus status) {
            this.status = Objects.requireNonNull(status, "status must not be null");
            return this;
        }

        @java.lang.Override
        public LabTestPromotion build() {
            return new LabTestPromotion(sourceSandboxLabTestId, productionLabTestId, status, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
