/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.junction.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.junction.api.core.ObjectMappers;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = LabTestPromotionSource.Builder.class)
public final class LabTestPromotionSource {
    private final String name;

    private final String description;

    private final LabTestCollectionMethod method;

    private final boolean fasting;

    private final Labs labSlug;

    private final List<String> providerIds;

    private final String sourceSandboxLabTestId;

    private final Map<String, Object> additionalProperties;

    private LabTestPromotionSource(
            String name,
            String description,
            LabTestCollectionMethod method,
            boolean fasting,
            Labs labSlug,
            List<String> providerIds,
            String sourceSandboxLabTestId,
            Map<String, Object> additionalProperties) {
        this.name = name;
        this.description = description;
        this.method = method;
        this.fasting = fasting;
        this.labSlug = labSlug;
        this.providerIds = providerIds;
        this.sourceSandboxLabTestId = sourceSandboxLabTestId;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("name")
    public String getName() {
        return name;
    }

    @JsonProperty("description")
    public String getDescription() {
        return description;
    }

    /**
     * @return ℹ️ This enum is non-exhaustive.
     */
    @JsonProperty("method")
    public LabTestCollectionMethod getMethod() {
        return method;
    }

    @JsonProperty("fasting")
    public boolean getFasting() {
        return fasting;
    }

    /**
     * @return ℹ️ This enum is non-exhaustive.
     */
    @JsonProperty("lab_slug")
    public Labs getLabSlug() {
        return labSlug;
    }

    @JsonProperty("provider_ids")
    public List<String> getProviderIds() {
        return providerIds;
    }

    @JsonProperty("source_sandbox_lab_test_id")
    public String getSourceSandboxLabTestId() {
        return sourceSandboxLabTestId;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof LabTestPromotionSource && equalTo((LabTestPromotionSource) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(LabTestPromotionSource other) {
        return name.equals(other.name)
                && description.equals(other.description)
                && method.equals(other.method)
                && fasting == other.fasting
                && labSlug.equals(other.labSlug)
                && providerIds.equals(other.providerIds)
                && sourceSandboxLabTestId.equals(other.sourceSandboxLabTestId);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.name,
                this.description,
                this.method,
                this.fasting,
                this.labSlug,
                this.providerIds,
                this.sourceSandboxLabTestId);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static NameStage builder() {
        return new Builder();
    }

    public interface NameStage {
        DescriptionStage name(@NotNull String name);

        Builder from(LabTestPromotionSource other);
    }

    public interface DescriptionStage {
        MethodStage description(@NotNull String description);
    }

    public interface MethodStage {
        /**
         * <p>ℹ️ This enum is non-exhaustive.</p>
         */
        FastingStage method(@NotNull LabTestCollectionMethod method);
    }

    public interface FastingStage {
        LabSlugStage fasting(boolean fasting);
    }

    public interface LabSlugStage {
        /**
         * <p>ℹ️ This enum is non-exhaustive.</p>
         */
        SourceSandboxLabTestIdStage labSlug(@NotNull Labs labSlug);
    }

    public interface SourceSandboxLabTestIdStage {
        _FinalStage sourceSandboxLabTestId(@NotNull String sourceSandboxLabTestId);
    }

    public interface _FinalStage {
        LabTestPromotionSource build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        _FinalStage providerIds(List<String> providerIds);

        _FinalStage addProviderIds(String providerIds);

        _FinalStage addAllProviderIds(List<String> providerIds);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements NameStage,
                    DescriptionStage,
                    MethodStage,
                    FastingStage,
                    LabSlugStage,
                    SourceSandboxLabTestIdStage,
                    _FinalStage {
        private String name;

        private String description;

        private LabTestCollectionMethod method;

        private boolean fasting;

        private Labs labSlug;

        private String sourceSandboxLabTestId;

        private List<String> providerIds = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(LabTestPromotionSource other) {
            name(other.getName());
            description(other.getDescription());
            method(other.getMethod());
            fasting(other.getFasting());
            labSlug(other.getLabSlug());
            providerIds(other.getProviderIds());
            sourceSandboxLabTestId(other.getSourceSandboxLabTestId());
            return this;
        }

        @java.lang.Override
        @JsonSetter("name")
        public DescriptionStage name(@NotNull String name) {
            this.name = Objects.requireNonNull(name, "name must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("description")
        public MethodStage description(@NotNull String description) {
            this.description = Objects.requireNonNull(description, "description must not be null");
            return this;
        }

        /**
         * <p>ℹ️ This enum is non-exhaustive.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("method")
        public FastingStage method(@NotNull LabTestCollectionMethod method) {
            this.method = Objects.requireNonNull(method, "method must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("fasting")
        public LabSlugStage fasting(boolean fasting) {
            this.fasting = fasting;
            return this;
        }

        /**
         * <p>ℹ️ This enum is non-exhaustive.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("lab_slug")
        public SourceSandboxLabTestIdStage labSlug(@NotNull Labs labSlug) {
            this.labSlug = Objects.requireNonNull(labSlug, "labSlug must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("source_sandbox_lab_test_id")
        public _FinalStage sourceSandboxLabTestId(@NotNull String sourceSandboxLabTestId) {
            this.sourceSandboxLabTestId =
                    Objects.requireNonNull(sourceSandboxLabTestId, "sourceSandboxLabTestId must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage addAllProviderIds(List<String> providerIds) {
            if (providerIds != null) {
                this.providerIds.addAll(providerIds);
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage addProviderIds(String providerIds) {
            this.providerIds.add(providerIds);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "provider_ids", nulls = Nulls.SKIP)
        public _FinalStage providerIds(List<String> providerIds) {
            this.providerIds.clear();
            if (providerIds != null) {
                this.providerIds.addAll(providerIds);
            }
            return this;
        }

        @java.lang.Override
        public LabTestPromotionSource build() {
            return new LabTestPromotionSource(
                    name,
                    description,
                    method,
                    fasting,
                    labSlug,
                    providerIds,
                    sourceSandboxLabTestId,
                    additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
