/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.junction.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.junction.api.core.Nullable;
import com.junction.api.core.NullableNonemptyFilter;
import com.junction.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = LabTestPanelPricing.Builder.class)
public final class LabTestPanelPricing {
    private final LabTestPanelPricingPricing pricing;

    private final Optional<Map<String, Optional<LabTestPanelPricingMarkerBreakdownValue>>> markerBreakdown;

    private final Map<String, Object> additionalProperties;

    private LabTestPanelPricing(
            LabTestPanelPricingPricing pricing,
            Optional<Map<String, Optional<LabTestPanelPricingMarkerBreakdownValue>>> markerBreakdown,
            Map<String, Object> additionalProperties) {
        this.pricing = pricing;
        this.markerBreakdown = markerBreakdown;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("pricing")
    public LabTestPanelPricingPricing getPricing() {
        return pricing;
    }

    @JsonIgnore
    public Optional<Map<String, Optional<LabTestPanelPricingMarkerBreakdownValue>>> getMarkerBreakdown() {
        if (markerBreakdown == null) {
            return Optional.empty();
        }
        return markerBreakdown;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("marker_breakdown")
    private Optional<Map<String, Optional<LabTestPanelPricingMarkerBreakdownValue>>> _getMarkerBreakdown() {
        return markerBreakdown;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof LabTestPanelPricing && equalTo((LabTestPanelPricing) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(LabTestPanelPricing other) {
        return pricing.equals(other.pricing) && markerBreakdown.equals(other.markerBreakdown);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.pricing, this.markerBreakdown);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static PricingStage builder() {
        return new Builder();
    }

    public interface PricingStage {
        _FinalStage pricing(@NotNull LabTestPanelPricingPricing pricing);

        Builder from(LabTestPanelPricing other);
    }

    public interface _FinalStage {
        LabTestPanelPricing build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        _FinalStage markerBreakdown(
                Optional<Map<String, Optional<LabTestPanelPricingMarkerBreakdownValue>>> markerBreakdown);

        _FinalStage markerBreakdown(Map<String, Optional<LabTestPanelPricingMarkerBreakdownValue>> markerBreakdown);

        _FinalStage markerBreakdown(
                Nullable<Map<String, Optional<LabTestPanelPricingMarkerBreakdownValue>>> markerBreakdown);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements PricingStage, _FinalStage {
        private LabTestPanelPricingPricing pricing;

        private Optional<Map<String, Optional<LabTestPanelPricingMarkerBreakdownValue>>> markerBreakdown =
                Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(LabTestPanelPricing other) {
            pricing(other.getPricing());
            markerBreakdown(other.getMarkerBreakdown());
            return this;
        }

        @java.lang.Override
        @JsonSetter("pricing")
        public _FinalStage pricing(@NotNull LabTestPanelPricingPricing pricing) {
            this.pricing = Objects.requireNonNull(pricing, "pricing must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage markerBreakdown(
                Nullable<Map<String, Optional<LabTestPanelPricingMarkerBreakdownValue>>> markerBreakdown) {
            if (markerBreakdown.isNull()) {
                this.markerBreakdown = null;
            } else if (markerBreakdown.isEmpty()) {
                this.markerBreakdown = Optional.empty();
            } else {
                this.markerBreakdown = Optional.of(markerBreakdown.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage markerBreakdown(
                Map<String, Optional<LabTestPanelPricingMarkerBreakdownValue>> markerBreakdown) {
            this.markerBreakdown = Optional.ofNullable(markerBreakdown);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "marker_breakdown", nulls = Nulls.SKIP)
        public _FinalStage markerBreakdown(
                Optional<Map<String, Optional<LabTestPanelPricingMarkerBreakdownValue>>> markerBreakdown) {
            this.markerBreakdown = markerBreakdown;
            return this;
        }

        @java.lang.Override
        public LabTestPanelPricing build() {
            return new LabTestPanelPricing(pricing, markerBreakdown, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
