/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.junction.api.types;

import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.JsonParseException;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.junction.api.core.ObjectMappers;
import java.io.IOException;
import java.util.Map;
import java.util.Objects;

@JsonDeserialize(using = MarkerPricingResponseDataValue.Deserializer.class)
public final class MarkerPricingResponseDataValue {
    private final Object value;

    private final int type;

    private MarkerPricingResponseDataValue(Object value, int type) {
        this.value = value;
        this.type = type;
    }

    @JsonValue
    public Object get() {
        return this.value;
    }

    @SuppressWarnings("unchecked")
    public <T> T visit(Visitor<T> visitor) {
        if (this.type == 0) {
            return visitor.visit((SpecifiedPricingMarkerPricingConditions) this.value);
        } else if (this.type == 1) {
            return visitor.visit((UnspecifiedPricing) this.value);
        }
        throw new IllegalStateException("Failed to visit value. This should never happen.");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof MarkerPricingResponseDataValue && equalTo((MarkerPricingResponseDataValue) other);
    }

    private boolean equalTo(MarkerPricingResponseDataValue other) {
        return value.equals(other.value);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.value);
    }

    @java.lang.Override
    public String toString() {
        return this.value.toString();
    }

    public static MarkerPricingResponseDataValue of(SpecifiedPricingMarkerPricingConditions value) {
        return new MarkerPricingResponseDataValue(value, 0);
    }

    public static MarkerPricingResponseDataValue of(UnspecifiedPricing value) {
        return new MarkerPricingResponseDataValue(value, 1);
    }

    public interface Visitor<T> {
        T visit(SpecifiedPricingMarkerPricingConditions value);

        T visit(UnspecifiedPricing value);
    }

    static final class Deserializer extends StdDeserializer<MarkerPricingResponseDataValue> {
        Deserializer() {
            super(MarkerPricingResponseDataValue.class);
        }

        @java.lang.Override
        public MarkerPricingResponseDataValue deserialize(JsonParser p, DeserializationContext context)
                throws IOException {
            Object value = p.readValueAs(Object.class);
            if (value instanceof Map<?, ?> && ((Map<?, ?>) value).containsKey("base_amount_minor")) {
                try {
                    return of(ObjectMappers.JSON_MAPPER.convertValue(
                            value, SpecifiedPricingMarkerPricingConditions.class));
                } catch (RuntimeException e) {
                }
            }
            if (value instanceof Map<?, ?> && ((Map<?, ?>) value).containsKey("unspecified")) {
                try {
                    return of(ObjectMappers.JSON_MAPPER.convertValue(value, UnspecifiedPricing.class));
                } catch (RuntimeException e) {
                }
            }
            throw new JsonParseException(p, "Failed to deserialize");
        }
    }
}
