/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.junction.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class MatchCandidateType {
    public static final MatchCandidateType ORDER_OPTION = new MatchCandidateType(Value.ORDER_OPTION, "order_option");

    public static final MatchCandidateType PROVENANCE_ORDER =
            new MatchCandidateType(Value.PROVENANCE_ORDER, "provenance_order");

    private final Value value;

    private final String string;

    MatchCandidateType(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof MatchCandidateType && this.string.equals(((MatchCandidateType) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case ORDER_OPTION:
                return visitor.visitOrderOption();
            case PROVENANCE_ORDER:
                return visitor.visitProvenanceOrder();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static MatchCandidateType valueOf(String value) {
        switch (value) {
            case "order_option":
                return ORDER_OPTION;
            case "provenance_order":
                return PROVENANCE_ORDER;
            default:
                return new MatchCandidateType(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        PROVENANCE_ORDER,

        ORDER_OPTION,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitProvenanceOrder();

        T visitOrderOption();

        T visitUnknown(String unknownType);
    }
}
