/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.junction.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.junction.api.core.Nullable;
import com.junction.api.core.NullableNonemptyFilter;
import com.junction.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = MatchReviewCandidateGroup.Builder.class)
public final class MatchReviewCandidateGroup {
    private final Optional<String> userId;

    private final Optional<List<MatchReviewCandidate>> candidates;

    private final Map<String, Object> additionalProperties;

    private MatchReviewCandidateGroup(
            Optional<String> userId,
            Optional<List<MatchReviewCandidate>> candidates,
            Map<String, Object> additionalProperties) {
        this.userId = userId;
        this.candidates = candidates;
        this.additionalProperties = additionalProperties;
    }

    @JsonIgnore
    public Optional<String> getUserId() {
        if (userId == null) {
            return Optional.empty();
        }
        return userId;
    }

    @JsonProperty("candidates")
    public Optional<List<MatchReviewCandidate>> getCandidates() {
        return candidates;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("user_id")
    private Optional<String> _getUserId() {
        return userId;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof MatchReviewCandidateGroup && equalTo((MatchReviewCandidateGroup) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(MatchReviewCandidateGroup other) {
        return userId.equals(other.userId) && candidates.equals(other.candidates);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.userId, this.candidates);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> userId = Optional.empty();

        private Optional<List<MatchReviewCandidate>> candidates = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(MatchReviewCandidateGroup other) {
            userId(other.getUserId());
            candidates(other.getCandidates());
            return this;
        }

        @JsonSetter(value = "user_id", nulls = Nulls.SKIP)
        public Builder userId(Optional<String> userId) {
            this.userId = userId;
            return this;
        }

        public Builder userId(String userId) {
            this.userId = Optional.ofNullable(userId);
            return this;
        }

        public Builder userId(Nullable<String> userId) {
            if (userId.isNull()) {
                this.userId = null;
            } else if (userId.isEmpty()) {
                this.userId = Optional.empty();
            } else {
                this.userId = Optional.of(userId.get());
            }
            return this;
        }

        @JsonSetter(value = "candidates", nulls = Nulls.SKIP)
        public Builder candidates(Optional<List<MatchReviewCandidate>> candidates) {
            this.candidates = candidates;
            return this;
        }

        public Builder candidates(List<MatchReviewCandidate> candidates) {
            this.candidates = Optional.ofNullable(candidates);
            return this;
        }

        public MatchReviewCandidateGroup build() {
            return new MatchReviewCandidateGroup(userId, candidates, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
