/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.junction.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class MatchCandidateReasonCode {
    public static final MatchCandidateReasonCode SAME_USER = new MatchCandidateReasonCode(Value.SAME_USER, "same_user");

    public static final MatchCandidateReasonCode MARKER_OVERLAP_PARTIAL =
            new MatchCandidateReasonCode(Value.MARKER_OVERLAP_PARTIAL, "marker_overlap_partial");

    public static final MatchCandidateReasonCode SAME_LAB = new MatchCandidateReasonCode(Value.SAME_LAB, "same_lab");

    public static final MatchCandidateReasonCode MARKER_OVERLAP_EXACT =
            new MatchCandidateReasonCode(Value.MARKER_OVERLAP_EXACT, "marker_overlap_exact");

    public static final MatchCandidateReasonCode INVALID_COLLECTION_STATE =
            new MatchCandidateReasonCode(Value.INVALID_COLLECTION_STATE, "invalid_collection_state");

    public static final MatchCandidateReasonCode MARKER_OVERLAP_NONE =
            new MatchCandidateReasonCode(Value.MARKER_OVERLAP_NONE, "marker_overlap_none");

    public static final MatchCandidateReasonCode DEMOGRAPHIC_MISMATCH =
            new MatchCandidateReasonCode(Value.DEMOGRAPHIC_MISMATCH, "demographic_mismatch");

    public static final MatchCandidateReasonCode MATCHED_CANCELLED_ORDER =
            new MatchCandidateReasonCode(Value.MATCHED_CANCELLED_ORDER, "matched_cancelled_order");

    public static final MatchCandidateReasonCode POSSIBLE_WRONG_LAB =
            new MatchCandidateReasonCode(Value.POSSIBLE_WRONG_LAB, "possible_wrong_lab");

    public static final MatchCandidateReasonCode DEMOGRAPHIC_MATCH =
            new MatchCandidateReasonCode(Value.DEMOGRAPHIC_MATCH, "demographic_match");

    public static final MatchCandidateReasonCode SAMPLE_ID_MATCH =
            new MatchCandidateReasonCode(Value.SAMPLE_ID_MATCH, "sample_id_match");

    public static final MatchCandidateReasonCode LAB_ACCOUNT_MISMATCH =
            new MatchCandidateReasonCode(Value.LAB_ACCOUNT_MISMATCH, "lab_account_mismatch");

    public static final MatchCandidateReasonCode MATCHED_COMPLETED_ORDER =
            new MatchCandidateReasonCode(Value.MATCHED_COMPLETED_ORDER, "matched_completed_order");

    private final Value value;

    private final String string;

    MatchCandidateReasonCode(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof MatchCandidateReasonCode
                        && this.string.equals(((MatchCandidateReasonCode) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case SAME_USER:
                return visitor.visitSameUser();
            case MARKER_OVERLAP_PARTIAL:
                return visitor.visitMarkerOverlapPartial();
            case SAME_LAB:
                return visitor.visitSameLab();
            case MARKER_OVERLAP_EXACT:
                return visitor.visitMarkerOverlapExact();
            case INVALID_COLLECTION_STATE:
                return visitor.visitInvalidCollectionState();
            case MARKER_OVERLAP_NONE:
                return visitor.visitMarkerOverlapNone();
            case DEMOGRAPHIC_MISMATCH:
                return visitor.visitDemographicMismatch();
            case MATCHED_CANCELLED_ORDER:
                return visitor.visitMatchedCancelledOrder();
            case POSSIBLE_WRONG_LAB:
                return visitor.visitPossibleWrongLab();
            case DEMOGRAPHIC_MATCH:
                return visitor.visitDemographicMatch();
            case SAMPLE_ID_MATCH:
                return visitor.visitSampleIdMatch();
            case LAB_ACCOUNT_MISMATCH:
                return visitor.visitLabAccountMismatch();
            case MATCHED_COMPLETED_ORDER:
                return visitor.visitMatchedCompletedOrder();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static MatchCandidateReasonCode valueOf(String value) {
        switch (value) {
            case "same_user":
                return SAME_USER;
            case "marker_overlap_partial":
                return MARKER_OVERLAP_PARTIAL;
            case "same_lab":
                return SAME_LAB;
            case "marker_overlap_exact":
                return MARKER_OVERLAP_EXACT;
            case "invalid_collection_state":
                return INVALID_COLLECTION_STATE;
            case "marker_overlap_none":
                return MARKER_OVERLAP_NONE;
            case "demographic_mismatch":
                return DEMOGRAPHIC_MISMATCH;
            case "matched_cancelled_order":
                return MATCHED_CANCELLED_ORDER;
            case "possible_wrong_lab":
                return POSSIBLE_WRONG_LAB;
            case "demographic_match":
                return DEMOGRAPHIC_MATCH;
            case "sample_id_match":
                return SAMPLE_ID_MATCH;
            case "lab_account_mismatch":
                return LAB_ACCOUNT_MISMATCH;
            case "matched_completed_order":
                return MATCHED_COMPLETED_ORDER;
            default:
                return new MatchCandidateReasonCode(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        SAMPLE_ID_MATCH,

        LAB_ACCOUNT_MISMATCH,

        MATCHED_COMPLETED_ORDER,

        MATCHED_CANCELLED_ORDER,

        INVALID_COLLECTION_STATE,

        DEMOGRAPHIC_MISMATCH,

        DEMOGRAPHIC_MATCH,

        POSSIBLE_WRONG_LAB,

        SAME_LAB,

        SAME_USER,

        MARKER_OVERLAP_EXACT,

        MARKER_OVERLAP_PARTIAL,

        MARKER_OVERLAP_NONE,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitSampleIdMatch();

        T visitLabAccountMismatch();

        T visitMatchedCompletedOrder();

        T visitMatchedCancelledOrder();

        T visitInvalidCollectionState();

        T visitDemographicMismatch();

        T visitDemographicMatch();

        T visitPossibleWrongLab();

        T visitSameLab();

        T visitSameUser();

        T visitMarkerOverlapExact();

        T visitMarkerOverlapPartial();

        T visitMarkerOverlapNone();

        T visitUnknown(String unknownType);
    }
}
