/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.junction.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class McOvulationTestFieldExprOvulationTest {
    public static final McOvulationTestFieldExprOvulationTest TEST_RESULT =
            new McOvulationTestFieldExprOvulationTest(Value.TEST_RESULT, "test_result");

    public static final McOvulationTestFieldExprOvulationTest DATE =
            new McOvulationTestFieldExprOvulationTest(Value.DATE, "date");

    private final Value value;

    private final String string;

    McOvulationTestFieldExprOvulationTest(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof McOvulationTestFieldExprOvulationTest
                        && this.string.equals(((McOvulationTestFieldExprOvulationTest) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case TEST_RESULT:
                return visitor.visitTestResult();
            case DATE:
                return visitor.visitDate();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static McOvulationTestFieldExprOvulationTest valueOf(String value) {
        switch (value) {
            case "test_result":
                return TEST_RESULT;
            case "date":
                return DATE;
            default:
                return new McOvulationTestFieldExprOvulationTest(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        DATE,

        TEST_RESULT,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitDate();

        T visitTestResult();

        T visitUnknown(String unknownType);
    }
}
