/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.junction.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class OAuthProviders {
    public static final OAuthProviders ULTRAHUMAN = new OAuthProviders(Value.ULTRAHUMAN, "ultrahuman");

    public static final OAuthProviders STRAVA = new OAuthProviders(Value.STRAVA, "strava");

    public static final OAuthProviders WHOOP_V_2 = new OAuthProviders(Value.WHOOP_V_2, "whoop_v2");

    public static final OAuthProviders CRONOMETER = new OAuthProviders(Value.CRONOMETER, "cronometer");

    public static final OAuthProviders POLAR = new OAuthProviders(Value.POLAR, "polar");

    public static final OAuthProviders GARMIN = new OAuthProviders(Value.GARMIN, "garmin");

    public static final OAuthProviders RUNKEEPER = new OAuthProviders(Value.RUNKEEPER, "runkeeper");

    public static final OAuthProviders OURA = new OAuthProviders(Value.OURA, "oura");

    public static final OAuthProviders OMRON = new OAuthProviders(Value.OMRON, "omron");

    public static final OAuthProviders MY_FITNESS_PAL_V_2 =
            new OAuthProviders(Value.MY_FITNESS_PAL_V_2, "my_fitness_pal_v2");

    public static final OAuthProviders GOOGLE_FIT = new OAuthProviders(Value.GOOGLE_FIT, "google_fit");

    public static final OAuthProviders FITBIT = new OAuthProviders(Value.FITBIT, "fitbit");

    public static final OAuthProviders DEXCOM_V_3 = new OAuthProviders(Value.DEXCOM_V_3, "dexcom_v3");

    public static final OAuthProviders WITHINGS = new OAuthProviders(Value.WITHINGS, "withings");

    public static final OAuthProviders IHEALTH = new OAuthProviders(Value.IHEALTH, "ihealth");

    public static final OAuthProviders WAHOO = new OAuthProviders(Value.WAHOO, "wahoo");

    private final Value value;

    private final String string;

    OAuthProviders(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof OAuthProviders && this.string.equals(((OAuthProviders) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case ULTRAHUMAN:
                return visitor.visitUltrahuman();
            case STRAVA:
                return visitor.visitStrava();
            case WHOOP_V_2:
                return visitor.visitWhoopV2();
            case CRONOMETER:
                return visitor.visitCronometer();
            case POLAR:
                return visitor.visitPolar();
            case GARMIN:
                return visitor.visitGarmin();
            case RUNKEEPER:
                return visitor.visitRunkeeper();
            case OURA:
                return visitor.visitOura();
            case OMRON:
                return visitor.visitOmron();
            case MY_FITNESS_PAL_V_2:
                return visitor.visitMyFitnessPalV2();
            case GOOGLE_FIT:
                return visitor.visitGoogleFit();
            case FITBIT:
                return visitor.visitFitbit();
            case DEXCOM_V_3:
                return visitor.visitDexcomV3();
            case WITHINGS:
                return visitor.visitWithings();
            case IHEALTH:
                return visitor.visitIhealth();
            case WAHOO:
                return visitor.visitWahoo();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static OAuthProviders valueOf(String value) {
        switch (value) {
            case "ultrahuman":
                return ULTRAHUMAN;
            case "strava":
                return STRAVA;
            case "whoop_v2":
                return WHOOP_V_2;
            case "cronometer":
                return CRONOMETER;
            case "polar":
                return POLAR;
            case "garmin":
                return GARMIN;
            case "runkeeper":
                return RUNKEEPER;
            case "oura":
                return OURA;
            case "omron":
                return OMRON;
            case "my_fitness_pal_v2":
                return MY_FITNESS_PAL_V_2;
            case "google_fit":
                return GOOGLE_FIT;
            case "fitbit":
                return FITBIT;
            case "dexcom_v3":
                return DEXCOM_V_3;
            case "withings":
                return WITHINGS;
            case "ihealth":
                return IHEALTH;
            case "wahoo":
                return WAHOO;
            default:
                return new OAuthProviders(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        OURA,

        FITBIT,

        GARMIN,

        STRAVA,

        WAHOO,

        IHEALTH,

        WITHINGS,

        GOOGLE_FIT,

        DEXCOM_V_3,

        POLAR,

        CRONOMETER,

        OMRON,

        WHOOP_V_2,

        MY_FITNESS_PAL_V_2,

        ULTRAHUMAN,

        RUNKEEPER,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitOura();

        T visitFitbit();

        T visitGarmin();

        T visitStrava();

        T visitWahoo();

        T visitIhealth();

        T visitWithings();

        T visitGoogleFit();

        T visitDexcomV3();

        T visitPolar();

        T visitCronometer();

        T visitOmron();

        T visitWhoopV2();

        T visitMyFitnessPalV2();

        T visitUltrahuman();

        T visitRunkeeper();

        T visitUnknown(String unknownType);
    }
}
