/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.junction.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class OrderMarkerTrackingStatus {
    public static final OrderMarkerTrackingStatus PENDING = new OrderMarkerTrackingStatus(Value.PENDING, "pending");

    public static final OrderMarkerTrackingStatus RESULTED = new OrderMarkerTrackingStatus(Value.RESULTED, "resulted");

    public static final OrderMarkerTrackingStatus INCOMPLETE =
            new OrderMarkerTrackingStatus(Value.INCOMPLETE, "incomplete");

    private final Value value;

    private final String string;

    OrderMarkerTrackingStatus(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof OrderMarkerTrackingStatus
                        && this.string.equals(((OrderMarkerTrackingStatus) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case PENDING:
                return visitor.visitPending();
            case RESULTED:
                return visitor.visitResulted();
            case INCOMPLETE:
                return visitor.visitIncomplete();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static OrderMarkerTrackingStatus valueOf(String value) {
        switch (value) {
            case "pending":
                return PENDING;
            case "resulted":
                return RESULTED;
            case "incomplete":
                return INCOMPLETE;
            default:
                return new OrderMarkerTrackingStatus(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        PENDING,

        INCOMPLETE,

        RESULTED,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitPending();

        T visitIncomplete();

        T visitResulted();

        T visitUnknown(String unknownType);
    }
}
