/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.junction.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.junction.api.core.Nullable;
import com.junction.api.core.NullableNonemptyFilter;
import com.junction.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = OrderTrackingImpactedMarker.Builder.class)
public final class OrderTrackingImpactedMarker {
    private final int id;

    private final String name;

    private final Optional<String> providerId;

    private final OrderTrackingEstimate estimates;

    private final Map<String, Object> additionalProperties;

    private OrderTrackingImpactedMarker(
            int id,
            String name,
            Optional<String> providerId,
            OrderTrackingEstimate estimates,
            Map<String, Object> additionalProperties) {
        this.id = id;
        this.name = name;
        this.providerId = providerId;
        this.estimates = estimates;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("id")
    public int getId() {
        return id;
    }

    @JsonProperty("name")
    public String getName() {
        return name;
    }

    @JsonIgnore
    public Optional<String> getProviderId() {
        if (providerId == null) {
            return Optional.empty();
        }
        return providerId;
    }

    @JsonProperty("estimates")
    public OrderTrackingEstimate getEstimates() {
        return estimates;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("provider_id")
    private Optional<String> _getProviderId() {
        return providerId;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof OrderTrackingImpactedMarker && equalTo((OrderTrackingImpactedMarker) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(OrderTrackingImpactedMarker other) {
        return id == other.id
                && name.equals(other.name)
                && providerId.equals(other.providerId)
                && estimates.equals(other.estimates);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.id, this.name, this.providerId, this.estimates);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static IdStage builder() {
        return new Builder();
    }

    public interface IdStage {
        NameStage id(int id);

        Builder from(OrderTrackingImpactedMarker other);
    }

    public interface NameStage {
        EstimatesStage name(@NotNull String name);
    }

    public interface EstimatesStage {
        _FinalStage estimates(@NotNull OrderTrackingEstimate estimates);
    }

    public interface _FinalStage {
        OrderTrackingImpactedMarker build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        _FinalStage providerId(Optional<String> providerId);

        _FinalStage providerId(String providerId);

        _FinalStage providerId(Nullable<String> providerId);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements IdStage, NameStage, EstimatesStage, _FinalStage {
        private int id;

        private String name;

        private OrderTrackingEstimate estimates;

        private Optional<String> providerId = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(OrderTrackingImpactedMarker other) {
            id(other.getId());
            name(other.getName());
            providerId(other.getProviderId());
            estimates(other.getEstimates());
            return this;
        }

        @java.lang.Override
        @JsonSetter("id")
        public NameStage id(int id) {
            this.id = id;
            return this;
        }

        @java.lang.Override
        @JsonSetter("name")
        public EstimatesStage name(@NotNull String name) {
            this.name = Objects.requireNonNull(name, "name must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("estimates")
        public _FinalStage estimates(@NotNull OrderTrackingEstimate estimates) {
            this.estimates = Objects.requireNonNull(estimates, "estimates must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage providerId(Nullable<String> providerId) {
            if (providerId.isNull()) {
                this.providerId = null;
            } else if (providerId.isEmpty()) {
                this.providerId = Optional.empty();
            } else {
                this.providerId = Optional.of(providerId.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage providerId(String providerId) {
            this.providerId = Optional.ofNullable(providerId);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "provider_id", nulls = Nulls.SKIP)
        public _FinalStage providerId(Optional<String> providerId) {
            this.providerId = providerId;
            return this;
        }

        @java.lang.Override
        public OrderTrackingImpactedMarker build() {
            return new OrderTrackingImpactedMarker(id, name, providerId, estimates, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
