/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.junction.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.junction.api.core.Nullable;
import com.junction.api.core.NullableNonemptyFilter;
import com.junction.api.core.ObjectMappers;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = OrderTrackingUpdate.Builder.class)
public final class OrderTrackingUpdate {
    private final OffsetDateTime createdAt;

    private final Optional<String> reason;

    private final Optional<OffsetDateTime> revisedEstimate;

    private final List<OrderTrackingImpactedMarker> impactedMarkers;

    private final EtaUpdateSource source;

    private final Map<String, Object> additionalProperties;

    private OrderTrackingUpdate(
            OffsetDateTime createdAt,
            Optional<String> reason,
            Optional<OffsetDateTime> revisedEstimate,
            List<OrderTrackingImpactedMarker> impactedMarkers,
            EtaUpdateSource source,
            Map<String, Object> additionalProperties) {
        this.createdAt = createdAt;
        this.reason = reason;
        this.revisedEstimate = revisedEstimate;
        this.impactedMarkers = impactedMarkers;
        this.source = source;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("created_at")
    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }

    @JsonIgnore
    public Optional<String> getReason() {
        if (reason == null) {
            return Optional.empty();
        }
        return reason;
    }

    @JsonIgnore
    public Optional<OffsetDateTime> getRevisedEstimate() {
        if (revisedEstimate == null) {
            return Optional.empty();
        }
        return revisedEstimate;
    }

    @JsonProperty("impacted_markers")
    public List<OrderTrackingImpactedMarker> getImpactedMarkers() {
        return impactedMarkers;
    }

    /**
     * @return ℹ️ This enum is non-exhaustive.
     */
    @JsonProperty("source")
    public EtaUpdateSource getSource() {
        return source;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("reason")
    private Optional<String> _getReason() {
        return reason;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("revised_estimate")
    private Optional<OffsetDateTime> _getRevisedEstimate() {
        return revisedEstimate;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof OrderTrackingUpdate && equalTo((OrderTrackingUpdate) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(OrderTrackingUpdate other) {
        return createdAt.equals(other.createdAt)
                && reason.equals(other.reason)
                && revisedEstimate.equals(other.revisedEstimate)
                && impactedMarkers.equals(other.impactedMarkers)
                && source.equals(other.source);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.createdAt, this.reason, this.revisedEstimate, this.impactedMarkers, this.source);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static CreatedAtStage builder() {
        return new Builder();
    }

    public interface CreatedAtStage {
        SourceStage createdAt(@NotNull OffsetDateTime createdAt);

        Builder from(OrderTrackingUpdate other);
    }

    public interface SourceStage {
        /**
         * <p>ℹ️ This enum is non-exhaustive.</p>
         */
        _FinalStage source(@NotNull EtaUpdateSource source);
    }

    public interface _FinalStage {
        OrderTrackingUpdate build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        _FinalStage reason(Optional<String> reason);

        _FinalStage reason(String reason);

        _FinalStage reason(Nullable<String> reason);

        _FinalStage revisedEstimate(Optional<OffsetDateTime> revisedEstimate);

        _FinalStage revisedEstimate(OffsetDateTime revisedEstimate);

        _FinalStage revisedEstimate(Nullable<OffsetDateTime> revisedEstimate);

        _FinalStage impactedMarkers(List<OrderTrackingImpactedMarker> impactedMarkers);

        _FinalStage addImpactedMarkers(OrderTrackingImpactedMarker impactedMarkers);

        _FinalStage addAllImpactedMarkers(List<OrderTrackingImpactedMarker> impactedMarkers);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements CreatedAtStage, SourceStage, _FinalStage {
        private OffsetDateTime createdAt;

        private EtaUpdateSource source;

        private List<OrderTrackingImpactedMarker> impactedMarkers = new ArrayList<>();

        private Optional<OffsetDateTime> revisedEstimate = Optional.empty();

        private Optional<String> reason = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(OrderTrackingUpdate other) {
            createdAt(other.getCreatedAt());
            reason(other.getReason());
            revisedEstimate(other.getRevisedEstimate());
            impactedMarkers(other.getImpactedMarkers());
            source(other.getSource());
            return this;
        }

        @java.lang.Override
        @JsonSetter("created_at")
        public SourceStage createdAt(@NotNull OffsetDateTime createdAt) {
            this.createdAt = Objects.requireNonNull(createdAt, "createdAt must not be null");
            return this;
        }

        /**
         * <p>ℹ️ This enum is non-exhaustive.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("source")
        public _FinalStage source(@NotNull EtaUpdateSource source) {
            this.source = Objects.requireNonNull(source, "source must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage addAllImpactedMarkers(List<OrderTrackingImpactedMarker> impactedMarkers) {
            if (impactedMarkers != null) {
                this.impactedMarkers.addAll(impactedMarkers);
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage addImpactedMarkers(OrderTrackingImpactedMarker impactedMarkers) {
            this.impactedMarkers.add(impactedMarkers);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "impacted_markers", nulls = Nulls.SKIP)
        public _FinalStage impactedMarkers(List<OrderTrackingImpactedMarker> impactedMarkers) {
            this.impactedMarkers.clear();
            if (impactedMarkers != null) {
                this.impactedMarkers.addAll(impactedMarkers);
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage revisedEstimate(Nullable<OffsetDateTime> revisedEstimate) {
            if (revisedEstimate.isNull()) {
                this.revisedEstimate = null;
            } else if (revisedEstimate.isEmpty()) {
                this.revisedEstimate = Optional.empty();
            } else {
                this.revisedEstimate = Optional.of(revisedEstimate.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage revisedEstimate(OffsetDateTime revisedEstimate) {
            this.revisedEstimate = Optional.ofNullable(revisedEstimate);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "revised_estimate", nulls = Nulls.SKIP)
        public _FinalStage revisedEstimate(Optional<OffsetDateTime> revisedEstimate) {
            this.revisedEstimate = revisedEstimate;
            return this;
        }

        @java.lang.Override
        public _FinalStage reason(Nullable<String> reason) {
            if (reason.isNull()) {
                this.reason = null;
            } else if (reason.isEmpty()) {
                this.reason = Optional.empty();
            } else {
                this.reason = Optional.of(reason.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage reason(String reason) {
            this.reason = Optional.ofNullable(reason);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "reason", nulls = Nulls.SKIP)
        public _FinalStage reason(Optional<String> reason) {
            this.reason = reason;
            return this;
        }

        @java.lang.Override
        public OrderTrackingUpdate build() {
            return new OrderTrackingUpdate(
                    createdAt, reason, revisedEstimate, impactedMarkers, source, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
