/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.junction.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class OvulationTestEntryTestResult {
    public static final OvulationTestEntryTestResult POSITIVE =
            new OvulationTestEntryTestResult(Value.POSITIVE, "positive");

    public static final OvulationTestEntryTestResult ESTROGEN_SURGE =
            new OvulationTestEntryTestResult(Value.ESTROGEN_SURGE, "estrogen_surge");

    public static final OvulationTestEntryTestResult LUTEINIZING_HORMONE_SURGE =
            new OvulationTestEntryTestResult(Value.LUTEINIZING_HORMONE_SURGE, "luteinizing_hormone_surge");

    public static final OvulationTestEntryTestResult NEGATIVE =
            new OvulationTestEntryTestResult(Value.NEGATIVE, "negative");

    public static final OvulationTestEntryTestResult INDETERMINATE =
            new OvulationTestEntryTestResult(Value.INDETERMINATE, "indeterminate");

    private final Value value;

    private final String string;

    OvulationTestEntryTestResult(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof OvulationTestEntryTestResult
                        && this.string.equals(((OvulationTestEntryTestResult) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case POSITIVE:
                return visitor.visitPositive();
            case ESTROGEN_SURGE:
                return visitor.visitEstrogenSurge();
            case LUTEINIZING_HORMONE_SURGE:
                return visitor.visitLuteinizingHormoneSurge();
            case NEGATIVE:
                return visitor.visitNegative();
            case INDETERMINATE:
                return visitor.visitIndeterminate();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static OvulationTestEntryTestResult valueOf(String value) {
        switch (value) {
            case "positive":
                return POSITIVE;
            case "estrogen_surge":
                return ESTROGEN_SURGE;
            case "luteinizing_hormone_surge":
                return LUTEINIZING_HORMONE_SURGE;
            case "negative":
                return NEGATIVE;
            case "indeterminate":
                return INDETERMINATE;
            default:
                return new OvulationTestEntryTestResult(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        NEGATIVE,

        POSITIVE,

        LUTEINIZING_HORMONE_SURGE,

        ESTROGEN_SURGE,

        INDETERMINATE,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitNegative();

        T visitPositive();

        T visitLuteinizingHormoneSurge();

        T visitEstrogenSurge();

        T visitIndeterminate();

        T visitUnknown(String unknownType);
    }
}
