/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.junction.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class PasswordProviders {
    public static final PasswordProviders ZWIFT = new PasswordProviders(Value.ZWIFT, "zwift");

    public static final PasswordProviders DEXCOM = new PasswordProviders(Value.DEXCOM, "dexcom");

    public static final PasswordProviders KARDIA = new PasswordProviders(Value.KARDIA, "kardia");

    public static final PasswordProviders PELOTON = new PasswordProviders(Value.PELOTON, "peloton");

    public static final PasswordProviders WHOOP = new PasswordProviders(Value.WHOOP, "whoop");

    public static final PasswordProviders HAMMERHEAD = new PasswordProviders(Value.HAMMERHEAD, "hammerhead");

    public static final PasswordProviders RENPHO = new PasswordProviders(Value.RENPHO, "renpho");

    public static final PasswordProviders TANDEM_SOURCE = new PasswordProviders(Value.TANDEM_SOURCE, "tandem_source");

    public static final PasswordProviders BEURER_API = new PasswordProviders(Value.BEURER_API, "beurer_api");

    public static final PasswordProviders ABBOTT_LIBREVIEW =
            new PasswordProviders(Value.ABBOTT_LIBREVIEW, "abbott_libreview");

    public static final PasswordProviders MY_FITNESS_PAL =
            new PasswordProviders(Value.MY_FITNESS_PAL, "my_fitness_pal");

    public static final PasswordProviders EIGHT_SLEEP = new PasswordProviders(Value.EIGHT_SLEEP, "eight_sleep");

    private final Value value;

    private final String string;

    PasswordProviders(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof PasswordProviders && this.string.equals(((PasswordProviders) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case ZWIFT:
                return visitor.visitZwift();
            case DEXCOM:
                return visitor.visitDexcom();
            case KARDIA:
                return visitor.visitKardia();
            case PELOTON:
                return visitor.visitPeloton();
            case WHOOP:
                return visitor.visitWhoop();
            case HAMMERHEAD:
                return visitor.visitHammerhead();
            case RENPHO:
                return visitor.visitRenpho();
            case TANDEM_SOURCE:
                return visitor.visitTandemSource();
            case BEURER_API:
                return visitor.visitBeurerApi();
            case ABBOTT_LIBREVIEW:
                return visitor.visitAbbottLibreview();
            case MY_FITNESS_PAL:
                return visitor.visitMyFitnessPal();
            case EIGHT_SLEEP:
                return visitor.visitEightSleep();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static PasswordProviders valueOf(String value) {
        switch (value) {
            case "zwift":
                return ZWIFT;
            case "dexcom":
                return DEXCOM;
            case "kardia":
                return KARDIA;
            case "peloton":
                return PELOTON;
            case "whoop":
                return WHOOP;
            case "hammerhead":
                return HAMMERHEAD;
            case "renpho":
                return RENPHO;
            case "tandem_source":
                return TANDEM_SOURCE;
            case "beurer_api":
                return BEURER_API;
            case "abbott_libreview":
                return ABBOTT_LIBREVIEW;
            case "my_fitness_pal":
                return MY_FITNESS_PAL;
            case "eight_sleep":
                return EIGHT_SLEEP;
            default:
                return new PasswordProviders(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        WHOOP,

        RENPHO,

        PELOTON,

        ZWIFT,

        EIGHT_SLEEP,

        BEURER_API,

        DEXCOM,

        HAMMERHEAD,

        MY_FITNESS_PAL,

        KARDIA,

        ABBOTT_LIBREVIEW,

        TANDEM_SOURCE,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitWhoop();

        T visitRenpho();

        T visitPeloton();

        T visitZwift();

        T visitEightSleep();

        T visitBeurerApi();

        T visitDexcom();

        T visitHammerhead();

        T visitMyFitnessPal();

        T visitKardia();

        T visitAbbottLibreview();

        T visitTandemSource();

        T visitUnknown(String unknownType);
    }
}
