/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.junction.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.junction.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = PricingModifierRange.Builder.class)
public final class PricingModifierRange {
    private final int minimum;

    private final int maximum;

    private final Map<String, Object> additionalProperties;

    private PricingModifierRange(int minimum, int maximum, Map<String, Object> additionalProperties) {
        this.minimum = minimum;
        this.maximum = maximum;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("minimum")
    public int getMinimum() {
        return minimum;
    }

    @JsonProperty("maximum")
    public int getMaximum() {
        return maximum;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof PricingModifierRange && equalTo((PricingModifierRange) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(PricingModifierRange other) {
        return minimum == other.minimum && maximum == other.maximum;
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.minimum, this.maximum);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static MinimumStage builder() {
        return new Builder();
    }

    public interface MinimumStage {
        MaximumStage minimum(int minimum);

        Builder from(PricingModifierRange other);
    }

    public interface MaximumStage {
        _FinalStage maximum(int maximum);
    }

    public interface _FinalStage {
        PricingModifierRange build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements MinimumStage, MaximumStage, _FinalStage {
        private int minimum;

        private int maximum;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(PricingModifierRange other) {
            minimum(other.getMinimum());
            maximum(other.getMaximum());
            return this;
        }

        @java.lang.Override
        @JsonSetter("minimum")
        public MaximumStage minimum(int minimum) {
            this.minimum = minimum;
            return this;
        }

        @java.lang.Override
        @JsonSetter("maximum")
        public _FinalStage maximum(int maximum) {
            this.maximum = maximum;
            return this;
        }

        @java.lang.Override
        public PricingModifierRange build() {
            return new PricingModifierRange(minimum, maximum, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
