/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.junction.api.types;

import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.JsonParseException;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.junction.api.core.ObjectMappers;
import java.io.IOException;
import java.util.Map;
import java.util.Objects;

@JsonDeserialize(using = PricingModifierComponentPricingConditionsDeltaAmountMinor.Deserializer.class)
public final class PricingModifierComponentPricingConditionsDeltaAmountMinor {
    private final Object value;

    private final int type;

    private PricingModifierComponentPricingConditionsDeltaAmountMinor(Object value, int type) {
        this.value = value;
        this.type = type;
    }

    @JsonValue
    public Object get() {
        return this.value;
    }

    @SuppressWarnings("unchecked")
    public <T> T visit(Visitor<T> visitor) {
        if (this.type == 0) {
            return visitor.visit((int) this.value);
        } else if (this.type == 1) {
            return visitor.visit((PricingModifierRange) this.value);
        }
        throw new IllegalStateException("Failed to visit value. This should never happen.");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof PricingModifierComponentPricingConditionsDeltaAmountMinor
                && equalTo((PricingModifierComponentPricingConditionsDeltaAmountMinor) other);
    }

    private boolean equalTo(PricingModifierComponentPricingConditionsDeltaAmountMinor other) {
        return value.equals(other.value);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.value);
    }

    @java.lang.Override
    public String toString() {
        return this.value.toString();
    }

    public static PricingModifierComponentPricingConditionsDeltaAmountMinor of(int value) {
        return new PricingModifierComponentPricingConditionsDeltaAmountMinor(value, 0);
    }

    public static PricingModifierComponentPricingConditionsDeltaAmountMinor of(PricingModifierRange value) {
        return new PricingModifierComponentPricingConditionsDeltaAmountMinor(value, 1);
    }

    public interface Visitor<T> {
        T visit(int value);

        T visit(PricingModifierRange value);
    }

    static final class Deserializer extends StdDeserializer<PricingModifierComponentPricingConditionsDeltaAmountMinor> {
        Deserializer() {
            super(PricingModifierComponentPricingConditionsDeltaAmountMinor.class);
        }

        @java.lang.Override
        public PricingModifierComponentPricingConditionsDeltaAmountMinor deserialize(
                JsonParser p, DeserializationContext context) throws IOException {
            Object value = p.readValueAs(Object.class);
            if (value instanceof Integer) {
                return of((Integer) value);
            }
            if (value instanceof Map<?, ?>
                    && ((Map<?, ?>) value).containsKey("minimum")
                    && ((Map<?, ?>) value).containsKey("maximum")) {
                try {
                    return of(ObjectMappers.JSON_MAPPER.convertValue(value, PricingModifierRange.class));
                } catch (RuntimeException e) {
                }
            }
            throw new JsonParseException(p, "Failed to deserialize");
        }
    }
}
