/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.junction.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class ProviderLinkResponseState {
    public static final ProviderLinkResponseState SUCCESS = new ProviderLinkResponseState(Value.SUCCESS, "success");

    public static final ProviderLinkResponseState ERROR = new ProviderLinkResponseState(Value.ERROR, "error");

    public static final ProviderLinkResponseState PENDING_PROVIDER_MFA =
            new ProviderLinkResponseState(Value.PENDING_PROVIDER_MFA, "pending_provider_mfa");

    private final Value value;

    private final String string;

    ProviderLinkResponseState(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof ProviderLinkResponseState
                        && this.string.equals(((ProviderLinkResponseState) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case SUCCESS:
                return visitor.visitSuccess();
            case ERROR:
                return visitor.visitError();
            case PENDING_PROVIDER_MFA:
                return visitor.visitPendingProviderMfa();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static ProviderLinkResponseState valueOf(String value) {
        switch (value) {
            case "success":
                return SUCCESS;
            case "error":
                return ERROR;
            case "pending_provider_mfa":
                return PENDING_PROVIDER_MFA;
            default:
                return new ProviderLinkResponseState(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        SUCCESS,

        ERROR,

        PENDING_PROVIDER_MFA,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitSuccess();

        T visitError();

        T visitPendingProviderMfa();

        T visitUnknown(String unknownType);
    }
}
