/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.junction.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class QuestionType {
    public static final QuestionType NUMERIC = new QuestionType(Value.NUMERIC, "numeric");

    public static final QuestionType TEXT = new QuestionType(Value.TEXT, "text");

    public static final QuestionType MULTI_CHOICE = new QuestionType(Value.MULTI_CHOICE, "multi_choice");

    public static final QuestionType CHOICE = new QuestionType(Value.CHOICE, "choice");

    private final Value value;

    private final String string;

    QuestionType(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other) || (other instanceof QuestionType && this.string.equals(((QuestionType) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case NUMERIC:
                return visitor.visitNumeric();
            case TEXT:
                return visitor.visitText();
            case MULTI_CHOICE:
                return visitor.visitMultiChoice();
            case CHOICE:
                return visitor.visitChoice();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static QuestionType valueOf(String value) {
        switch (value) {
            case "numeric":
                return NUMERIC;
            case "text":
                return TEXT;
            case "multi_choice":
                return MULTI_CHOICE;
            case "choice":
                return CHOICE;
            default:
                return new QuestionType(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        CHOICE,

        TEXT,

        NUMERIC,

        MULTI_CHOICE,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitChoice();

        T visitText();

        T visitNumeric();

        T visitMultiChoice();

        T visitUnknown(String unknownType);
    }
}
