/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.junction.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class Region {
    public static final Region BR = new Region(Value.BR, "br");

    public static final Region HK = new Region(Value.HK, "hk");

    public static final Region LU = new Region(Value.LU, "lu");

    public static final Region QA = new Region(Value.QA, "qa");

    public static final Region ES = new Region(Value.ES, "es");

    public static final Region GB = new Region(Value.GB, "gb");

    public static final Region DE = new Region(Value.DE, "de");

    public static final Region HR = new Region(Value.HR, "hr");

    public static final Region EU = new Region(Value.EU, "eu");

    public static final Region IL = new Region(Value.IL, "il");

    public static final Region NL = new Region(Value.NL, "nl");

    public static final Region US = new Region(Value.US, "us");

    public static final Region MX = new Region(Value.MX, "mx");

    public static final Region IN = new Region(Value.IN, "in");

    public static final Region CA = new Region(Value.CA, "ca");

    public static final Region AU = new Region(Value.AU, "au");

    public static final Region CZ = new Region(Value.CZ, "cz");

    public static final Region KW = new Region(Value.KW, "kw");

    public static final Region IT = new Region(Value.IT, "it");

    public static final Region SA = new Region(Value.SA, "sa");

    public static final Region CH = new Region(Value.CH, "ch");

    public static final Region GR = new Region(Value.GR, "gr");

    public static final Region PH = new Region(Value.PH, "ph");

    public static final Region JO = new Region(Value.JO, "jo");

    public static final Region SE = new Region(Value.SE, "se");

    public static final Region CL = new Region(Value.CL, "cl");

    public static final Region NZ = new Region(Value.NZ, "nz");

    public static final Region TR = new Region(Value.TR, "tr");

    public static final Region IE = new Region(Value.IE, "ie");

    public static final Region FI = new Region(Value.FI, "fi");

    public static final Region PL = new Region(Value.PL, "pl");

    public static final Region SG = new Region(Value.SG, "sg");

    public static final Region LB = new Region(Value.LB, "lb");

    public static final Region TW = new Region(Value.TW, "tw");

    public static final Region CO = new Region(Value.CO, "co");

    public static final Region SI = new Region(Value.SI, "si");

    public static final Region SK = new Region(Value.SK, "sk");

    public static final Region BE = new Region(Value.BE, "be");

    public static final Region DK = new Region(Value.DK, "dk");

    public static final Region KR = new Region(Value.KR, "kr");

    public static final Region BH = new Region(Value.BH, "bh");

    public static final Region AR = new Region(Value.AR, "ar");

    public static final Region PT = new Region(Value.PT, "pt");

    public static final Region FR = new Region(Value.FR, "fr");

    public static final Region NO = new Region(Value.NO, "no");

    public static final Region EG = new Region(Value.EG, "eg");

    public static final Region ZA = new Region(Value.ZA, "za");

    public static final Region AT = new Region(Value.AT, "at");

    public static final Region OM = new Region(Value.OM, "om");

    private final Value value;

    private final String string;

    Region(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other) || (other instanceof Region && this.string.equals(((Region) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case BR:
                return visitor.visitBr();
            case HK:
                return visitor.visitHk();
            case LU:
                return visitor.visitLu();
            case QA:
                return visitor.visitQa();
            case ES:
                return visitor.visitEs();
            case GB:
                return visitor.visitGb();
            case DE:
                return visitor.visitDe();
            case HR:
                return visitor.visitHr();
            case EU:
                return visitor.visitEu();
            case IL:
                return visitor.visitIl();
            case NL:
                return visitor.visitNl();
            case US:
                return visitor.visitUs();
            case MX:
                return visitor.visitMx();
            case IN:
                return visitor.visitIn();
            case CA:
                return visitor.visitCa();
            case AU:
                return visitor.visitAu();
            case CZ:
                return visitor.visitCz();
            case KW:
                return visitor.visitKw();
            case IT:
                return visitor.visitIt();
            case SA:
                return visitor.visitSa();
            case CH:
                return visitor.visitCh();
            case GR:
                return visitor.visitGr();
            case PH:
                return visitor.visitPh();
            case JO:
                return visitor.visitJo();
            case SE:
                return visitor.visitSe();
            case CL:
                return visitor.visitCl();
            case NZ:
                return visitor.visitNz();
            case TR:
                return visitor.visitTr();
            case IE:
                return visitor.visitIe();
            case FI:
                return visitor.visitFi();
            case PL:
                return visitor.visitPl();
            case SG:
                return visitor.visitSg();
            case LB:
                return visitor.visitLb();
            case TW:
                return visitor.visitTw();
            case CO:
                return visitor.visitCo();
            case SI:
                return visitor.visitSi();
            case SK:
                return visitor.visitSk();
            case BE:
                return visitor.visitBe();
            case DK:
                return visitor.visitDk();
            case KR:
                return visitor.visitKr();
            case BH:
                return visitor.visitBh();
            case AR:
                return visitor.visitAr();
            case PT:
                return visitor.visitPt();
            case FR:
                return visitor.visitFr();
            case NO:
                return visitor.visitNo();
            case EG:
                return visitor.visitEg();
            case ZA:
                return visitor.visitZa();
            case AT:
                return visitor.visitAt();
            case OM:
                return visitor.visitOm();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static Region valueOf(String value) {
        switch (value) {
            case "br":
                return BR;
            case "hk":
                return HK;
            case "lu":
                return LU;
            case "qa":
                return QA;
            case "es":
                return ES;
            case "gb":
                return GB;
            case "de":
                return DE;
            case "hr":
                return HR;
            case "eu":
                return EU;
            case "il":
                return IL;
            case "nl":
                return NL;
            case "us":
                return US;
            case "mx":
                return MX;
            case "in":
                return IN;
            case "ca":
                return CA;
            case "au":
                return AU;
            case "cz":
                return CZ;
            case "kw":
                return KW;
            case "it":
                return IT;
            case "sa":
                return SA;
            case "ch":
                return CH;
            case "gr":
                return GR;
            case "ph":
                return PH;
            case "jo":
                return JO;
            case "se":
                return SE;
            case "cl":
                return CL;
            case "nz":
                return NZ;
            case "tr":
                return TR;
            case "ie":
                return IE;
            case "fi":
                return FI;
            case "pl":
                return PL;
            case "sg":
                return SG;
            case "lb":
                return LB;
            case "tw":
                return TW;
            case "co":
                return CO;
            case "si":
                return SI;
            case "sk":
                return SK;
            case "be":
                return BE;
            case "dk":
                return DK;
            case "kr":
                return KR;
            case "bh":
                return BH;
            case "ar":
                return AR;
            case "pt":
                return PT;
            case "fr":
                return FR;
            case "no":
                return NO;
            case "eg":
                return EG;
            case "za":
                return ZA;
            case "at":
                return AT;
            case "om":
                return OM;
            default:
                return new Region(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        US,

        EU,

        DE,

        FR,

        CA,

        BR,

        AR,

        CL,

        CO,

        MX,

        GB,

        IE,

        AU,

        NZ,

        NL,

        AT,

        BE,

        BH,

        CH,

        CZ,

        DK,

        EG,

        ES,

        FI,

        GR,

        HR,

        IL,

        IT,

        JO,

        KW,

        LB,

        LU,

        NO,

        OM,

        PL,

        PT,

        QA,

        SA,

        SE,

        SI,

        SK,

        TR,

        ZA,

        IN,

        SG,

        HK,

        KR,

        PH,

        TW,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitUs();

        T visitEu();

        T visitDe();

        T visitFr();

        T visitCa();

        T visitBr();

        T visitAr();

        T visitCl();

        T visitCo();

        T visitMx();

        T visitGb();

        T visitIe();

        T visitAu();

        T visitNz();

        T visitNl();

        T visitAt();

        T visitBe();

        T visitBh();

        T visitCh();

        T visitCz();

        T visitDk();

        T visitEg();

        T visitEs();

        T visitFi();

        T visitGr();

        T visitHr();

        T visitIl();

        T visitIt();

        T visitJo();

        T visitKw();

        T visitLb();

        T visitLu();

        T visitNo();

        T visitOm();

        T visitPl();

        T visitPt();

        T visitQa();

        T visitSa();

        T visitSe();

        T visitSi();

        T visitSk();

        T visitTr();

        T visitZa();

        T visitIn();

        T visitSg();

        T visitHk();

        T visitKr();

        T visitPh();

        T visitTw();

        T visitUnknown(String unknownType);
    }
}
