/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.junction.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class ResponsibleRelationship {
    public static final ResponsibleRelationship SELF = new ResponsibleRelationship(Value.SELF, "Self");

    public static final ResponsibleRelationship OTHER = new ResponsibleRelationship(Value.OTHER, "Other");

    public static final ResponsibleRelationship SPOUSE = new ResponsibleRelationship(Value.SPOUSE, "Spouse");

    private final Value value;

    private final String string;

    ResponsibleRelationship(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof ResponsibleRelationship
                        && this.string.equals(((ResponsibleRelationship) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case SELF:
                return visitor.visitSelf();
            case OTHER:
                return visitor.visitOther();
            case SPOUSE:
                return visitor.visitSpouse();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static ResponsibleRelationship valueOf(String value) {
        switch (value) {
            case "Self":
                return SELF;
            case "Other":
                return OTHER;
            case "Spouse":
                return SPOUSE;
            default:
                return new ResponsibleRelationship(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        SELF,

        SPOUSE,

        OTHER,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitSelf();

        T visitSpouse();

        T visitOther();

        T visitUnknown(String unknownType);
    }
}
