/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.junction.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class ResultMetadataGender {
    public static final ResultMetadataGender MALE = new ResultMetadataGender(Value.MALE, "male");

    public static final ResultMetadataGender FEMALE = new ResultMetadataGender(Value.FEMALE, "female");

    public static final ResultMetadataGender OTHER = new ResultMetadataGender(Value.OTHER, "other");

    private final Value value;

    private final String string;

    ResultMetadataGender(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof ResultMetadataGender && this.string.equals(((ResultMetadataGender) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case MALE:
                return visitor.visitMale();
            case FEMALE:
                return visitor.visitFemale();
            case OTHER:
                return visitor.visitOther();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static ResultMetadataGender valueOf(String value) {
        switch (value) {
            case "male":
                return MALE;
            case "female":
                return FEMALE;
            case "other":
                return OTHER;
            default:
                return new ResultMetadataGender(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        MALE,

        FEMALE,

        OTHER,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitMale();

        T visitFemale();

        T visitOther();

        T visitUnknown(String unknownType);
    }
}
