/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.junction.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class SourceColumnExprSource {
    public static final SourceColumnExprSource SOURCE_TYPE =
            new SourceColumnExprSource(Value.SOURCE_TYPE, "source_type");

    public static final SourceColumnExprSource SOURCE_PROVIDER =
            new SourceColumnExprSource(Value.SOURCE_PROVIDER, "source_provider");

    public static final SourceColumnExprSource SOURCE_APP_ID =
            new SourceColumnExprSource(Value.SOURCE_APP_ID, "source_app_id");

    public static final SourceColumnExprSource SOURCE_WORKOUT_ID =
            new SourceColumnExprSource(Value.SOURCE_WORKOUT_ID, "source_workout_id");

    public static final SourceColumnExprSource SOURCE_SPORT =
            new SourceColumnExprSource(Value.SOURCE_SPORT, "source_sport");

    private final Value value;

    private final String string;

    SourceColumnExprSource(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof SourceColumnExprSource
                        && this.string.equals(((SourceColumnExprSource) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case SOURCE_TYPE:
                return visitor.visitSourceType();
            case SOURCE_PROVIDER:
                return visitor.visitSourceProvider();
            case SOURCE_APP_ID:
                return visitor.visitSourceAppId();
            case SOURCE_WORKOUT_ID:
                return visitor.visitSourceWorkoutId();
            case SOURCE_SPORT:
                return visitor.visitSourceSport();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static SourceColumnExprSource valueOf(String value) {
        switch (value) {
            case "source_type":
                return SOURCE_TYPE;
            case "source_provider":
                return SOURCE_PROVIDER;
            case "source_app_id":
                return SOURCE_APP_ID;
            case "source_workout_id":
                return SOURCE_WORKOUT_ID;
            case "source_sport":
                return SOURCE_SPORT;
            default:
                return new SourceColumnExprSource(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        SOURCE_PROVIDER,

        SOURCE_TYPE,

        SOURCE_APP_ID,

        SOURCE_WORKOUT_ID,

        SOURCE_SPORT,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitSourceProvider();

        T visitSourceType();

        T visitSourceAppId();

        T visitSourceWorkoutId();

        T visitSourceSport();

        T visitUnknown(String unknownType);
    }
}
