/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.junction.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class TemperatureTimeseriesExprField {
    public static final TemperatureTimeseriesExprField SOURCE_TYPE =
            new TemperatureTimeseriesExprField(Value.SOURCE_TYPE, "source_type");

    public static final TemperatureTimeseriesExprField SOURCE_PROVIDER =
            new TemperatureTimeseriesExprField(Value.SOURCE_PROVIDER, "source_provider");

    public static final TemperatureTimeseriesExprField TIMEZONE_OFFSET =
            new TemperatureTimeseriesExprField(Value.TIMEZONE_OFFSET, "timezone_offset");

    public static final TemperatureTimeseriesExprField SOURCE_APP_ID =
            new TemperatureTimeseriesExprField(Value.SOURCE_APP_ID, "source_app_id");

    public static final TemperatureTimeseriesExprField TYPE = new TemperatureTimeseriesExprField(Value.TYPE, "type");

    public static final TemperatureTimeseriesExprField SOURCE_WORKOUT_ID =
            new TemperatureTimeseriesExprField(Value.SOURCE_WORKOUT_ID, "source_workout_id");

    public static final TemperatureTimeseriesExprField DURATION =
            new TemperatureTimeseriesExprField(Value.DURATION, "duration");

    public static final TemperatureTimeseriesExprField SENSOR_LOCATION =
            new TemperatureTimeseriesExprField(Value.SENSOR_LOCATION, "sensor_location");

    public static final TemperatureTimeseriesExprField VALUE = new TemperatureTimeseriesExprField(Value.VALUE, "value");

    public static final TemperatureTimeseriesExprField SOURCE_SPORT =
            new TemperatureTimeseriesExprField(Value.SOURCE_SPORT, "source_sport");

    private final Value value;

    private final String string;

    TemperatureTimeseriesExprField(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof TemperatureTimeseriesExprField
                        && this.string.equals(((TemperatureTimeseriesExprField) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case SOURCE_TYPE:
                return visitor.visitSourceType();
            case SOURCE_PROVIDER:
                return visitor.visitSourceProvider();
            case TIMEZONE_OFFSET:
                return visitor.visitTimezoneOffset();
            case SOURCE_APP_ID:
                return visitor.visitSourceAppId();
            case TYPE:
                return visitor.visitType();
            case SOURCE_WORKOUT_ID:
                return visitor.visitSourceWorkoutId();
            case DURATION:
                return visitor.visitDuration();
            case SENSOR_LOCATION:
                return visitor.visitSensorLocation();
            case VALUE:
                return visitor.visitValue();
            case SOURCE_SPORT:
                return visitor.visitSourceSport();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static TemperatureTimeseriesExprField valueOf(String value) {
        switch (value) {
            case "source_type":
                return SOURCE_TYPE;
            case "source_provider":
                return SOURCE_PROVIDER;
            case "timezone_offset":
                return TIMEZONE_OFFSET;
            case "source_app_id":
                return SOURCE_APP_ID;
            case "type":
                return TYPE;
            case "source_workout_id":
                return SOURCE_WORKOUT_ID;
            case "duration":
                return DURATION;
            case "sensor_location":
                return SENSOR_LOCATION;
            case "value":
                return VALUE;
            case "source_sport":
                return SOURCE_SPORT;
            default:
                return new TemperatureTimeseriesExprField(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        SOURCE_PROVIDER,

        SOURCE_TYPE,

        SOURCE_APP_ID,

        SOURCE_WORKOUT_ID,

        SOURCE_SPORT,

        TIMEZONE_OFFSET,

        TYPE,

        DURATION,

        VALUE,

        SENSOR_LOCATION,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitSourceProvider();

        T visitSourceType();

        T visitSourceAppId();

        T visitSourceWorkoutId();

        T visitSourceSport();

        T visitTimezoneOffset();

        T visitType();

        T visitDuration();

        T visitValue();

        T visitSensorLocation();

        T visitUnknown(String unknownType);
    }
}
