/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.junction.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class UnmatchedResultUpdateStatus {
    public static final UnmatchedResultUpdateStatus PENDING_CUSTOMER_REVIEW =
            new UnmatchedResultUpdateStatus(Value.PENDING_CUSTOMER_REVIEW, "pending_customer_review");

    public static final UnmatchedResultUpdateStatus PENDING_CUSTOMER_REVIEW_IN_PROGRESS =
            new UnmatchedResultUpdateStatus(
                    Value.PENDING_CUSTOMER_REVIEW_IN_PROGRESS, "pending_customer_review:in_progress");

    private final Value value;

    private final String string;

    UnmatchedResultUpdateStatus(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof UnmatchedResultUpdateStatus
                        && this.string.equals(((UnmatchedResultUpdateStatus) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case PENDING_CUSTOMER_REVIEW:
                return visitor.visitPendingCustomerReview();
            case PENDING_CUSTOMER_REVIEW_IN_PROGRESS:
                return visitor.visitPendingCustomerReviewInProgress();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static UnmatchedResultUpdateStatus valueOf(String value) {
        switch (value) {
            case "pending_customer_review":
                return PENDING_CUSTOMER_REVIEW;
            case "pending_customer_review:in_progress":
                return PENDING_CUSTOMER_REVIEW_IN_PROGRESS;
            default:
                return new UnmatchedResultUpdateStatus(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        PENDING_CUSTOMER_REVIEW,

        PENDING_CUSTOMER_REVIEW_IN_PROGRESS,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitPendingCustomerReview();

        T visitPendingCustomerReviewInProgress();

        T visitUnknown(String unknownType);
    }
}
