/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.junction.api.errors;

import com.junction.api.core.ApiError;
import com.junction.api.types.HttpValidationError;
import okhttp3.Response;

public final class UnprocessableEntityError extends ApiError {
    /**
     * The body of the response that triggered the exception.
     */
    private final HttpValidationError body;

    public UnprocessableEntityError(HttpValidationError body) {
        super("UnprocessableEntityError", 422, body);
        this.body = body;
    }

    public UnprocessableEntityError(HttpValidationError body, Response rawResponse) {
        super("UnprocessableEntityError", 422, body, rawResponse);
        this.body = body;
    }

    /**
     * @return the body
     */
    @java.lang.Override
    public HttpValidationError body() {
        return this.body;
    }
}
