/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.junction.api.resources.insurance;

import com.junction.api.core.ClientOptions;
import com.junction.api.core.RequestOptions;
import com.junction.api.resources.insurance.requests.PayorSearchRequest;
import com.junction.api.resources.insurance.requests.SearchDiagnosisInsuranceRequest;
import com.junction.api.resources.insurance.requests.SearchGetPayorInfoInsuranceRequest;
import com.junction.api.types.ClientFacingDiagnosisInformation;
import com.junction.api.types.ClientFacingPayorSearchResponse;
import com.junction.api.types.ClientFacingPayorSearchResponseDeprecated;
import java.util.List;

public class InsuranceClient {
    protected final ClientOptions clientOptions;

    private final RawInsuranceClient rawClient;

    public InsuranceClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawInsuranceClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawInsuranceClient withRawResponse() {
        return this.rawClient;
    }

    public List<ClientFacingPayorSearchResponse> searchGetPayorInfo() {
        return this.rawClient.searchGetPayorInfo().body();
    }

    public List<ClientFacingPayorSearchResponse> searchGetPayorInfo(RequestOptions requestOptions) {
        return this.rawClient.searchGetPayorInfo(requestOptions).body();
    }

    public List<ClientFacingPayorSearchResponse> searchGetPayorInfo(SearchGetPayorInfoInsuranceRequest request) {
        return this.rawClient.searchGetPayorInfo(request).body();
    }

    public List<ClientFacingPayorSearchResponse> searchGetPayorInfo(
            SearchGetPayorInfoInsuranceRequest request, RequestOptions requestOptions) {
        return this.rawClient.searchGetPayorInfo(request, requestOptions).body();
    }

    public List<ClientFacingPayorSearchResponseDeprecated> searchPayorInfo() {
        return this.rawClient.searchPayorInfo().body();
    }

    public List<ClientFacingPayorSearchResponseDeprecated> searchPayorInfo(RequestOptions requestOptions) {
        return this.rawClient.searchPayorInfo(requestOptions).body();
    }

    public List<ClientFacingPayorSearchResponseDeprecated> searchPayorInfo(PayorSearchRequest request) {
        return this.rawClient.searchPayorInfo(request).body();
    }

    public List<ClientFacingPayorSearchResponseDeprecated> searchPayorInfo(
            PayorSearchRequest request, RequestOptions requestOptions) {
        return this.rawClient.searchPayorInfo(request, requestOptions).body();
    }

    public List<ClientFacingDiagnosisInformation> searchDiagnosis(SearchDiagnosisInsuranceRequest request) {
        return this.rawClient.searchDiagnosis(request).body();
    }

    public List<ClientFacingDiagnosisInformation> searchDiagnosis(
            SearchDiagnosisInsuranceRequest request, RequestOptions requestOptions) {
        return this.rawClient.searchDiagnosis(request, requestOptions).body();
    }
}
