/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.junction.api.resources.checkout.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.junction.api.core.Nullable;
import com.junction.api.core.NullableNonemptyFilter;
import com.junction.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = RefineCheckoutQuoteBody.Builder.class)
public final class RefineCheckoutQuoteBody {
    private final Optional<Boolean> priority;

    private final Map<String, Object> additionalProperties;

    private RefineCheckoutQuoteBody(Optional<Boolean> priority, Map<String, Object> additionalProperties) {
        this.priority = priority;
        this.additionalProperties = additionalProperties;
    }

    @JsonIgnore
    public Optional<Boolean> getPriority() {
        if (priority == null) {
            return Optional.empty();
        }
        return priority;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("priority")
    private Optional<Boolean> _getPriority() {
        return priority;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof RefineCheckoutQuoteBody && equalTo((RefineCheckoutQuoteBody) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(RefineCheckoutQuoteBody other) {
        return priority.equals(other.priority);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.priority);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Boolean> priority = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(RefineCheckoutQuoteBody other) {
            priority(other.getPriority());
            return this;
        }

        @JsonSetter(value = "priority", nulls = Nulls.SKIP)
        public Builder priority(Optional<Boolean> priority) {
            this.priority = priority;
            return this;
        }

        public Builder priority(Boolean priority) {
            this.priority = Optional.ofNullable(priority);
            return this;
        }

        public Builder priority(Nullable<Boolean> priority) {
            if (priority.isNull()) {
                this.priority = null;
            } else if (priority.isEmpty()) {
                this.priority = Optional.empty();
            } else {
                this.priority = Optional.of(priority.get());
            }
            return this;
        }

        public RefineCheckoutQuoteBody build() {
            return new RefineCheckoutQuoteBody(priority, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
