/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.junction.api.resources.testkit;

import com.junction.api.core.ClientOptions;
import com.junction.api.core.RequestOptions;
import com.junction.api.resources.testkit.requests.CreateRegistrableTestkitOrderRequest;
import com.junction.api.resources.testkit.requests.RegisterTestkitRequest;
import com.junction.api.types.PostOrderResponse;

public class TestkitClient {
    protected final ClientOptions clientOptions;

    private final RawTestkitClient rawClient;

    public TestkitClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawTestkitClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawTestkitClient withRawResponse() {
        return this.rawClient;
    }

    public PostOrderResponse register(RegisterTestkitRequest request) {
        return this.rawClient.register(request).body();
    }

    public PostOrderResponse register(RegisterTestkitRequest request, RequestOptions requestOptions) {
        return this.rawClient.register(request, requestOptions).body();
    }

    /**
     * Creates an order for an unregistered testkit
     */
    public PostOrderResponse createOrder(CreateRegistrableTestkitOrderRequest request) {
        return this.rawClient.createOrder(request).body();
    }

    /**
     * Creates an order for an unregistered testkit
     */
    public PostOrderResponse createOrder(CreateRegistrableTestkitOrderRequest request, RequestOptions requestOptions) {
        return this.rawClient.createOrder(request, requestOptions).body();
    }
}
