/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.junction.api.resources.vitals;

import com.junction.api.core.ClientOptions;
import com.junction.api.core.RequestOptions;
import com.junction.api.resources.vitals.requests.AfibBurdenGroupedVitalsRequest;
import com.junction.api.resources.vitals.requests.BasalBodyTemperatureGroupedVitalsRequest;
import com.junction.api.resources.vitals.requests.BloodOxygenGroupedVitalsRequest;
import com.junction.api.resources.vitals.requests.BloodOxygenVitalsRequest;
import com.junction.api.resources.vitals.requests.BloodPressureGroupedVitalsRequest;
import com.junction.api.resources.vitals.requests.BloodPressureVitalsRequest;
import com.junction.api.resources.vitals.requests.BodyFatGroupedVitalsRequest;
import com.junction.api.resources.vitals.requests.BodyFatVitalsRequest;
import com.junction.api.resources.vitals.requests.BodyMassIndexGroupedVitalsRequest;
import com.junction.api.resources.vitals.requests.BodyTemperatureDeltaGroupedVitalsRequest;
import com.junction.api.resources.vitals.requests.BodyTemperatureGroupedVitalsRequest;
import com.junction.api.resources.vitals.requests.BodyWeightGroupedVitalsRequest;
import com.junction.api.resources.vitals.requests.BodyWeightVitalsRequest;
import com.junction.api.resources.vitals.requests.CaffeineGroupedVitalsRequest;
import com.junction.api.resources.vitals.requests.CaffeineVitalsRequest;
import com.junction.api.resources.vitals.requests.CaloriesActiveGroupedVitalsRequest;
import com.junction.api.resources.vitals.requests.CaloriesActiveVitalsRequest;
import com.junction.api.resources.vitals.requests.CaloriesBasalGroupedVitalsRequest;
import com.junction.api.resources.vitals.requests.CaloriesBasalVitalsRequest;
import com.junction.api.resources.vitals.requests.CarbohydratesGroupedVitalsRequest;
import com.junction.api.resources.vitals.requests.CholesterolGroupedVitalsRequest;
import com.junction.api.resources.vitals.requests.CholesterolHdlVitalsRequest;
import com.junction.api.resources.vitals.requests.CholesterolLdlVitalsRequest;
import com.junction.api.resources.vitals.requests.CholesterolTotalVitalsRequest;
import com.junction.api.resources.vitals.requests.CholesterolTriglyceridesVitalsRequest;
import com.junction.api.resources.vitals.requests.CholesterolVitalsRequest;
import com.junction.api.resources.vitals.requests.DaylightExposureGroupedVitalsRequest;
import com.junction.api.resources.vitals.requests.DistanceGroupedVitalsRequest;
import com.junction.api.resources.vitals.requests.DistanceVitalsRequest;
import com.junction.api.resources.vitals.requests.ElectrocardiogramVoltageGroupedVitalsRequest;
import com.junction.api.resources.vitals.requests.ElectrocardiogramVoltageVitalsRequest;
import com.junction.api.resources.vitals.requests.FallGroupedVitalsRequest;
import com.junction.api.resources.vitals.requests.FloorsClimbedGroupedVitalsRequest;
import com.junction.api.resources.vitals.requests.FloorsClimbedVitalsRequest;
import com.junction.api.resources.vitals.requests.ForcedExpiratoryVolume1GroupedVitalsRequest;
import com.junction.api.resources.vitals.requests.ForcedVitalCapacityGroupedVitalsRequest;
import com.junction.api.resources.vitals.requests.GlucoseGroupedVitalsRequest;
import com.junction.api.resources.vitals.requests.GlucoseVitalsRequest;
import com.junction.api.resources.vitals.requests.HandwashingGroupedVitalsRequest;
import com.junction.api.resources.vitals.requests.HeartRateAlertGroupedVitalsRequest;
import com.junction.api.resources.vitals.requests.HeartRateRecoveryOneMinuteGroupedVitalsRequest;
import com.junction.api.resources.vitals.requests.HeartrateGroupedVitalsRequest;
import com.junction.api.resources.vitals.requests.HeartrateVitalsRequest;
import com.junction.api.resources.vitals.requests.HrvGroupedVitalsRequest;
import com.junction.api.resources.vitals.requests.HrvVitalsRequest;
import com.junction.api.resources.vitals.requests.HypnogramGroupedVitalsRequest;
import com.junction.api.resources.vitals.requests.HypnogramVitalsRequest;
import com.junction.api.resources.vitals.requests.IgeGroupedVitalsRequest;
import com.junction.api.resources.vitals.requests.IgeVitalsRequest;
import com.junction.api.resources.vitals.requests.IggGroupedVitalsRequest;
import com.junction.api.resources.vitals.requests.IggVitalsRequest;
import com.junction.api.resources.vitals.requests.InhalerUsageGroupedVitalsRequest;
import com.junction.api.resources.vitals.requests.InsulinInjectionGroupedVitalsRequest;
import com.junction.api.resources.vitals.requests.LeanBodyMassGroupedVitalsRequest;
import com.junction.api.resources.vitals.requests.MindfulnessMinutesGroupedVitalsRequest;
import com.junction.api.resources.vitals.requests.MindfulnessMinutesVitalsRequest;
import com.junction.api.resources.vitals.requests.NoteGroupedVitalsRequest;
import com.junction.api.resources.vitals.requests.PeakExpiratoryFlowRateGroupedVitalsRequest;
import com.junction.api.resources.vitals.requests.RespiratoryRateGroupedVitalsRequest;
import com.junction.api.resources.vitals.requests.RespiratoryRateVitalsRequest;
import com.junction.api.resources.vitals.requests.SleepApneaAlertGroupedVitalsRequest;
import com.junction.api.resources.vitals.requests.SleepBreathingDisturbanceGroupedVitalsRequest;
import com.junction.api.resources.vitals.requests.StandDurationGroupedVitalsRequest;
import com.junction.api.resources.vitals.requests.StandHourGroupedVitalsRequest;
import com.junction.api.resources.vitals.requests.StepsGroupedVitalsRequest;
import com.junction.api.resources.vitals.requests.StepsVitalsRequest;
import com.junction.api.resources.vitals.requests.StressLevelGroupedVitalsRequest;
import com.junction.api.resources.vitals.requests.StressLevelVitalsRequest;
import com.junction.api.resources.vitals.requests.UvExposureGroupedVitalsRequest;
import com.junction.api.resources.vitals.requests.Vo2MaxGroupedVitalsRequest;
import com.junction.api.resources.vitals.requests.Vo2MaxVitalsRequest;
import com.junction.api.resources.vitals.requests.WaistCircumferenceGroupedVitalsRequest;
import com.junction.api.resources.vitals.requests.WaterGroupedVitalsRequest;
import com.junction.api.resources.vitals.requests.WaterVitalsRequest;
import com.junction.api.resources.vitals.requests.WheelchairPushGroupedVitalsRequest;
import com.junction.api.resources.vitals.requests.WorkoutDistanceGroupedVitalsRequest;
import com.junction.api.resources.vitals.requests.WorkoutDurationGroupedVitalsRequest;
import com.junction.api.resources.vitals.requests.WorkoutSwimmingStrokeGroupedVitalsRequest;
import com.junction.api.types.ClientFacingBloodOxygenTimeseries;
import com.junction.api.types.ClientFacingBloodPressureTimeseries;
import com.junction.api.types.ClientFacingBodyFatTimeseries;
import com.junction.api.types.ClientFacingBodyWeightTimeseries;
import com.junction.api.types.ClientFacingCaffeineTimeseries;
import com.junction.api.types.ClientFacingCaloriesActiveTimeseries;
import com.junction.api.types.ClientFacingCaloriesBasalTimeseries;
import com.junction.api.types.ClientFacingCholesterolTimeseries;
import com.junction.api.types.ClientFacingDistanceTimeseries;
import com.junction.api.types.ClientFacingElectrocardiogramVoltageTimeseries;
import com.junction.api.types.ClientFacingFloorsClimbedTimeseries;
import com.junction.api.types.ClientFacingGlucoseTimeseries;
import com.junction.api.types.ClientFacingHeartRateTimeseries;
import com.junction.api.types.ClientFacingHrvTimeseries;
import com.junction.api.types.ClientFacingHypnogramTimeseries;
import com.junction.api.types.ClientFacingIgeTimeseries;
import com.junction.api.types.ClientFacingIggTimeseries;
import com.junction.api.types.ClientFacingMindfulnessMinutesTimeseries;
import com.junction.api.types.ClientFacingRespiratoryRateTimeseries;
import com.junction.api.types.ClientFacingStepsTimeseries;
import com.junction.api.types.ClientFacingStressLevelTimeseries;
import com.junction.api.types.ClientFacingVo2MaxTimeseries;
import com.junction.api.types.ClientFacingWaterTimeseries;
import com.junction.api.types.GroupedAFibBurdenResponse;
import com.junction.api.types.GroupedBasalBodyTemperatureResponse;
import com.junction.api.types.GroupedBloodOxygenResponse;
import com.junction.api.types.GroupedBloodPressureResponse;
import com.junction.api.types.GroupedBodyFatResponse;
import com.junction.api.types.GroupedBodyMassIndexResponse;
import com.junction.api.types.GroupedBodyTemperatureDeltaResponse;
import com.junction.api.types.GroupedBodyTemperatureResponse;
import com.junction.api.types.GroupedBodyWeightResponse;
import com.junction.api.types.GroupedCaffeineResponse;
import com.junction.api.types.GroupedCaloriesActiveResponse;
import com.junction.api.types.GroupedCaloriesBasalResponse;
import com.junction.api.types.GroupedCarbohydratesResponse;
import com.junction.api.types.GroupedCholesterolResponse;
import com.junction.api.types.GroupedDaylightExposureResponse;
import com.junction.api.types.GroupedDistanceResponse;
import com.junction.api.types.GroupedElectrocardiogramVoltageResponse;
import com.junction.api.types.GroupedFallResponse;
import com.junction.api.types.GroupedFloorsClimbedResponse;
import com.junction.api.types.GroupedForcedExpiratoryVolume1Response;
import com.junction.api.types.GroupedForcedVitalCapacityResponse;
import com.junction.api.types.GroupedGlucoseResponse;
import com.junction.api.types.GroupedHandwashingResponse;
import com.junction.api.types.GroupedHeartRateAlertResponse;
import com.junction.api.types.GroupedHeartRateRecoveryOneMinuteResponse;
import com.junction.api.types.GroupedHeartRateResponse;
import com.junction.api.types.GroupedHrvResponse;
import com.junction.api.types.GroupedHypnogramResponse;
import com.junction.api.types.GroupedIgeResponse;
import com.junction.api.types.GroupedIggResponse;
import com.junction.api.types.GroupedInhalerUsageResponse;
import com.junction.api.types.GroupedInsulinInjectionResponse;
import com.junction.api.types.GroupedLeanBodyMassResponse;
import com.junction.api.types.GroupedMindfulnessMinutesResponse;
import com.junction.api.types.GroupedNoteResponse;
import com.junction.api.types.GroupedPeakExpiratoryFlowRateResponse;
import com.junction.api.types.GroupedRespiratoryRateResponse;
import com.junction.api.types.GroupedSleepApneaAlertResponse;
import com.junction.api.types.GroupedSleepBreathingDisturbanceResponse;
import com.junction.api.types.GroupedStandDurationResponse;
import com.junction.api.types.GroupedStandHourResponse;
import com.junction.api.types.GroupedStepsResponse;
import com.junction.api.types.GroupedStressLevelResponse;
import com.junction.api.types.GroupedUvExposureResponse;
import com.junction.api.types.GroupedVo2MaxResponse;
import com.junction.api.types.GroupedWaistCircumferenceResponse;
import com.junction.api.types.GroupedWaterResponse;
import com.junction.api.types.GroupedWheelchairPushResponse;
import com.junction.api.types.GroupedWorkoutDistanceResponse;
import com.junction.api.types.GroupedWorkoutDurationResponse;
import com.junction.api.types.GroupedWorkoutSwimmingStrokeResponse;
import java.util.List;
import java.util.concurrent.CompletableFuture;

public class AsyncVitalsClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawVitalsClient rawClient;

    public AsyncVitalsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawVitalsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawVitalsClient withRawResponse() {
        return this.rawClient;
    }

    public CompletableFuture<GroupedWorkoutSwimmingStrokeResponse> workoutSwimmingStrokeGrouped(
            String userId, WorkoutSwimmingStrokeGroupedVitalsRequest request) {
        return this.rawClient.workoutSwimmingStrokeGrouped(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedWorkoutSwimmingStrokeResponse> workoutSwimmingStrokeGrouped(
            String userId, WorkoutSwimmingStrokeGroupedVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .workoutSwimmingStrokeGrouped(userId, request, requestOptions)
                .thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedWorkoutDistanceResponse> workoutDistanceGrouped(
            String userId, WorkoutDistanceGroupedVitalsRequest request) {
        return this.rawClient.workoutDistanceGrouped(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedWorkoutDistanceResponse> workoutDistanceGrouped(
            String userId, WorkoutDistanceGroupedVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .workoutDistanceGrouped(userId, request, requestOptions)
                .thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedHeartRateRecoveryOneMinuteResponse> heartRateRecoveryOneMinuteGrouped(
            String userId, HeartRateRecoveryOneMinuteGroupedVitalsRequest request) {
        return this.rawClient.heartRateRecoveryOneMinuteGrouped(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedHeartRateRecoveryOneMinuteResponse> heartRateRecoveryOneMinuteGrouped(
            String userId, HeartRateRecoveryOneMinuteGroupedVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .heartRateRecoveryOneMinuteGrouped(userId, request, requestOptions)
                .thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedWaistCircumferenceResponse> waistCircumferenceGrouped(
            String userId, WaistCircumferenceGroupedVitalsRequest request) {
        return this.rawClient.waistCircumferenceGrouped(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedWaistCircumferenceResponse> waistCircumferenceGrouped(
            String userId, WaistCircumferenceGroupedVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .waistCircumferenceGrouped(userId, request, requestOptions)
                .thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedLeanBodyMassResponse> leanBodyMassGrouped(
            String userId, LeanBodyMassGroupedVitalsRequest request) {
        return this.rawClient.leanBodyMassGrouped(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedLeanBodyMassResponse> leanBodyMassGrouped(
            String userId, LeanBodyMassGroupedVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .leanBodyMassGrouped(userId, request, requestOptions)
                .thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedBodyMassIndexResponse> bodyMassIndexGrouped(
            String userId, BodyMassIndexGroupedVitalsRequest request) {
        return this.rawClient.bodyMassIndexGrouped(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedBodyMassIndexResponse> bodyMassIndexGrouped(
            String userId, BodyMassIndexGroupedVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .bodyMassIndexGrouped(userId, request, requestOptions)
                .thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedBasalBodyTemperatureResponse> basalBodyTemperatureGrouped(
            String userId, BasalBodyTemperatureGroupedVitalsRequest request) {
        return this.rawClient.basalBodyTemperatureGrouped(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedBasalBodyTemperatureResponse> basalBodyTemperatureGrouped(
            String userId, BasalBodyTemperatureGroupedVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .basalBodyTemperatureGrouped(userId, request, requestOptions)
                .thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedHandwashingResponse> handwashingGrouped(
            String userId, HandwashingGroupedVitalsRequest request) {
        return this.rawClient.handwashingGrouped(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedHandwashingResponse> handwashingGrouped(
            String userId, HandwashingGroupedVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .handwashingGrouped(userId, request, requestOptions)
                .thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedDaylightExposureResponse> daylightExposureGrouped(
            String userId, DaylightExposureGroupedVitalsRequest request) {
        return this.rawClient.daylightExposureGrouped(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedDaylightExposureResponse> daylightExposureGrouped(
            String userId, DaylightExposureGroupedVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .daylightExposureGrouped(userId, request, requestOptions)
                .thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedUvExposureResponse> uvExposureGrouped(
            String userId, UvExposureGroupedVitalsRequest request) {
        return this.rawClient.uvExposureGrouped(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedUvExposureResponse> uvExposureGrouped(
            String userId, UvExposureGroupedVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient.uvExposureGrouped(userId, request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedFallResponse> fallGrouped(String userId, FallGroupedVitalsRequest request) {
        return this.rawClient.fallGrouped(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedFallResponse> fallGrouped(
            String userId, FallGroupedVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient.fallGrouped(userId, request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedInhalerUsageResponse> inhalerUsageGrouped(
            String userId, InhalerUsageGroupedVitalsRequest request) {
        return this.rawClient.inhalerUsageGrouped(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedInhalerUsageResponse> inhalerUsageGrouped(
            String userId, InhalerUsageGroupedVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .inhalerUsageGrouped(userId, request, requestOptions)
                .thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedPeakExpiratoryFlowRateResponse> peakExpiratoryFlowRateGrouped(
            String userId, PeakExpiratoryFlowRateGroupedVitalsRequest request) {
        return this.rawClient.peakExpiratoryFlowRateGrouped(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedPeakExpiratoryFlowRateResponse> peakExpiratoryFlowRateGrouped(
            String userId, PeakExpiratoryFlowRateGroupedVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .peakExpiratoryFlowRateGrouped(userId, request, requestOptions)
                .thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedForcedVitalCapacityResponse> forcedVitalCapacityGrouped(
            String userId, ForcedVitalCapacityGroupedVitalsRequest request) {
        return this.rawClient.forcedVitalCapacityGrouped(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedForcedVitalCapacityResponse> forcedVitalCapacityGrouped(
            String userId, ForcedVitalCapacityGroupedVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .forcedVitalCapacityGrouped(userId, request, requestOptions)
                .thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedForcedExpiratoryVolume1Response> forcedExpiratoryVolume1Grouped(
            String userId, ForcedExpiratoryVolume1GroupedVitalsRequest request) {
        return this.rawClient.forcedExpiratoryVolume1Grouped(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedForcedExpiratoryVolume1Response> forcedExpiratoryVolume1Grouped(
            String userId, ForcedExpiratoryVolume1GroupedVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .forcedExpiratoryVolume1Grouped(userId, request, requestOptions)
                .thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedWheelchairPushResponse> wheelchairPushGrouped(
            String userId, WheelchairPushGroupedVitalsRequest request) {
        return this.rawClient.wheelchairPushGrouped(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedWheelchairPushResponse> wheelchairPushGrouped(
            String userId, WheelchairPushGroupedVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .wheelchairPushGrouped(userId, request, requestOptions)
                .thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedSleepBreathingDisturbanceResponse> sleepBreathingDisturbanceGrouped(
            String userId, SleepBreathingDisturbanceGroupedVitalsRequest request) {
        return this.rawClient.sleepBreathingDisturbanceGrouped(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedSleepBreathingDisturbanceResponse> sleepBreathingDisturbanceGrouped(
            String userId, SleepBreathingDisturbanceGroupedVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .sleepBreathingDisturbanceGrouped(userId, request, requestOptions)
                .thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedSleepApneaAlertResponse> sleepApneaAlertGrouped(
            String userId, SleepApneaAlertGroupedVitalsRequest request) {
        return this.rawClient.sleepApneaAlertGrouped(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedSleepApneaAlertResponse> sleepApneaAlertGrouped(
            String userId, SleepApneaAlertGroupedVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .sleepApneaAlertGrouped(userId, request, requestOptions)
                .thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedStandDurationResponse> standDurationGrouped(
            String userId, StandDurationGroupedVitalsRequest request) {
        return this.rawClient.standDurationGrouped(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedStandDurationResponse> standDurationGrouped(
            String userId, StandDurationGroupedVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .standDurationGrouped(userId, request, requestOptions)
                .thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedStandHourResponse> standHourGrouped(
            String userId, StandHourGroupedVitalsRequest request) {
        return this.rawClient.standHourGrouped(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedStandHourResponse> standHourGrouped(
            String userId, StandHourGroupedVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient.standHourGrouped(userId, request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedHeartRateAlertResponse> heartRateAlertGrouped(
            String userId, HeartRateAlertGroupedVitalsRequest request) {
        return this.rawClient.heartRateAlertGrouped(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedHeartRateAlertResponse> heartRateAlertGrouped(
            String userId, HeartRateAlertGroupedVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .heartRateAlertGrouped(userId, request, requestOptions)
                .thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedAFibBurdenResponse> afibBurdenGrouped(
            String userId, AfibBurdenGroupedVitalsRequest request) {
        return this.rawClient.afibBurdenGrouped(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedAFibBurdenResponse> afibBurdenGrouped(
            String userId, AfibBurdenGroupedVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient.afibBurdenGrouped(userId, request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedWorkoutDurationResponse> workoutDurationGrouped(
            String userId, WorkoutDurationGroupedVitalsRequest request) {
        return this.rawClient.workoutDurationGrouped(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedWorkoutDurationResponse> workoutDurationGrouped(
            String userId, WorkoutDurationGroupedVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .workoutDurationGrouped(userId, request, requestOptions)
                .thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedVo2MaxResponse> vo2MaxGrouped(String userId, Vo2MaxGroupedVitalsRequest request) {
        return this.rawClient.vo2MaxGrouped(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedVo2MaxResponse> vo2MaxGrouped(
            String userId, Vo2MaxGroupedVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient.vo2MaxGrouped(userId, request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedStressLevelResponse> stressLevelGrouped(
            String userId, StressLevelGroupedVitalsRequest request) {
        return this.rawClient.stressLevelGrouped(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedStressLevelResponse> stressLevelGrouped(
            String userId, StressLevelGroupedVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .stressLevelGrouped(userId, request, requestOptions)
                .thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedMindfulnessMinutesResponse> mindfulnessMinutesGrouped(
            String userId, MindfulnessMinutesGroupedVitalsRequest request) {
        return this.rawClient.mindfulnessMinutesGrouped(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedMindfulnessMinutesResponse> mindfulnessMinutesGrouped(
            String userId, MindfulnessMinutesGroupedVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .mindfulnessMinutesGrouped(userId, request, requestOptions)
                .thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedCaffeineResponse> caffeineGrouped(
            String userId, CaffeineGroupedVitalsRequest request) {
        return this.rawClient.caffeineGrouped(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedCaffeineResponse> caffeineGrouped(
            String userId, CaffeineGroupedVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient.caffeineGrouped(userId, request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedWaterResponse> waterGrouped(String userId, WaterGroupedVitalsRequest request) {
        return this.rawClient.waterGrouped(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedWaterResponse> waterGrouped(
            String userId, WaterGroupedVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient.waterGrouped(userId, request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedStepsResponse> stepsGrouped(String userId, StepsGroupedVitalsRequest request) {
        return this.rawClient.stepsGrouped(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedStepsResponse> stepsGrouped(
            String userId, StepsGroupedVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient.stepsGrouped(userId, request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedFloorsClimbedResponse> floorsClimbedGrouped(
            String userId, FloorsClimbedGroupedVitalsRequest request) {
        return this.rawClient.floorsClimbedGrouped(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedFloorsClimbedResponse> floorsClimbedGrouped(
            String userId, FloorsClimbedGroupedVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .floorsClimbedGrouped(userId, request, requestOptions)
                .thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedDistanceResponse> distanceGrouped(
            String userId, DistanceGroupedVitalsRequest request) {
        return this.rawClient.distanceGrouped(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedDistanceResponse> distanceGrouped(
            String userId, DistanceGroupedVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient.distanceGrouped(userId, request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedCaloriesBasalResponse> caloriesBasalGrouped(
            String userId, CaloriesBasalGroupedVitalsRequest request) {
        return this.rawClient.caloriesBasalGrouped(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedCaloriesBasalResponse> caloriesBasalGrouped(
            String userId, CaloriesBasalGroupedVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .caloriesBasalGrouped(userId, request, requestOptions)
                .thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedCaloriesActiveResponse> caloriesActiveGrouped(
            String userId, CaloriesActiveGroupedVitalsRequest request) {
        return this.rawClient.caloriesActiveGrouped(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedCaloriesActiveResponse> caloriesActiveGrouped(
            String userId, CaloriesActiveGroupedVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .caloriesActiveGrouped(userId, request, requestOptions)
                .thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedRespiratoryRateResponse> respiratoryRateGrouped(
            String userId, RespiratoryRateGroupedVitalsRequest request) {
        return this.rawClient.respiratoryRateGrouped(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedRespiratoryRateResponse> respiratoryRateGrouped(
            String userId, RespiratoryRateGroupedVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .respiratoryRateGrouped(userId, request, requestOptions)
                .thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedNoteResponse> noteGrouped(String userId, NoteGroupedVitalsRequest request) {
        return this.rawClient.noteGrouped(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedNoteResponse> noteGrouped(
            String userId, NoteGroupedVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient.noteGrouped(userId, request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedInsulinInjectionResponse> insulinInjectionGrouped(
            String userId, InsulinInjectionGroupedVitalsRequest request) {
        return this.rawClient.insulinInjectionGrouped(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedInsulinInjectionResponse> insulinInjectionGrouped(
            String userId, InsulinInjectionGroupedVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .insulinInjectionGrouped(userId, request, requestOptions)
                .thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedIgeResponse> igeGrouped(String userId, IgeGroupedVitalsRequest request) {
        return this.rawClient.igeGrouped(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedIgeResponse> igeGrouped(
            String userId, IgeGroupedVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient.igeGrouped(userId, request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedIggResponse> iggGrouped(String userId, IggGroupedVitalsRequest request) {
        return this.rawClient.iggGrouped(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedIggResponse> iggGrouped(
            String userId, IggGroupedVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient.iggGrouped(userId, request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedHypnogramResponse> hypnogramGrouped(
            String userId, HypnogramGroupedVitalsRequest request) {
        return this.rawClient.hypnogramGrouped(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedHypnogramResponse> hypnogramGrouped(
            String userId, HypnogramGroupedVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient.hypnogramGrouped(userId, request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedHrvResponse> hrvGrouped(String userId, HrvGroupedVitalsRequest request) {
        return this.rawClient.hrvGrouped(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedHrvResponse> hrvGrouped(
            String userId, HrvGroupedVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient.hrvGrouped(userId, request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedHeartRateResponse> heartrateGrouped(
            String userId, HeartrateGroupedVitalsRequest request) {
        return this.rawClient.heartrateGrouped(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedHeartRateResponse> heartrateGrouped(
            String userId, HeartrateGroupedVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient.heartrateGrouped(userId, request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedGlucoseResponse> glucoseGrouped(
            String userId, GlucoseGroupedVitalsRequest request) {
        return this.rawClient.glucoseGrouped(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedGlucoseResponse> glucoseGrouped(
            String userId, GlucoseGroupedVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient.glucoseGrouped(userId, request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedCholesterolResponse> cholesterolGrouped(
            String userId, CholesterolGroupedVitalsRequest request) {
        return this.rawClient.cholesterolGrouped(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedCholesterolResponse> cholesterolGrouped(
            String userId, CholesterolGroupedVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .cholesterolGrouped(userId, request, requestOptions)
                .thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedCarbohydratesResponse> carbohydratesGrouped(
            String userId, CarbohydratesGroupedVitalsRequest request) {
        return this.rawClient.carbohydratesGrouped(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedCarbohydratesResponse> carbohydratesGrouped(
            String userId, CarbohydratesGroupedVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .carbohydratesGrouped(userId, request, requestOptions)
                .thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedBodyTemperatureDeltaResponse> bodyTemperatureDeltaGrouped(
            String userId, BodyTemperatureDeltaGroupedVitalsRequest request) {
        return this.rawClient.bodyTemperatureDeltaGrouped(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedBodyTemperatureDeltaResponse> bodyTemperatureDeltaGrouped(
            String userId, BodyTemperatureDeltaGroupedVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .bodyTemperatureDeltaGrouped(userId, request, requestOptions)
                .thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedBodyTemperatureResponse> bodyTemperatureGrouped(
            String userId, BodyTemperatureGroupedVitalsRequest request) {
        return this.rawClient.bodyTemperatureGrouped(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedBodyTemperatureResponse> bodyTemperatureGrouped(
            String userId, BodyTemperatureGroupedVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .bodyTemperatureGrouped(userId, request, requestOptions)
                .thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedBodyWeightResponse> bodyWeightGrouped(
            String userId, BodyWeightGroupedVitalsRequest request) {
        return this.rawClient.bodyWeightGrouped(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedBodyWeightResponse> bodyWeightGrouped(
            String userId, BodyWeightGroupedVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient.bodyWeightGrouped(userId, request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedBodyFatResponse> bodyFatGrouped(
            String userId, BodyFatGroupedVitalsRequest request) {
        return this.rawClient.bodyFatGrouped(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedBodyFatResponse> bodyFatGrouped(
            String userId, BodyFatGroupedVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient.bodyFatGrouped(userId, request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedBloodOxygenResponse> bloodOxygenGrouped(
            String userId, BloodOxygenGroupedVitalsRequest request) {
        return this.rawClient.bloodOxygenGrouped(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedBloodOxygenResponse> bloodOxygenGrouped(
            String userId, BloodOxygenGroupedVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .bloodOxygenGrouped(userId, request, requestOptions)
                .thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedElectrocardiogramVoltageResponse> electrocardiogramVoltageGrouped(
            String userId, ElectrocardiogramVoltageGroupedVitalsRequest request) {
        return this.rawClient.electrocardiogramVoltageGrouped(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedElectrocardiogramVoltageResponse> electrocardiogramVoltageGrouped(
            String userId, ElectrocardiogramVoltageGroupedVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .electrocardiogramVoltageGrouped(userId, request, requestOptions)
                .thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedBloodPressureResponse> bloodPressureGrouped(
            String userId, BloodPressureGroupedVitalsRequest request) {
        return this.rawClient.bloodPressureGrouped(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<GroupedBloodPressureResponse> bloodPressureGrouped(
            String userId, BloodPressureGroupedVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .bloodPressureGrouped(userId, request, requestOptions)
                .thenApply(response -> response.body());
    }

    public CompletableFuture<List<ClientFacingVo2MaxTimeseries>> vo2Max(String userId, Vo2MaxVitalsRequest request) {
        return this.rawClient.vo2Max(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<List<ClientFacingVo2MaxTimeseries>> vo2Max(
            String userId, Vo2MaxVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient.vo2Max(userId, request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<List<ClientFacingStressLevelTimeseries>> stressLevel(
            String userId, StressLevelVitalsRequest request) {
        return this.rawClient.stressLevel(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<List<ClientFacingStressLevelTimeseries>> stressLevel(
            String userId, StressLevelVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient.stressLevel(userId, request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<List<ClientFacingMindfulnessMinutesTimeseries>> mindfulnessMinutes(
            String userId, MindfulnessMinutesVitalsRequest request) {
        return this.rawClient.mindfulnessMinutes(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<List<ClientFacingMindfulnessMinutesTimeseries>> mindfulnessMinutes(
            String userId, MindfulnessMinutesVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .mindfulnessMinutes(userId, request, requestOptions)
                .thenApply(response -> response.body());
    }

    public CompletableFuture<List<ClientFacingCaffeineTimeseries>> caffeine(
            String userId, CaffeineVitalsRequest request) {
        return this.rawClient.caffeine(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<List<ClientFacingCaffeineTimeseries>> caffeine(
            String userId, CaffeineVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient.caffeine(userId, request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<List<ClientFacingWaterTimeseries>> water(String userId, WaterVitalsRequest request) {
        return this.rawClient.water(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<List<ClientFacingWaterTimeseries>> water(
            String userId, WaterVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient.water(userId, request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<List<ClientFacingStepsTimeseries>> steps(String userId, StepsVitalsRequest request) {
        return this.rawClient.steps(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<List<ClientFacingStepsTimeseries>> steps(
            String userId, StepsVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient.steps(userId, request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<List<ClientFacingFloorsClimbedTimeseries>> floorsClimbed(
            String userId, FloorsClimbedVitalsRequest request) {
        return this.rawClient.floorsClimbed(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<List<ClientFacingFloorsClimbedTimeseries>> floorsClimbed(
            String userId, FloorsClimbedVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient.floorsClimbed(userId, request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<List<ClientFacingDistanceTimeseries>> distance(
            String userId, DistanceVitalsRequest request) {
        return this.rawClient.distance(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<List<ClientFacingDistanceTimeseries>> distance(
            String userId, DistanceVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient.distance(userId, request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<List<ClientFacingCaloriesBasalTimeseries>> caloriesBasal(
            String userId, CaloriesBasalVitalsRequest request) {
        return this.rawClient.caloriesBasal(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<List<ClientFacingCaloriesBasalTimeseries>> caloriesBasal(
            String userId, CaloriesBasalVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient.caloriesBasal(userId, request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<List<ClientFacingCaloriesActiveTimeseries>> caloriesActive(
            String userId, CaloriesActiveVitalsRequest request) {
        return this.rawClient.caloriesActive(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<List<ClientFacingCaloriesActiveTimeseries>> caloriesActive(
            String userId, CaloriesActiveVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient.caloriesActive(userId, request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<List<ClientFacingRespiratoryRateTimeseries>> respiratoryRate(
            String userId, RespiratoryRateVitalsRequest request) {
        return this.rawClient.respiratoryRate(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<List<ClientFacingRespiratoryRateTimeseries>> respiratoryRate(
            String userId, RespiratoryRateVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient.respiratoryRate(userId, request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<List<ClientFacingIgeTimeseries>> ige(String userId, IgeVitalsRequest request) {
        return this.rawClient.ige(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<List<ClientFacingIgeTimeseries>> ige(
            String userId, IgeVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient.ige(userId, request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<List<ClientFacingIggTimeseries>> igg(String userId, IggVitalsRequest request) {
        return this.rawClient.igg(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<List<ClientFacingIggTimeseries>> igg(
            String userId, IggVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient.igg(userId, request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<List<ClientFacingHypnogramTimeseries>> hypnogram(
            String userId, HypnogramVitalsRequest request) {
        return this.rawClient.hypnogram(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<List<ClientFacingHypnogramTimeseries>> hypnogram(
            String userId, HypnogramVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient.hypnogram(userId, request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<List<ClientFacingHrvTimeseries>> hrv(String userId, HrvVitalsRequest request) {
        return this.rawClient.hrv(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<List<ClientFacingHrvTimeseries>> hrv(
            String userId, HrvVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient.hrv(userId, request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<List<ClientFacingHeartRateTimeseries>> heartrate(
            String userId, HeartrateVitalsRequest request) {
        return this.rawClient.heartrate(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<List<ClientFacingHeartRateTimeseries>> heartrate(
            String userId, HeartrateVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient.heartrate(userId, request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<List<ClientFacingGlucoseTimeseries>> glucose(String userId, GlucoseVitalsRequest request) {
        return this.rawClient.glucose(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<List<ClientFacingGlucoseTimeseries>> glucose(
            String userId, GlucoseVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient.glucose(userId, request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<List<ClientFacingCholesterolTimeseries>> cholesterolTriglycerides(
            String userId, CholesterolTriglyceridesVitalsRequest request) {
        return this.rawClient.cholesterolTriglycerides(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<List<ClientFacingCholesterolTimeseries>> cholesterolTriglycerides(
            String userId, CholesterolTriglyceridesVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .cholesterolTriglycerides(userId, request, requestOptions)
                .thenApply(response -> response.body());
    }

    public CompletableFuture<List<ClientFacingCholesterolTimeseries>> cholesterolTotal(
            String userId, CholesterolTotalVitalsRequest request) {
        return this.rawClient.cholesterolTotal(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<List<ClientFacingCholesterolTimeseries>> cholesterolTotal(
            String userId, CholesterolTotalVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient.cholesterolTotal(userId, request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<List<ClientFacingCholesterolTimeseries>> cholesterolLdl(
            String userId, CholesterolLdlVitalsRequest request) {
        return this.rawClient.cholesterolLdl(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<List<ClientFacingCholesterolTimeseries>> cholesterolLdl(
            String userId, CholesterolLdlVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient.cholesterolLdl(userId, request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<List<ClientFacingCholesterolTimeseries>> cholesterolHdl(
            String userId, CholesterolHdlVitalsRequest request) {
        return this.rawClient.cholesterolHdl(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<List<ClientFacingCholesterolTimeseries>> cholesterolHdl(
            String userId, CholesterolHdlVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient.cholesterolHdl(userId, request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<List<ClientFacingCholesterolTimeseries>> cholesterol(
            String userId, CholesterolVitalsRequest request) {
        return this.rawClient.cholesterol(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<List<ClientFacingCholesterolTimeseries>> cholesterol(
            String userId, CholesterolVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient.cholesterol(userId, request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<List<ClientFacingBodyWeightTimeseries>> bodyWeight(
            String userId, BodyWeightVitalsRequest request) {
        return this.rawClient.bodyWeight(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<List<ClientFacingBodyWeightTimeseries>> bodyWeight(
            String userId, BodyWeightVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient.bodyWeight(userId, request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<List<ClientFacingBodyFatTimeseries>> bodyFat(String userId, BodyFatVitalsRequest request) {
        return this.rawClient.bodyFat(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<List<ClientFacingBodyFatTimeseries>> bodyFat(
            String userId, BodyFatVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient.bodyFat(userId, request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<List<ClientFacingBloodOxygenTimeseries>> bloodOxygen(
            String userId, BloodOxygenVitalsRequest request) {
        return this.rawClient.bloodOxygen(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<List<ClientFacingBloodOxygenTimeseries>> bloodOxygen(
            String userId, BloodOxygenVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient.bloodOxygen(userId, request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<List<ClientFacingElectrocardiogramVoltageTimeseries>> electrocardiogramVoltage(
            String userId, ElectrocardiogramVoltageVitalsRequest request) {
        return this.rawClient.electrocardiogramVoltage(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<List<ClientFacingElectrocardiogramVoltageTimeseries>> electrocardiogramVoltage(
            String userId, ElectrocardiogramVoltageVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .electrocardiogramVoltage(userId, request, requestOptions)
                .thenApply(response -> response.body());
    }

    public CompletableFuture<List<ClientFacingBloodPressureTimeseries>> bloodPressure(
            String userId, BloodPressureVitalsRequest request) {
        return this.rawClient.bloodPressure(userId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<List<ClientFacingBloodPressureTimeseries>> bloodPressure(
            String userId, BloodPressureVitalsRequest request, RequestOptions requestOptions) {
        return this.rawClient.bloodPressure(userId, request, requestOptions).thenApply(response -> response.body());
    }
}
