/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.junction.api.core;

/**
 * This class serves as the base exception for all errors in the SDK.
 */
public class JunctionException extends RuntimeException {
    public JunctionException(String message) {
        super(message);
    }

    public JunctionException(String message, Exception e) {
        super(message, e);
    }
}
