/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.junction.api.resources.workouts;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.junction.api.core.ApiError;
import com.junction.api.core.ClientOptions;
import com.junction.api.core.JunctionException;
import com.junction.api.core.JunctionHttpResponse;
import com.junction.api.core.ObjectMappers;
import com.junction.api.core.QueryStringMapper;
import com.junction.api.core.RequestOptions;
import com.junction.api.errors.UnprocessableEntityError;
import com.junction.api.resources.workouts.requests.GetByWorkoutIdWorkoutsRequest;
import com.junction.api.resources.workouts.requests.GetRawWorkoutsRequest;
import com.junction.api.resources.workouts.requests.GetWorkoutsRequest;
import com.junction.api.types.ClientFacingStream;
import com.junction.api.types.ClientWorkoutResponse;
import com.junction.api.types.HttpValidationError;
import com.junction.api.types.RawWorkoutResponse;
import java.io.IOException;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;
import okhttp3.ResponseBody;

public class RawWorkoutsClient {
    protected final ClientOptions clientOptions;

    public RawWorkoutsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    /**
     * Get workout summary for user_id
     */
    public JunctionHttpResponse<ClientWorkoutResponse> get(String userId, GetWorkoutsRequest request) {
        return get(userId, request, null);
    }

    /**
     * Get workout summary for user_id
     */
    public JunctionHttpResponse<ClientWorkoutResponse> get(
            String userId, GetWorkoutsRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("v2/summary/workouts")
                .addPathSegment(userId);
        if (request.getProvider().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "provider", request.getProvider().get(), false);
        }
        QueryStringMapper.addQueryParameter(httpUrl, "start_date", request.getStartDate(), false);
        if (request.getEndDate().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "end_date", request.getEndDate().get(), false);
        }
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new JunctionHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ClientWorkoutResponse.class), response);
            }
            try {
                if (response.code() == 422) {
                    throw new UnprocessableEntityError(
                            ObjectMappers.JSON_MAPPER.readValue(responseBodyString, HttpValidationError.class),
                            response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new ApiError("Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new JunctionException("Network error executing HTTP request", e);
        }
    }

    /**
     * Get raw workout summary for user_id
     */
    public JunctionHttpResponse<RawWorkoutResponse> getRaw(String userId, GetRawWorkoutsRequest request) {
        return getRaw(userId, request, null);
    }

    /**
     * Get raw workout summary for user_id
     */
    public JunctionHttpResponse<RawWorkoutResponse> getRaw(
            String userId, GetRawWorkoutsRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("v2/summary/workouts")
                .addPathSegment(userId)
                .addPathSegments("raw");
        if (request.getProvider().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "provider", request.getProvider().get(), false);
        }
        QueryStringMapper.addQueryParameter(httpUrl, "start_date", request.getStartDate(), false);
        if (request.getEndDate().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "end_date", request.getEndDate().get(), false);
        }
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new JunctionHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, RawWorkoutResponse.class), response);
            }
            try {
                if (response.code() == 422) {
                    throw new UnprocessableEntityError(
                            ObjectMappers.JSON_MAPPER.readValue(responseBodyString, HttpValidationError.class),
                            response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new ApiError("Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new JunctionException("Network error executing HTTP request", e);
        }
    }

    public JunctionHttpResponse<ClientFacingStream> getByWorkoutId(String workoutId) {
        return getByWorkoutId(workoutId, GetByWorkoutIdWorkoutsRequest.builder().build());
    }

    public JunctionHttpResponse<ClientFacingStream> getByWorkoutId(String workoutId, RequestOptions requestOptions) {
        return getByWorkoutId(workoutId, GetByWorkoutIdWorkoutsRequest.builder().build(), requestOptions);
    }

    public JunctionHttpResponse<ClientFacingStream> getByWorkoutId(
            String workoutId, GetByWorkoutIdWorkoutsRequest request) {
        return getByWorkoutId(workoutId, request, null);
    }

    public JunctionHttpResponse<ClientFacingStream> getByWorkoutId(
            String workoutId, GetByWorkoutIdWorkoutsRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("v2/timeseries/workouts")
                .addPathSegment(workoutId)
                .addPathSegments("stream");
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new JunctionHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ClientFacingStream.class), response);
            }
            try {
                if (response.code() == 422) {
                    throw new UnprocessableEntityError(
                            ObjectMappers.JSON_MAPPER.readValue(responseBodyString, HttpValidationError.class),
                            response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new ApiError("Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new JunctionException("Network error executing HTTP request", e);
        }
    }
}
