/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.junction.api.resources.body;

import com.junction.api.core.ClientOptions;
import com.junction.api.core.RequestOptions;
import com.junction.api.resources.body.requests.GetBodyRequest;
import com.junction.api.resources.body.requests.GetRawBodyRequest;
import com.junction.api.types.ClientBodyResponse;
import com.junction.api.types.RawBodyResponse;

public class BodyClient {
    protected final ClientOptions clientOptions;

    private final RawBodyClient rawClient;

    public BodyClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawBodyClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawBodyClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Get Body summary for user_id
     */
    public ClientBodyResponse get(String userId, GetBodyRequest request) {
        return this.rawClient.get(userId, request).body();
    }

    /**
     * Get Body summary for user_id
     */
    public ClientBodyResponse get(String userId, GetBodyRequest request, RequestOptions requestOptions) {
        return this.rawClient.get(userId, request, requestOptions).body();
    }

    /**
     * Get raw Body summary for user_id
     */
    public RawBodyResponse getRaw(String userId, GetRawBodyRequest request) {
        return this.rawClient.getRaw(userId, request).body();
    }

    /**
     * Get raw Body summary for user_id
     */
    public RawBodyResponse getRaw(String userId, GetRawBodyRequest request, RequestOptions requestOptions) {
        return this.rawClient.getRaw(userId, request, requestOptions).body();
    }
}
