/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.junction.api.resources.labtests.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.junction.api.core.Nullable;
import com.junction.api.core.NullableNonemptyFilter;
import com.junction.api.core.ObjectMappers;
import com.junction.api.types.UnmatchedResultUpdateStatus;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CreateUnmatchedResultUpdateBody.Builder.class)
public final class CreateUnmatchedResultUpdateBody {
    private final Optional<String> note;

    private final Optional<UnmatchedResultUpdateStatus> status;

    private final Map<String, Object> additionalProperties;

    private CreateUnmatchedResultUpdateBody(
            Optional<String> note,
            Optional<UnmatchedResultUpdateStatus> status,
            Map<String, Object> additionalProperties) {
        this.note = note;
        this.status = status;
        this.additionalProperties = additionalProperties;
    }

    @JsonIgnore
    public Optional<String> getNote() {
        if (note == null) {
            return Optional.empty();
        }
        return note;
    }

    /**
     * @return ℹ️ This enum is non-exhaustive.
     */
    @JsonIgnore
    public Optional<UnmatchedResultUpdateStatus> getStatus() {
        if (status == null) {
            return Optional.empty();
        }
        return status;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("note")
    private Optional<String> _getNote() {
        return note;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("status")
    private Optional<UnmatchedResultUpdateStatus> _getStatus() {
        return status;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CreateUnmatchedResultUpdateBody && equalTo((CreateUnmatchedResultUpdateBody) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CreateUnmatchedResultUpdateBody other) {
        return note.equals(other.note) && status.equals(other.status);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.note, this.status);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> note = Optional.empty();

        private Optional<UnmatchedResultUpdateStatus> status = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(CreateUnmatchedResultUpdateBody other) {
            note(other.getNote());
            status(other.getStatus());
            return this;
        }

        @JsonSetter(value = "note", nulls = Nulls.SKIP)
        public Builder note(Optional<String> note) {
            this.note = note;
            return this;
        }

        public Builder note(String note) {
            this.note = Optional.ofNullable(note);
            return this;
        }

        public Builder note(Nullable<String> note) {
            if (note.isNull()) {
                this.note = null;
            } else if (note.isEmpty()) {
                this.note = Optional.empty();
            } else {
                this.note = Optional.of(note.get());
            }
            return this;
        }

        /**
         * <p>ℹ️ This enum is non-exhaustive.</p>
         */
        @JsonSetter(value = "status", nulls = Nulls.SKIP)
        public Builder status(Optional<UnmatchedResultUpdateStatus> status) {
            this.status = status;
            return this;
        }

        public Builder status(UnmatchedResultUpdateStatus status) {
            this.status = Optional.ofNullable(status);
            return this;
        }

        public Builder status(Nullable<UnmatchedResultUpdateStatus> status) {
            if (status.isNull()) {
                this.status = null;
            } else if (status.isEmpty()) {
                this.status = Optional.empty();
            } else {
                this.status = Optional.of(status.get());
            }
            return this;
        }

        public CreateUnmatchedResultUpdateBody build() {
            return new CreateUnmatchedResultUpdateBody(note, status, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
