/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.junction.api.resources.labtests.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.junction.api.core.Nullable;
import com.junction.api.core.ObjectMappers;
import com.junction.api.resources.labtests.types.GetLabTestsRequestOrderDirection;
import com.junction.api.resources.labtests.types.GetLabTestsRequestOrderKey;
import com.junction.api.types.LabTestCollectionMethod;
import com.junction.api.types.LabTestGenerationMethodFilter;
import com.junction.api.types.LabTestStatus;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = GetLabTestsRequest.Builder.class)
public final class GetLabTestsRequest {
    private final Optional<List<Integer>> markerIds;

    private final Optional<List<String>> providerIds;

    private final Optional<LabTestGenerationMethodFilter> generationMethod;

    private final Optional<String> labSlug;

    private final Optional<LabTestCollectionMethod> collectionMethod;

    private final Optional<LabTestStatus> status;

    private final Optional<String> name;

    private final Optional<GetLabTestsRequestOrderKey> orderKey;

    private final Optional<GetLabTestsRequestOrderDirection> orderDirection;

    private final Map<String, Object> additionalProperties;

    private GetLabTestsRequest(
            Optional<List<Integer>> markerIds,
            Optional<List<String>> providerIds,
            Optional<LabTestGenerationMethodFilter> generationMethod,
            Optional<String> labSlug,
            Optional<LabTestCollectionMethod> collectionMethod,
            Optional<LabTestStatus> status,
            Optional<String> name,
            Optional<GetLabTestsRequestOrderKey> orderKey,
            Optional<GetLabTestsRequestOrderDirection> orderDirection,
            Map<String, Object> additionalProperties) {
        this.markerIds = markerIds;
        this.providerIds = providerIds;
        this.generationMethod = generationMethod;
        this.labSlug = labSlug;
        this.collectionMethod = collectionMethod;
        this.status = status;
        this.name = name;
        this.orderKey = orderKey;
        this.orderDirection = orderDirection;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Filter to only include lab tests containing these marker IDs.
     */
    @JsonIgnore
    public Optional<List<Integer>> getMarkerIds() {
        if (markerIds == null) {
            return Optional.empty();
        }
        return markerIds;
    }

    /**
     * @return Filter to only include lab tests containing these provider IDs.
     */
    @JsonIgnore
    public Optional<List<String>> getProviderIds() {
        if (providerIds == null) {
            return Optional.empty();
        }
        return providerIds;
    }

    /**
     * @return Filter on whether auto-generated lab tests created by Vital, manually created lab tests, or all lab tests should be returned.
     */
    @JsonIgnore
    public Optional<LabTestGenerationMethodFilter> getGenerationMethod() {
        if (generationMethod == null) {
            return Optional.empty();
        }
        return generationMethod;
    }

    /**
     * @return Filter by the slug of the lab for these lab tests.
     */
    @JsonIgnore
    public Optional<String> getLabSlug() {
        if (labSlug == null) {
            return Optional.empty();
        }
        return labSlug;
    }

    /**
     * @return Filter by the collection method for these lab tests.
     */
    @JsonIgnore
    public Optional<LabTestCollectionMethod> getCollectionMethod() {
        if (collectionMethod == null) {
            return Optional.empty();
        }
        return collectionMethod;
    }

    /**
     * @return Filter by the status of these lab tests.
     */
    @JsonIgnore
    public Optional<LabTestStatus> getStatus() {
        if (status == null) {
            return Optional.empty();
        }
        return status;
    }

    /**
     * @return Filter by the name of the lab test (a case-insensitive substring search).
     */
    @JsonIgnore
    public Optional<String> getName() {
        if (name == null) {
            return Optional.empty();
        }
        return name;
    }

    @JsonIgnore
    public Optional<GetLabTestsRequestOrderKey> getOrderKey() {
        if (orderKey == null) {
            return Optional.empty();
        }
        return orderKey;
    }

    @JsonIgnore
    public Optional<GetLabTestsRequestOrderDirection> getOrderDirection() {
        if (orderDirection == null) {
            return Optional.empty();
        }
        return orderDirection;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof GetLabTestsRequest && equalTo((GetLabTestsRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(GetLabTestsRequest other) {
        return markerIds.equals(other.markerIds)
                && providerIds.equals(other.providerIds)
                && generationMethod.equals(other.generationMethod)
                && labSlug.equals(other.labSlug)
                && collectionMethod.equals(other.collectionMethod)
                && status.equals(other.status)
                && name.equals(other.name)
                && orderKey.equals(other.orderKey)
                && orderDirection.equals(other.orderDirection);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.markerIds,
                this.providerIds,
                this.generationMethod,
                this.labSlug,
                this.collectionMethod,
                this.status,
                this.name,
                this.orderKey,
                this.orderDirection);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<List<Integer>> markerIds = Optional.empty();

        private Optional<List<String>> providerIds = Optional.empty();

        private Optional<LabTestGenerationMethodFilter> generationMethod = Optional.empty();

        private Optional<String> labSlug = Optional.empty();

        private Optional<LabTestCollectionMethod> collectionMethod = Optional.empty();

        private Optional<LabTestStatus> status = Optional.empty();

        private Optional<String> name = Optional.empty();

        private Optional<GetLabTestsRequestOrderKey> orderKey = Optional.empty();

        private Optional<GetLabTestsRequestOrderDirection> orderDirection = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(GetLabTestsRequest other) {
            markerIds(other.getMarkerIds());
            providerIds(other.getProviderIds());
            generationMethod(other.getGenerationMethod());
            labSlug(other.getLabSlug());
            collectionMethod(other.getCollectionMethod());
            status(other.getStatus());
            name(other.getName());
            orderKey(other.getOrderKey());
            orderDirection(other.getOrderDirection());
            return this;
        }

        /**
         * <p>Filter to only include lab tests containing these marker IDs.</p>
         */
        @JsonSetter(value = "marker_ids", nulls = Nulls.SKIP)
        public Builder markerIds(Optional<List<Integer>> markerIds) {
            this.markerIds = markerIds;
            return this;
        }

        public Builder markerIds(List<Integer> markerIds) {
            this.markerIds = Optional.ofNullable(markerIds);
            return this;
        }

        public Builder markerIds(Nullable<List<Integer>> markerIds) {
            if (markerIds.isNull()) {
                this.markerIds = null;
            } else if (markerIds.isEmpty()) {
                this.markerIds = Optional.empty();
            } else {
                this.markerIds = Optional.of(markerIds.get());
            }
            return this;
        }

        public Builder markerIds(Integer markerIds) {
            this.markerIds = Optional.of(Collections.singletonList(markerIds));
            return this;
        }

        /**
         * <p>Filter to only include lab tests containing these provider IDs.</p>
         */
        @JsonSetter(value = "provider_ids", nulls = Nulls.SKIP)
        public Builder providerIds(Optional<List<String>> providerIds) {
            this.providerIds = providerIds;
            return this;
        }

        public Builder providerIds(List<String> providerIds) {
            this.providerIds = Optional.ofNullable(providerIds);
            return this;
        }

        public Builder providerIds(Nullable<List<String>> providerIds) {
            if (providerIds.isNull()) {
                this.providerIds = null;
            } else if (providerIds.isEmpty()) {
                this.providerIds = Optional.empty();
            } else {
                this.providerIds = Optional.of(providerIds.get());
            }
            return this;
        }

        public Builder providerIds(String providerIds) {
            this.providerIds = Optional.of(Collections.singletonList(providerIds));
            return this;
        }

        /**
         * <p>Filter on whether auto-generated lab tests created by Vital, manually created lab tests, or all lab tests should be returned.</p>
         */
        @JsonSetter(value = "generation_method", nulls = Nulls.SKIP)
        public Builder generationMethod(Optional<LabTestGenerationMethodFilter> generationMethod) {
            this.generationMethod = generationMethod;
            return this;
        }

        public Builder generationMethod(LabTestGenerationMethodFilter generationMethod) {
            this.generationMethod = Optional.ofNullable(generationMethod);
            return this;
        }

        public Builder generationMethod(Nullable<LabTestGenerationMethodFilter> generationMethod) {
            if (generationMethod.isNull()) {
                this.generationMethod = null;
            } else if (generationMethod.isEmpty()) {
                this.generationMethod = Optional.empty();
            } else {
                this.generationMethod = Optional.of(generationMethod.get());
            }
            return this;
        }

        /**
         * <p>Filter by the slug of the lab for these lab tests.</p>
         */
        @JsonSetter(value = "lab_slug", nulls = Nulls.SKIP)
        public Builder labSlug(Optional<String> labSlug) {
            this.labSlug = labSlug;
            return this;
        }

        public Builder labSlug(String labSlug) {
            this.labSlug = Optional.ofNullable(labSlug);
            return this;
        }

        public Builder labSlug(Nullable<String> labSlug) {
            if (labSlug.isNull()) {
                this.labSlug = null;
            } else if (labSlug.isEmpty()) {
                this.labSlug = Optional.empty();
            } else {
                this.labSlug = Optional.of(labSlug.get());
            }
            return this;
        }

        /**
         * <p>Filter by the collection method for these lab tests.</p>
         */
        @JsonSetter(value = "collection_method", nulls = Nulls.SKIP)
        public Builder collectionMethod(Optional<LabTestCollectionMethod> collectionMethod) {
            this.collectionMethod = collectionMethod;
            return this;
        }

        public Builder collectionMethod(LabTestCollectionMethod collectionMethod) {
            this.collectionMethod = Optional.ofNullable(collectionMethod);
            return this;
        }

        public Builder collectionMethod(Nullable<LabTestCollectionMethod> collectionMethod) {
            if (collectionMethod.isNull()) {
                this.collectionMethod = null;
            } else if (collectionMethod.isEmpty()) {
                this.collectionMethod = Optional.empty();
            } else {
                this.collectionMethod = Optional.of(collectionMethod.get());
            }
            return this;
        }

        /**
         * <p>Filter by the status of these lab tests.</p>
         */
        @JsonSetter(value = "status", nulls = Nulls.SKIP)
        public Builder status(Optional<LabTestStatus> status) {
            this.status = status;
            return this;
        }

        public Builder status(LabTestStatus status) {
            this.status = Optional.ofNullable(status);
            return this;
        }

        public Builder status(Nullable<LabTestStatus> status) {
            if (status.isNull()) {
                this.status = null;
            } else if (status.isEmpty()) {
                this.status = Optional.empty();
            } else {
                this.status = Optional.of(status.get());
            }
            return this;
        }

        /**
         * <p>Filter by the name of the lab test (a case-insensitive substring search).</p>
         */
        @JsonSetter(value = "name", nulls = Nulls.SKIP)
        public Builder name(Optional<String> name) {
            this.name = name;
            return this;
        }

        public Builder name(String name) {
            this.name = Optional.ofNullable(name);
            return this;
        }

        public Builder name(Nullable<String> name) {
            if (name.isNull()) {
                this.name = null;
            } else if (name.isEmpty()) {
                this.name = Optional.empty();
            } else {
                this.name = Optional.of(name.get());
            }
            return this;
        }

        @JsonSetter(value = "order_key", nulls = Nulls.SKIP)
        public Builder orderKey(Optional<GetLabTestsRequestOrderKey> orderKey) {
            this.orderKey = orderKey;
            return this;
        }

        public Builder orderKey(GetLabTestsRequestOrderKey orderKey) {
            this.orderKey = Optional.ofNullable(orderKey);
            return this;
        }

        public Builder orderKey(Nullable<GetLabTestsRequestOrderKey> orderKey) {
            if (orderKey.isNull()) {
                this.orderKey = null;
            } else if (orderKey.isEmpty()) {
                this.orderKey = Optional.empty();
            } else {
                this.orderKey = Optional.of(orderKey.get());
            }
            return this;
        }

        @JsonSetter(value = "order_direction", nulls = Nulls.SKIP)
        public Builder orderDirection(Optional<GetLabTestsRequestOrderDirection> orderDirection) {
            this.orderDirection = orderDirection;
            return this;
        }

        public Builder orderDirection(GetLabTestsRequestOrderDirection orderDirection) {
            this.orderDirection = Optional.ofNullable(orderDirection);
            return this;
        }

        public Builder orderDirection(Nullable<GetLabTestsRequestOrderDirection> orderDirection) {
            if (orderDirection.isNull()) {
                this.orderDirection = null;
            } else if (orderDirection.isEmpty()) {
                this.orderDirection = Optional.empty();
            } else {
                this.orderDirection = Optional.of(orderDirection.get());
            }
            return this;
        }

        public GetLabTestsRequest build() {
            return new GetLabTestsRequest(
                    markerIds,
                    providerIds,
                    generationMethod,
                    labSlug,
                    collectionMethod,
                    status,
                    name,
                    orderKey,
                    orderDirection,
                    additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
