/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.junction.api.resources.labtests.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.junction.api.core.Nullable;
import com.junction.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = GetMarkersForLabTestLabTestsRequest.Builder.class)
public final class GetMarkersForLabTestLabTestsRequest {
    private final Optional<String> labAccountId;

    private final Optional<Integer> page;

    private final Optional<Integer> size;

    private final Map<String, Object> additionalProperties;

    private GetMarkersForLabTestLabTestsRequest(
            Optional<String> labAccountId,
            Optional<Integer> page,
            Optional<Integer> size,
            Map<String, Object> additionalProperties) {
        this.labAccountId = labAccountId;
        this.page = page;
        this.size = size;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The lab account ID. This lab account is used to determine the availability of markers and lab tests.
     */
    @JsonIgnore
    public Optional<String> getLabAccountId() {
        if (labAccountId == null) {
            return Optional.empty();
        }
        return labAccountId;
    }

    @JsonIgnore
    public Optional<Integer> getPage() {
        if (page == null) {
            return Optional.empty();
        }
        return page;
    }

    @JsonIgnore
    public Optional<Integer> getSize() {
        if (size == null) {
            return Optional.empty();
        }
        return size;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof GetMarkersForLabTestLabTestsRequest
                && equalTo((GetMarkersForLabTestLabTestsRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(GetMarkersForLabTestLabTestsRequest other) {
        return labAccountId.equals(other.labAccountId) && page.equals(other.page) && size.equals(other.size);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.labAccountId, this.page, this.size);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> labAccountId = Optional.empty();

        private Optional<Integer> page = Optional.empty();

        private Optional<Integer> size = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(GetMarkersForLabTestLabTestsRequest other) {
            labAccountId(other.getLabAccountId());
            page(other.getPage());
            size(other.getSize());
            return this;
        }

        /**
         * <p>The lab account ID. This lab account is used to determine the availability of markers and lab tests.</p>
         */
        @JsonSetter(value = "lab_account_id", nulls = Nulls.SKIP)
        public Builder labAccountId(Optional<String> labAccountId) {
            this.labAccountId = labAccountId;
            return this;
        }

        public Builder labAccountId(String labAccountId) {
            this.labAccountId = Optional.ofNullable(labAccountId);
            return this;
        }

        public Builder labAccountId(Nullable<String> labAccountId) {
            if (labAccountId.isNull()) {
                this.labAccountId = null;
            } else if (labAccountId.isEmpty()) {
                this.labAccountId = Optional.empty();
            } else {
                this.labAccountId = Optional.of(labAccountId.get());
            }
            return this;
        }

        @JsonSetter(value = "page", nulls = Nulls.SKIP)
        public Builder page(Optional<Integer> page) {
            this.page = page;
            return this;
        }

        public Builder page(Integer page) {
            this.page = Optional.ofNullable(page);
            return this;
        }

        public Builder page(Nullable<Integer> page) {
            if (page.isNull()) {
                this.page = null;
            } else if (page.isEmpty()) {
                this.page = Optional.empty();
            } else {
                this.page = Optional.of(page.get());
            }
            return this;
        }

        @JsonSetter(value = "size", nulls = Nulls.SKIP)
        public Builder size(Optional<Integer> size) {
            this.size = size;
            return this;
        }

        public Builder size(Integer size) {
            this.size = Optional.ofNullable(size);
            return this;
        }

        public Builder size(Nullable<Integer> size) {
            if (size.isNull()) {
                this.size = null;
            } else if (size.isEmpty()) {
                this.size = Optional.empty();
            } else {
                this.size = Optional.of(size.get());
            }
            return this;
        }

        public GetMarkersForLabTestLabTestsRequest build() {
            return new GetMarkersForLabTestLabTestsRequest(labAccountId, page, size, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
