/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.junction.api.resources.labtests.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.junction.api.core.Nullable;
import com.junction.api.core.ObjectMappers;
import com.junction.api.resources.labtests.types.GetOrdersLabTestsRequestOrderDirection;
import com.junction.api.resources.labtests.types.GetOrdersLabTestsRequestOrderKey;
import com.junction.api.types.Interpretation;
import com.junction.api.types.LabTestCollectionMethod;
import com.junction.api.types.OrderActivationType;
import com.junction.api.types.OrderLowLevelStatus;
import java.time.OffsetDateTime;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = GetOrdersLabTestsRequest.Builder.class)
public final class GetOrdersLabTestsRequest {
    private final Optional<List<OrderLowLevelStatus>> status;

    private final Optional<List<LabTestCollectionMethod>> orderType;

    private final Optional<List<OrderActivationType>> orderActivationTypes;

    private final Optional<List<String>> orderIds;

    private final Optional<String> searchInput;

    private final Optional<OffsetDateTime> startDate;

    private final Optional<OffsetDateTime> endDate;

    private final Optional<OffsetDateTime> updatedStartDate;

    private final Optional<OffsetDateTime> updatedEndDate;

    private final Optional<GetOrdersLabTestsRequestOrderKey> orderKey;

    private final Optional<GetOrdersLabTestsRequestOrderDirection> orderDirection;

    private final Optional<Boolean> isCritical;

    private final Optional<Interpretation> interpretation;

    private final Optional<String> userId;

    private final Optional<String> patientName;

    private final Optional<String> shippingRecipientName;

    private final Optional<String> orderTransactionId;

    private final Optional<Integer> page;

    private final Optional<Integer> size;

    private final Map<String, Object> additionalProperties;

    private GetOrdersLabTestsRequest(
            Optional<List<OrderLowLevelStatus>> status,
            Optional<List<LabTestCollectionMethod>> orderType,
            Optional<List<OrderActivationType>> orderActivationTypes,
            Optional<List<String>> orderIds,
            Optional<String> searchInput,
            Optional<OffsetDateTime> startDate,
            Optional<OffsetDateTime> endDate,
            Optional<OffsetDateTime> updatedStartDate,
            Optional<OffsetDateTime> updatedEndDate,
            Optional<GetOrdersLabTestsRequestOrderKey> orderKey,
            Optional<GetOrdersLabTestsRequestOrderDirection> orderDirection,
            Optional<Boolean> isCritical,
            Optional<Interpretation> interpretation,
            Optional<String> userId,
            Optional<String> patientName,
            Optional<String> shippingRecipientName,
            Optional<String> orderTransactionId,
            Optional<Integer> page,
            Optional<Integer> size,
            Map<String, Object> additionalProperties) {
        this.status = status;
        this.orderType = orderType;
        this.orderActivationTypes = orderActivationTypes;
        this.orderIds = orderIds;
        this.searchInput = searchInput;
        this.startDate = startDate;
        this.endDate = endDate;
        this.updatedStartDate = updatedStartDate;
        this.updatedEndDate = updatedEndDate;
        this.orderKey = orderKey;
        this.orderDirection = orderDirection;
        this.isCritical = isCritical;
        this.interpretation = interpretation;
        this.userId = userId;
        this.patientName = patientName;
        this.shippingRecipientName = shippingRecipientName;
        this.orderTransactionId = orderTransactionId;
        this.page = page;
        this.size = size;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Filter by low level status.
     */
    @JsonIgnore
    public Optional<List<OrderLowLevelStatus>> getStatus() {
        if (status == null) {
            return Optional.empty();
        }
        return status;
    }

    /**
     * @return Filter by method used to perform the lab test.
     */
    @JsonIgnore
    public Optional<List<LabTestCollectionMethod>> getOrderType() {
        if (orderType == null) {
            return Optional.empty();
        }
        return orderType;
    }

    /**
     * @return Filter by activation type.
     */
    @JsonIgnore
    public Optional<List<OrderActivationType>> getOrderActivationTypes() {
        if (orderActivationTypes == null) {
            return Optional.empty();
        }
        return orderActivationTypes;
    }

    /**
     * @return Filter by order ids.
     */
    @JsonIgnore
    public Optional<List<String>> getOrderIds() {
        if (orderIds == null) {
            return Optional.empty();
        }
        return orderIds;
    }

    /**
     * @return Search by order id, user id, patient name, shipping dob, or shipping recipient name.
     */
    @JsonIgnore
    public Optional<String> getSearchInput() {
        if (searchInput == null) {
            return Optional.empty();
        }
        return searchInput;
    }

    /**
     * @return Date from in YYYY-MM-DD or ISO formatted date time. If a date is provided without a time, the time will be set to 00:00:00
     */
    @JsonIgnore
    public Optional<OffsetDateTime> getStartDate() {
        if (startDate == null) {
            return Optional.empty();
        }
        return startDate;
    }

    /**
     * @return Date to YYYY-MM-DD or ISO formatted date time. If a date is provided without a time, the time will be set to 23:59:59
     */
    @JsonIgnore
    public Optional<OffsetDateTime> getEndDate() {
        if (endDate == null) {
            return Optional.empty();
        }
        return endDate;
    }

    /**
     * @return Date from in YYYY-MM-DD or ISO formatted date time. If a date is provided without a time, the time will be set to 00:00:00
     */
    @JsonIgnore
    public Optional<OffsetDateTime> getUpdatedStartDate() {
        if (updatedStartDate == null) {
            return Optional.empty();
        }
        return updatedStartDate;
    }

    /**
     * @return Date to YYYY-MM-DD or ISO formatted date time. If a date is provided without a time, the time will be set to 00:00:00
     */
    @JsonIgnore
    public Optional<OffsetDateTime> getUpdatedEndDate() {
        if (updatedEndDate == null) {
            return Optional.empty();
        }
        return updatedEndDate;
    }

    /**
     * @return Order key to sort by.
     */
    @JsonIgnore
    public Optional<GetOrdersLabTestsRequestOrderKey> getOrderKey() {
        if (orderKey == null) {
            return Optional.empty();
        }
        return orderKey;
    }

    /**
     * @return Order direction to sort by.
     */
    @JsonIgnore
    public Optional<GetOrdersLabTestsRequestOrderDirection> getOrderDirection() {
        if (orderDirection == null) {
            return Optional.empty();
        }
        return orderDirection;
    }

    /**
     * @return Filter by critical order status.
     */
    @JsonIgnore
    public Optional<Boolean> getIsCritical() {
        if (isCritical == null) {
            return Optional.empty();
        }
        return isCritical;
    }

    /**
     * @return Filter by result interpretation of the lab test.
     */
    @JsonIgnore
    public Optional<Interpretation> getInterpretation() {
        if (interpretation == null) {
            return Optional.empty();
        }
        return interpretation;
    }

    /**
     * @return Filter by user ID.
     */
    @JsonIgnore
    public Optional<String> getUserId() {
        if (userId == null) {
            return Optional.empty();
        }
        return userId;
    }

    /**
     * @return Filter by patient name.
     */
    @JsonIgnore
    public Optional<String> getPatientName() {
        if (patientName == null) {
            return Optional.empty();
        }
        return patientName;
    }

    /**
     * @return Filter by shipping recipient name.
     */
    @JsonIgnore
    public Optional<String> getShippingRecipientName() {
        if (shippingRecipientName == null) {
            return Optional.empty();
        }
        return shippingRecipientName;
    }

    /**
     * @return Filter by order transaction ID
     */
    @JsonIgnore
    public Optional<String> getOrderTransactionId() {
        if (orderTransactionId == null) {
            return Optional.empty();
        }
        return orderTransactionId;
    }

    @JsonIgnore
    public Optional<Integer> getPage() {
        if (page == null) {
            return Optional.empty();
        }
        return page;
    }

    @JsonIgnore
    public Optional<Integer> getSize() {
        if (size == null) {
            return Optional.empty();
        }
        return size;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof GetOrdersLabTestsRequest && equalTo((GetOrdersLabTestsRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(GetOrdersLabTestsRequest other) {
        return status.equals(other.status)
                && orderType.equals(other.orderType)
                && orderActivationTypes.equals(other.orderActivationTypes)
                && orderIds.equals(other.orderIds)
                && searchInput.equals(other.searchInput)
                && startDate.equals(other.startDate)
                && endDate.equals(other.endDate)
                && updatedStartDate.equals(other.updatedStartDate)
                && updatedEndDate.equals(other.updatedEndDate)
                && orderKey.equals(other.orderKey)
                && orderDirection.equals(other.orderDirection)
                && isCritical.equals(other.isCritical)
                && interpretation.equals(other.interpretation)
                && userId.equals(other.userId)
                && patientName.equals(other.patientName)
                && shippingRecipientName.equals(other.shippingRecipientName)
                && orderTransactionId.equals(other.orderTransactionId)
                && page.equals(other.page)
                && size.equals(other.size);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.status,
                this.orderType,
                this.orderActivationTypes,
                this.orderIds,
                this.searchInput,
                this.startDate,
                this.endDate,
                this.updatedStartDate,
                this.updatedEndDate,
                this.orderKey,
                this.orderDirection,
                this.isCritical,
                this.interpretation,
                this.userId,
                this.patientName,
                this.shippingRecipientName,
                this.orderTransactionId,
                this.page,
                this.size);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<List<OrderLowLevelStatus>> status = Optional.empty();

        private Optional<List<LabTestCollectionMethod>> orderType = Optional.empty();

        private Optional<List<OrderActivationType>> orderActivationTypes = Optional.empty();

        private Optional<List<String>> orderIds = Optional.empty();

        private Optional<String> searchInput = Optional.empty();

        private Optional<OffsetDateTime> startDate = Optional.empty();

        private Optional<OffsetDateTime> endDate = Optional.empty();

        private Optional<OffsetDateTime> updatedStartDate = Optional.empty();

        private Optional<OffsetDateTime> updatedEndDate = Optional.empty();

        private Optional<GetOrdersLabTestsRequestOrderKey> orderKey = Optional.empty();

        private Optional<GetOrdersLabTestsRequestOrderDirection> orderDirection = Optional.empty();

        private Optional<Boolean> isCritical = Optional.empty();

        private Optional<Interpretation> interpretation = Optional.empty();

        private Optional<String> userId = Optional.empty();

        private Optional<String> patientName = Optional.empty();

        private Optional<String> shippingRecipientName = Optional.empty();

        private Optional<String> orderTransactionId = Optional.empty();

        private Optional<Integer> page = Optional.empty();

        private Optional<Integer> size = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(GetOrdersLabTestsRequest other) {
            status(other.getStatus());
            orderType(other.getOrderType());
            orderActivationTypes(other.getOrderActivationTypes());
            orderIds(other.getOrderIds());
            searchInput(other.getSearchInput());
            startDate(other.getStartDate());
            endDate(other.getEndDate());
            updatedStartDate(other.getUpdatedStartDate());
            updatedEndDate(other.getUpdatedEndDate());
            orderKey(other.getOrderKey());
            orderDirection(other.getOrderDirection());
            isCritical(other.getIsCritical());
            interpretation(other.getInterpretation());
            userId(other.getUserId());
            patientName(other.getPatientName());
            shippingRecipientName(other.getShippingRecipientName());
            orderTransactionId(other.getOrderTransactionId());
            page(other.getPage());
            size(other.getSize());
            return this;
        }

        /**
         * <p>Filter by low level status.</p>
         */
        @JsonSetter(value = "status", nulls = Nulls.SKIP)
        public Builder status(Optional<List<OrderLowLevelStatus>> status) {
            this.status = status;
            return this;
        }

        public Builder status(List<OrderLowLevelStatus> status) {
            this.status = Optional.ofNullable(status);
            return this;
        }

        public Builder status(Nullable<List<OrderLowLevelStatus>> status) {
            if (status.isNull()) {
                this.status = null;
            } else if (status.isEmpty()) {
                this.status = Optional.empty();
            } else {
                this.status = Optional.of(status.get());
            }
            return this;
        }

        public Builder status(OrderLowLevelStatus status) {
            this.status = Optional.of(Collections.singletonList(status));
            return this;
        }

        /**
         * <p>Filter by method used to perform the lab test.</p>
         */
        @JsonSetter(value = "order_type", nulls = Nulls.SKIP)
        public Builder orderType(Optional<List<LabTestCollectionMethod>> orderType) {
            this.orderType = orderType;
            return this;
        }

        public Builder orderType(List<LabTestCollectionMethod> orderType) {
            this.orderType = Optional.ofNullable(orderType);
            return this;
        }

        public Builder orderType(Nullable<List<LabTestCollectionMethod>> orderType) {
            if (orderType.isNull()) {
                this.orderType = null;
            } else if (orderType.isEmpty()) {
                this.orderType = Optional.empty();
            } else {
                this.orderType = Optional.of(orderType.get());
            }
            return this;
        }

        public Builder orderType(LabTestCollectionMethod orderType) {
            this.orderType = Optional.of(Collections.singletonList(orderType));
            return this;
        }

        /**
         * <p>Filter by activation type.</p>
         */
        @JsonSetter(value = "order_activation_types", nulls = Nulls.SKIP)
        public Builder orderActivationTypes(Optional<List<OrderActivationType>> orderActivationTypes) {
            this.orderActivationTypes = orderActivationTypes;
            return this;
        }

        public Builder orderActivationTypes(List<OrderActivationType> orderActivationTypes) {
            this.orderActivationTypes = Optional.ofNullable(orderActivationTypes);
            return this;
        }

        public Builder orderActivationTypes(Nullable<List<OrderActivationType>> orderActivationTypes) {
            if (orderActivationTypes.isNull()) {
                this.orderActivationTypes = null;
            } else if (orderActivationTypes.isEmpty()) {
                this.orderActivationTypes = Optional.empty();
            } else {
                this.orderActivationTypes = Optional.of(orderActivationTypes.get());
            }
            return this;
        }

        public Builder orderActivationTypes(OrderActivationType orderActivationTypes) {
            this.orderActivationTypes = Optional.of(Collections.singletonList(orderActivationTypes));
            return this;
        }

        /**
         * <p>Filter by order ids.</p>
         */
        @JsonSetter(value = "order_ids", nulls = Nulls.SKIP)
        public Builder orderIds(Optional<List<String>> orderIds) {
            this.orderIds = orderIds;
            return this;
        }

        public Builder orderIds(List<String> orderIds) {
            this.orderIds = Optional.ofNullable(orderIds);
            return this;
        }

        public Builder orderIds(Nullable<List<String>> orderIds) {
            if (orderIds.isNull()) {
                this.orderIds = null;
            } else if (orderIds.isEmpty()) {
                this.orderIds = Optional.empty();
            } else {
                this.orderIds = Optional.of(orderIds.get());
            }
            return this;
        }

        public Builder orderIds(String orderIds) {
            this.orderIds = Optional.of(Collections.singletonList(orderIds));
            return this;
        }

        /**
         * <p>Search by order id, user id, patient name, shipping dob, or shipping recipient name.</p>
         */
        @JsonSetter(value = "search_input", nulls = Nulls.SKIP)
        public Builder searchInput(Optional<String> searchInput) {
            this.searchInput = searchInput;
            return this;
        }

        public Builder searchInput(String searchInput) {
            this.searchInput = Optional.ofNullable(searchInput);
            return this;
        }

        public Builder searchInput(Nullable<String> searchInput) {
            if (searchInput.isNull()) {
                this.searchInput = null;
            } else if (searchInput.isEmpty()) {
                this.searchInput = Optional.empty();
            } else {
                this.searchInput = Optional.of(searchInput.get());
            }
            return this;
        }

        /**
         * <p>Date from in YYYY-MM-DD or ISO formatted date time. If a date is provided without a time, the time will be set to 00:00:00</p>
         */
        @JsonSetter(value = "start_date", nulls = Nulls.SKIP)
        public Builder startDate(Optional<OffsetDateTime> startDate) {
            this.startDate = startDate;
            return this;
        }

        public Builder startDate(OffsetDateTime startDate) {
            this.startDate = Optional.ofNullable(startDate);
            return this;
        }

        public Builder startDate(Nullable<OffsetDateTime> startDate) {
            if (startDate.isNull()) {
                this.startDate = null;
            } else if (startDate.isEmpty()) {
                this.startDate = Optional.empty();
            } else {
                this.startDate = Optional.of(startDate.get());
            }
            return this;
        }

        /**
         * <p>Date to YYYY-MM-DD or ISO formatted date time. If a date is provided without a time, the time will be set to 23:59:59</p>
         */
        @JsonSetter(value = "end_date", nulls = Nulls.SKIP)
        public Builder endDate(Optional<OffsetDateTime> endDate) {
            this.endDate = endDate;
            return this;
        }

        public Builder endDate(OffsetDateTime endDate) {
            this.endDate = Optional.ofNullable(endDate);
            return this;
        }

        public Builder endDate(Nullable<OffsetDateTime> endDate) {
            if (endDate.isNull()) {
                this.endDate = null;
            } else if (endDate.isEmpty()) {
                this.endDate = Optional.empty();
            } else {
                this.endDate = Optional.of(endDate.get());
            }
            return this;
        }

        /**
         * <p>Date from in YYYY-MM-DD or ISO formatted date time. If a date is provided without a time, the time will be set to 00:00:00</p>
         */
        @JsonSetter(value = "updated_start_date", nulls = Nulls.SKIP)
        public Builder updatedStartDate(Optional<OffsetDateTime> updatedStartDate) {
            this.updatedStartDate = updatedStartDate;
            return this;
        }

        public Builder updatedStartDate(OffsetDateTime updatedStartDate) {
            this.updatedStartDate = Optional.ofNullable(updatedStartDate);
            return this;
        }

        public Builder updatedStartDate(Nullable<OffsetDateTime> updatedStartDate) {
            if (updatedStartDate.isNull()) {
                this.updatedStartDate = null;
            } else if (updatedStartDate.isEmpty()) {
                this.updatedStartDate = Optional.empty();
            } else {
                this.updatedStartDate = Optional.of(updatedStartDate.get());
            }
            return this;
        }

        /**
         * <p>Date to YYYY-MM-DD or ISO formatted date time. If a date is provided without a time, the time will be set to 00:00:00</p>
         */
        @JsonSetter(value = "updated_end_date", nulls = Nulls.SKIP)
        public Builder updatedEndDate(Optional<OffsetDateTime> updatedEndDate) {
            this.updatedEndDate = updatedEndDate;
            return this;
        }

        public Builder updatedEndDate(OffsetDateTime updatedEndDate) {
            this.updatedEndDate = Optional.ofNullable(updatedEndDate);
            return this;
        }

        public Builder updatedEndDate(Nullable<OffsetDateTime> updatedEndDate) {
            if (updatedEndDate.isNull()) {
                this.updatedEndDate = null;
            } else if (updatedEndDate.isEmpty()) {
                this.updatedEndDate = Optional.empty();
            } else {
                this.updatedEndDate = Optional.of(updatedEndDate.get());
            }
            return this;
        }

        /**
         * <p>Order key to sort by.</p>
         */
        @JsonSetter(value = "order_key", nulls = Nulls.SKIP)
        public Builder orderKey(Optional<GetOrdersLabTestsRequestOrderKey> orderKey) {
            this.orderKey = orderKey;
            return this;
        }

        public Builder orderKey(GetOrdersLabTestsRequestOrderKey orderKey) {
            this.orderKey = Optional.ofNullable(orderKey);
            return this;
        }

        public Builder orderKey(Nullable<GetOrdersLabTestsRequestOrderKey> orderKey) {
            if (orderKey.isNull()) {
                this.orderKey = null;
            } else if (orderKey.isEmpty()) {
                this.orderKey = Optional.empty();
            } else {
                this.orderKey = Optional.of(orderKey.get());
            }
            return this;
        }

        /**
         * <p>Order direction to sort by.</p>
         */
        @JsonSetter(value = "order_direction", nulls = Nulls.SKIP)
        public Builder orderDirection(Optional<GetOrdersLabTestsRequestOrderDirection> orderDirection) {
            this.orderDirection = orderDirection;
            return this;
        }

        public Builder orderDirection(GetOrdersLabTestsRequestOrderDirection orderDirection) {
            this.orderDirection = Optional.ofNullable(orderDirection);
            return this;
        }

        public Builder orderDirection(Nullable<GetOrdersLabTestsRequestOrderDirection> orderDirection) {
            if (orderDirection.isNull()) {
                this.orderDirection = null;
            } else if (orderDirection.isEmpty()) {
                this.orderDirection = Optional.empty();
            } else {
                this.orderDirection = Optional.of(orderDirection.get());
            }
            return this;
        }

        /**
         * <p>Filter by critical order status.</p>
         */
        @JsonSetter(value = "is_critical", nulls = Nulls.SKIP)
        public Builder isCritical(Optional<Boolean> isCritical) {
            this.isCritical = isCritical;
            return this;
        }

        public Builder isCritical(Boolean isCritical) {
            this.isCritical = Optional.ofNullable(isCritical);
            return this;
        }

        public Builder isCritical(Nullable<Boolean> isCritical) {
            if (isCritical.isNull()) {
                this.isCritical = null;
            } else if (isCritical.isEmpty()) {
                this.isCritical = Optional.empty();
            } else {
                this.isCritical = Optional.of(isCritical.get());
            }
            return this;
        }

        /**
         * <p>Filter by result interpretation of the lab test.</p>
         */
        @JsonSetter(value = "interpretation", nulls = Nulls.SKIP)
        public Builder interpretation(Optional<Interpretation> interpretation) {
            this.interpretation = interpretation;
            return this;
        }

        public Builder interpretation(Interpretation interpretation) {
            this.interpretation = Optional.ofNullable(interpretation);
            return this;
        }

        public Builder interpretation(Nullable<Interpretation> interpretation) {
            if (interpretation.isNull()) {
                this.interpretation = null;
            } else if (interpretation.isEmpty()) {
                this.interpretation = Optional.empty();
            } else {
                this.interpretation = Optional.of(interpretation.get());
            }
            return this;
        }

        /**
         * <p>Filter by user ID.</p>
         */
        @JsonSetter(value = "user_id", nulls = Nulls.SKIP)
        public Builder userId(Optional<String> userId) {
            this.userId = userId;
            return this;
        }

        public Builder userId(String userId) {
            this.userId = Optional.ofNullable(userId);
            return this;
        }

        public Builder userId(Nullable<String> userId) {
            if (userId.isNull()) {
                this.userId = null;
            } else if (userId.isEmpty()) {
                this.userId = Optional.empty();
            } else {
                this.userId = Optional.of(userId.get());
            }
            return this;
        }

        /**
         * <p>Filter by patient name.</p>
         */
        @JsonSetter(value = "patient_name", nulls = Nulls.SKIP)
        public Builder patientName(Optional<String> patientName) {
            this.patientName = patientName;
            return this;
        }

        public Builder patientName(String patientName) {
            this.patientName = Optional.ofNullable(patientName);
            return this;
        }

        public Builder patientName(Nullable<String> patientName) {
            if (patientName.isNull()) {
                this.patientName = null;
            } else if (patientName.isEmpty()) {
                this.patientName = Optional.empty();
            } else {
                this.patientName = Optional.of(patientName.get());
            }
            return this;
        }

        /**
         * <p>Filter by shipping recipient name.</p>
         */
        @JsonSetter(value = "shipping_recipient_name", nulls = Nulls.SKIP)
        public Builder shippingRecipientName(Optional<String> shippingRecipientName) {
            this.shippingRecipientName = shippingRecipientName;
            return this;
        }

        public Builder shippingRecipientName(String shippingRecipientName) {
            this.shippingRecipientName = Optional.ofNullable(shippingRecipientName);
            return this;
        }

        public Builder shippingRecipientName(Nullable<String> shippingRecipientName) {
            if (shippingRecipientName.isNull()) {
                this.shippingRecipientName = null;
            } else if (shippingRecipientName.isEmpty()) {
                this.shippingRecipientName = Optional.empty();
            } else {
                this.shippingRecipientName = Optional.of(shippingRecipientName.get());
            }
            return this;
        }

        /**
         * <p>Filter by order transaction ID</p>
         */
        @JsonSetter(value = "order_transaction_id", nulls = Nulls.SKIP)
        public Builder orderTransactionId(Optional<String> orderTransactionId) {
            this.orderTransactionId = orderTransactionId;
            return this;
        }

        public Builder orderTransactionId(String orderTransactionId) {
            this.orderTransactionId = Optional.ofNullable(orderTransactionId);
            return this;
        }

        public Builder orderTransactionId(Nullable<String> orderTransactionId) {
            if (orderTransactionId.isNull()) {
                this.orderTransactionId = null;
            } else if (orderTransactionId.isEmpty()) {
                this.orderTransactionId = Optional.empty();
            } else {
                this.orderTransactionId = Optional.of(orderTransactionId.get());
            }
            return this;
        }

        @JsonSetter(value = "page", nulls = Nulls.SKIP)
        public Builder page(Optional<Integer> page) {
            this.page = page;
            return this;
        }

        public Builder page(Integer page) {
            this.page = Optional.ofNullable(page);
            return this;
        }

        public Builder page(Nullable<Integer> page) {
            if (page.isNull()) {
                this.page = null;
            } else if (page.isEmpty()) {
                this.page = Optional.empty();
            } else {
                this.page = Optional.of(page.get());
            }
            return this;
        }

        @JsonSetter(value = "size", nulls = Nulls.SKIP)
        public Builder size(Optional<Integer> size) {
            this.size = size;
            return this;
        }

        public Builder size(Integer size) {
            this.size = Optional.ofNullable(size);
            return this;
        }

        public Builder size(Nullable<Integer> size) {
            if (size.isNull()) {
                this.size = null;
            } else if (size.isEmpty()) {
                this.size = Optional.empty();
            } else {
                this.size = Optional.of(size.get());
            }
            return this;
        }

        public GetOrdersLabTestsRequest build() {
            return new GetOrdersLabTestsRequest(
                    status,
                    orderType,
                    orderActivationTypes,
                    orderIds,
                    searchInput,
                    startDate,
                    endDate,
                    updatedStartDate,
                    updatedEndDate,
                    orderKey,
                    orderDirection,
                    isCritical,
                    interpretation,
                    userId,
                    patientName,
                    shippingRecipientName,
                    orderTransactionId,
                    page,
                    size,
                    additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
