/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.junction.api.resources.profile;

import com.junction.api.core.ClientOptions;
import com.junction.api.core.RequestOptions;
import com.junction.api.resources.profile.requests.GetProfileRequest;
import com.junction.api.resources.profile.requests.GetRawProfileRequest;
import com.junction.api.types.ClientFacingProfile;
import com.junction.api.types.RawProfile;

public class ProfileClient {
    protected final ClientOptions clientOptions;

    private final RawProfileClient rawClient;

    public ProfileClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawProfileClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawProfileClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Get profile for user_id
     */
    public ClientFacingProfile get(String userId) {
        return this.rawClient.get(userId).body();
    }

    /**
     * Get profile for user_id
     */
    public ClientFacingProfile get(String userId, RequestOptions requestOptions) {
        return this.rawClient.get(userId, requestOptions).body();
    }

    /**
     * Get profile for user_id
     */
    public ClientFacingProfile get(String userId, GetProfileRequest request) {
        return this.rawClient.get(userId, request).body();
    }

    /**
     * Get profile for user_id
     */
    public ClientFacingProfile get(String userId, GetProfileRequest request, RequestOptions requestOptions) {
        return this.rawClient.get(userId, request, requestOptions).body();
    }

    /**
     * Get raw profile for user_id
     */
    public RawProfile getRaw(String userId) {
        return this.rawClient.getRaw(userId).body();
    }

    /**
     * Get raw profile for user_id
     */
    public RawProfile getRaw(String userId, RequestOptions requestOptions) {
        return this.rawClient.getRaw(userId, requestOptions).body();
    }

    /**
     * Get raw profile for user_id
     */
    public RawProfile getRaw(String userId, GetRawProfileRequest request) {
        return this.rawClient.getRaw(userId, request).body();
    }

    /**
     * Get raw profile for user_id
     */
    public RawProfile getRaw(String userId, GetRawProfileRequest request, RequestOptions requestOptions) {
        return this.rawClient.getRaw(userId, request, requestOptions).body();
    }
}
