/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.junction.api.resources.profile;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.junction.api.core.ApiError;
import com.junction.api.core.ClientOptions;
import com.junction.api.core.JunctionException;
import com.junction.api.core.JunctionHttpResponse;
import com.junction.api.core.ObjectMappers;
import com.junction.api.core.QueryStringMapper;
import com.junction.api.core.RequestOptions;
import com.junction.api.errors.UnprocessableEntityError;
import com.junction.api.resources.profile.requests.GetProfileRequest;
import com.junction.api.resources.profile.requests.GetRawProfileRequest;
import com.junction.api.types.ClientFacingProfile;
import com.junction.api.types.HttpValidationError;
import com.junction.api.types.RawProfile;
import java.io.IOException;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;
import okhttp3.ResponseBody;

public class RawProfileClient {
    protected final ClientOptions clientOptions;

    public RawProfileClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    /**
     * Get profile for user_id
     */
    public JunctionHttpResponse<ClientFacingProfile> get(String userId) {
        return get(userId, GetProfileRequest.builder().build());
    }

    /**
     * Get profile for user_id
     */
    public JunctionHttpResponse<ClientFacingProfile> get(String userId, RequestOptions requestOptions) {
        return get(userId, GetProfileRequest.builder().build(), requestOptions);
    }

    /**
     * Get profile for user_id
     */
    public JunctionHttpResponse<ClientFacingProfile> get(String userId, GetProfileRequest request) {
        return get(userId, request, null);
    }

    /**
     * Get profile for user_id
     */
    public JunctionHttpResponse<ClientFacingProfile> get(
            String userId, GetProfileRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("v2/summary/profile")
                .addPathSegment(userId);
        if (request.getProvider().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "provider", request.getProvider().get(), false);
        }
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new JunctionHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ClientFacingProfile.class), response);
            }
            try {
                if (response.code() == 422) {
                    throw new UnprocessableEntityError(
                            ObjectMappers.JSON_MAPPER.readValue(responseBodyString, HttpValidationError.class),
                            response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new ApiError("Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new JunctionException("Network error executing HTTP request", e);
        }
    }

    /**
     * Get raw profile for user_id
     */
    public JunctionHttpResponse<RawProfile> getRaw(String userId) {
        return getRaw(userId, GetRawProfileRequest.builder().build());
    }

    /**
     * Get raw profile for user_id
     */
    public JunctionHttpResponse<RawProfile> getRaw(String userId, RequestOptions requestOptions) {
        return getRaw(userId, GetRawProfileRequest.builder().build(), requestOptions);
    }

    /**
     * Get raw profile for user_id
     */
    public JunctionHttpResponse<RawProfile> getRaw(String userId, GetRawProfileRequest request) {
        return getRaw(userId, request, null);
    }

    /**
     * Get raw profile for user_id
     */
    public JunctionHttpResponse<RawProfile> getRaw(
            String userId, GetRawProfileRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("v2/summary/profile")
                .addPathSegment(userId)
                .addPathSegments("raw");
        if (request.getProvider().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "provider", request.getProvider().get(), false);
        }
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new JunctionHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, RawProfile.class), response);
            }
            try {
                if (response.code() == 422) {
                    throw new UnprocessableEntityError(
                            ObjectMappers.JSON_MAPPER.readValue(responseBodyString, HttpValidationError.class),
                            response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new ApiError("Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new JunctionException("Network error executing HTTP request", e);
        }
    }
}
