/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.junction.api.resources.labtests.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class GetPaginatedLabTestsRequestOrderKey {
    public static final GetPaginatedLabTestsRequestOrderKey UPDATED_AT =
            new GetPaginatedLabTestsRequestOrderKey(Value.UPDATED_AT, "updated_at");

    public static final GetPaginatedLabTestsRequestOrderKey PRICE =
            new GetPaginatedLabTestsRequestOrderKey(Value.PRICE, "price");

    public static final GetPaginatedLabTestsRequestOrderKey CREATED_AT =
            new GetPaginatedLabTestsRequestOrderKey(Value.CREATED_AT, "created_at");

    private final Value value;

    private final String string;

    GetPaginatedLabTestsRequestOrderKey(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof GetPaginatedLabTestsRequestOrderKey
                        && this.string.equals(((GetPaginatedLabTestsRequestOrderKey) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case UPDATED_AT:
                return visitor.visitUpdatedAt();
            case PRICE:
                return visitor.visitPrice();
            case CREATED_AT:
                return visitor.visitCreatedAt();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static GetPaginatedLabTestsRequestOrderKey valueOf(String value) {
        switch (value) {
            case "updated_at":
                return UPDATED_AT;
            case "price":
                return PRICE;
            case "created_at":
                return CREATED_AT;
            default:
                return new GetPaginatedLabTestsRequestOrderKey(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        PRICE,

        CREATED_AT,

        UPDATED_AT,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitPrice();

        T visitCreatedAt();

        T visitUpdatedAt();

        T visitUnknown(String unknownType);
    }
}
